// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import type { BrexCore } from '../core/client';
import type { RequestOptions } from '../core/options';
import type { PagePromise } from '../core/pagination';
import type { paths } from './types.gen';

export class Cards {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Create card
     *
     * Creates a new card.
     * The `spend_controls` field is required when `limit_type` = `CARD`.
     * The `mailing_address` field is required for physical cards and is the shipping address used to send the card; it is not the same as the billing and mailing address used for online purchases.
     * The first 2 lines of this address must be under 60 characters long. Each user can only have up to 10 active physical cards.
     * For Empower accounts, this endpoint requires budget management. If your account does not have access to budget management features, a 403 response status will be returned.
     * If this is the case and you want to gain access to this endpoint, please contact Brex support.
     *
     * `POST /v2/cards` — requires OAuth scope: `cards`
     * Sends an `Idempotency-Key` header: `options.idempotencyKey`, or an auto-generated UUID.
     */
    create(
        body: NonNullable<paths['/v2/cards']['post']['requestBody']>['content']['application/json'],
        options?: RequestOptions,
    ): Promise<paths['/v2/cards']['post']['responses']['200']['content']['application/json']> {
        return this._core.request<
            paths['/v2/cards']['post']['responses']['200']['content']['application/json']
        >('POST', '/v2/cards', { body, idempotency: 'required', options });
    }

    /**
     * Create secure email to send card number
     *
     * Creates a secure email to send card number, CVV, and expiration date of a card by ID to the specified email.
     *
     * This endpoint is currently gated. If you would like to request access, please reach out to
     * developer-support@brex.com
     *
     * `POST /v2/cards/{id}/secure_email` — requires OAuth scope: `cards.pan`
     * Sends an `Idempotency-Key` header: `options.idempotencyKey`, or an auto-generated UUID.
     */
    emailNumber(
        id: paths['/v2/cards/{id}/secure_email']['post']['parameters']['path']['id'],
        body: NonNullable<
            paths['/v2/cards/{id}/secure_email']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<void> {
        return this._core.request<void>(
            'POST',
            `/v2/cards/${encodeURIComponent(id)}/secure_email`,
            { body, idempotency: 'required', options },
        );
    }

    /**
     * Get card
     *
     * Retrieves a card by ID. Only cards with `limit_type = CARD` have `spend_controls`
     *
     * `GET /v2/cards/{id}` — requires OAuth scope: `cards`, `cards.readonly`
     */
    get(
        id: paths['/v2/cards/{id}']['get']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<paths['/v2/cards/{id}']['get']['responses']['200']['content']['application/json']> {
        return this._core.request<
            paths['/v2/cards/{id}']['get']['responses']['200']['content']['application/json']
        >('GET', `/v2/cards/${encodeURIComponent(id)}`, { options });
    }

    /**
     * Get card number
     *
     * Retrieves card number, CVV, and expiration date of a card by ID.
     *
     * `GET /v2/cards/{id}/pan` — requires OAuth scope: `cards.pan`
     */
    getNumber(
        id: paths['/v2/cards/{id}/pan']['get']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<
        paths['/v2/cards/{id}/pan']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v2/cards/{id}/pan']['get']['responses']['200']['content']['application/json']
        >('GET', `/v2/cards/${encodeURIComponent(id)}/pan`, { options });
    }

    /**
     * List cards
     *
     * Lists all cards by a `user_id`.
     * Only cards with `limit_type = CARD` have `spend_controls`
     *
     * `GET /v2/cards` — requires OAuth scope: `cards.readonly`, `cards`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    list(
        query?: paths['/v2/cards']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<paths['/v2/cards']['get']['responses']['200']['content']['application/json']> {
        return this._core.list<
            paths['/v2/cards']['get']['responses']['200']['content']['application/json']
        >('/v2/cards', { query, options });
    }

    /**
     * Lock card
     *
     * Locks an existing, unlocked card. And the card owner will receive a notification about it.
     *
     * `POST /v2/cards/{id}/lock` — requires OAuth scope: `cards`
     * Supports an optional `Idempotency-Key` via `options.idempotencyKey`.
     */
    lock(
        id: paths['/v2/cards/{id}/lock']['post']['parameters']['path']['id'],
        body: NonNullable<
            paths['/v2/cards/{id}/lock']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<
        paths['/v2/cards/{id}/lock']['post']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v2/cards/{id}/lock']['post']['responses']['200']['content']['application/json']
        >('POST', `/v2/cards/${encodeURIComponent(id)}/lock`, {
            body,
            idempotency: 'optional',
            options,
        });
    }

    /**
     * Terminate card
     *
     * Terminates an existing card. The card owner will receive a notification about it.
     *
     * `POST /v2/cards/{id}/terminate` — requires OAuth scope: `cards`
     * Supports an optional `Idempotency-Key` via `options.idempotencyKey`.
     */
    terminate(
        id: paths['/v2/cards/{id}/terminate']['post']['parameters']['path']['id'],
        body: NonNullable<
            paths['/v2/cards/{id}/terminate']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<
        paths['/v2/cards/{id}/terminate']['post']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v2/cards/{id}/terminate']['post']['responses']['200']['content']['application/json']
        >('POST', `/v2/cards/${encodeURIComponent(id)}/terminate`, {
            body,
            idempotency: 'optional',
            options,
        });
    }

    /**
     * Unlock card
     *
     * Unlocks an existing card.
     *
     * `POST /v2/cards/{id}/unlock` — requires OAuth scope: `cards`
     * Supports an optional `Idempotency-Key` via `options.idempotencyKey`.
     */
    unlock(
        id: paths['/v2/cards/{id}/unlock']['post']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<
        paths['/v2/cards/{id}/unlock']['post']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v2/cards/{id}/unlock']['post']['responses']['200']['content']['application/json']
        >('POST', `/v2/cards/${encodeURIComponent(id)}/unlock`, {
            idempotency: 'optional',
            options,
        });
    }

    /**
     * Update card
     *
     * Update an existing vendor card
     *
     * `PUT /v2/cards/{id}` — requires OAuth scope: `cards`
     * Supports an optional `Idempotency-Key` via `options.idempotencyKey`.
     */
    update(
        id: paths['/v2/cards/{id}']['put']['parameters']['path']['id'],
        body: NonNullable<
            paths['/v2/cards/{id}']['put']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<paths['/v2/cards/{id}']['put']['responses']['200']['content']['application/json']> {
        return this._core.request<
            paths['/v2/cards/{id}']['put']['responses']['200']['content']['application/json']
        >('PUT', `/v2/cards/${encodeURIComponent(id)}`, { body, idempotency: 'optional', options });
    }
}

export class Companies {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Get company
     *
     * This endpoint returns the company associated with the OAuth2 access token.
     *
     * `GET /v2/company` — requires OAuth scope: `companies.readonly`
     */
    get(
        options?: RequestOptions,
    ): Promise<paths['/v2/company']['get']['responses']['200']['content']['application/json']> {
        return this._core.request<
            paths['/v2/company']['get']['responses']['200']['content']['application/json']
        >('GET', '/v2/company', { options });
    }
}

export class Departments {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Create department
     *
     * This endpoint creates a new department
     *
     * `POST /v2/departments` — requires OAuth scope: `departments`
     * Supports an optional `Idempotency-Key` via `options.idempotencyKey`.
     */
    create(
        body: NonNullable<
            paths['/v2/departments']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<
        paths['/v2/departments']['post']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v2/departments']['post']['responses']['200']['content']['application/json']
        >('POST', '/v2/departments', { body, idempotency: 'optional', options });
    }

    /**
     * Get department
     *
     * This endpoint gets a department by ID.
     *
     * `GET /v2/departments/{id}` — requires OAuth scope: `departments`, `departments.readonly`
     */
    get(
        id: paths['/v2/departments/{id}']['get']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<
        paths['/v2/departments/{id}']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v2/departments/{id}']['get']['responses']['200']['content']['application/json']
        >('GET', `/v2/departments/${encodeURIComponent(id)}`, { options });
    }

    /**
     * List departments
     *
     * This endpoint lists all departments.
     *
     * `GET /v2/departments` — requires OAuth scope: `departments`, `departments.readonly`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    list(
        query?: paths['/v2/departments']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<
        paths['/v2/departments']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.list<
            paths['/v2/departments']['get']['responses']['200']['content']['application/json']
        >('/v2/departments', { query, options });
    }
}

export class LegalEntities {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Get legal entity
     *
     * Get a legal entity by its ID.
     *
     * `GET /v2/legal_entities/{id}` — requires OAuth scope: `legal_entities`, `legal_entities.readonly`
     */
    get(
        id: paths['/v2/legal_entities/{id}']['get']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<
        paths['/v2/legal_entities/{id}']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v2/legal_entities/{id}']['get']['responses']['200']['content']['application/json']
        >('GET', `/v2/legal_entities/${encodeURIComponent(id)}`, { options });
    }

    /**
     * List legal entities
     *
     * List legal entities for the account.
     *
     * `GET /v2/legal_entities` — requires OAuth scope: `legal_entities`, `legal_entities.readonly`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    list(
        query?: paths['/v2/legal_entities']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<
        paths['/v2/legal_entities']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.list<
            paths['/v2/legal_entities']['get']['responses']['200']['content']['application/json']
        >('/v2/legal_entities', { query, options });
    }
}

export class Locations {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Create location
     *
     * This endpoint creates a new location.
     *
     * `POST /v2/locations` — requires OAuth scope: `locations`
     * Supports an optional `Idempotency-Key` via `options.idempotencyKey`.
     */
    create(
        body: NonNullable<
            paths['/v2/locations']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<paths['/v2/locations']['post']['responses']['200']['content']['application/json']> {
        return this._core.request<
            paths['/v2/locations']['post']['responses']['200']['content']['application/json']
        >('POST', '/v2/locations', { body, idempotency: 'optional', options });
    }

    /**
     * Get location
     *
     * This endpoint gets a location by ID.
     *
     * `GET /v2/locations/{id}` — requires OAuth scope: `locations`, `locations.readonly`
     */
    get(
        id: paths['/v2/locations/{id}']['get']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<
        paths['/v2/locations/{id}']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v2/locations/{id}']['get']['responses']['200']['content']['application/json']
        >('GET', `/v2/locations/${encodeURIComponent(id)}`, { options });
    }

    /**
     * List locations
     *
     * This endpoint lists all locations.
     *
     * `GET /v2/locations` — requires OAuth scope: `locations`, `locations.readonly`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    list(
        query?: paths['/v2/locations']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<
        paths['/v2/locations']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.list<
            paths['/v2/locations']['get']['responses']['200']['content']['application/json']
        >('/v2/locations', { query, options });
    }
}

export class Titles {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Create title
     *
     * This endpoint creates a new title
     *
     * `POST /v2/titles` — requires OAuth scope: `titles`
     * Supports an optional `Idempotency-Key` via `options.idempotencyKey`.
     */
    create(
        body: NonNullable<
            paths['/v2/titles']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<paths['/v2/titles']['post']['responses']['200']['content']['application/json']> {
        return this._core.request<
            paths['/v2/titles']['post']['responses']['200']['content']['application/json']
        >('POST', '/v2/titles', { body, idempotency: 'optional', options });
    }

    /**
     * Get title
     *
     * This endpoint gets a title by ID.
     *
     * `GET /v2/titles/{id}` — requires OAuth scope: `titles`, `titles.readonly`
     */
    get(
        id: paths['/v2/titles/{id}']['get']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<paths['/v2/titles/{id}']['get']['responses']['200']['content']['application/json']> {
        return this._core.request<
            paths['/v2/titles/{id}']['get']['responses']['200']['content']['application/json']
        >('GET', `/v2/titles/${encodeURIComponent(id)}`, { options });
    }

    /**
     * List titles
     *
     * This endpoint lists all titles.
     *
     * `GET /v2/titles` — requires OAuth scope: `titles`, `titles.readonly`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    list(
        query?: paths['/v2/titles']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<paths['/v2/titles']['get']['responses']['200']['content']['application/json']> {
        return this._core.list<
            paths['/v2/titles']['get']['responses']['200']['content']['application/json']
        >('/v2/titles', { query, options });
    }
}

export class Users {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Invite user
     *
     * This endpoint invites a new user as an employee.
     * To update user's role, check out [this article](https://support.brex.com/how-do-i-change-another-user-s-role/).
     *
     * `POST /v2/users` — requires OAuth scope: `users`
     * Supports an optional `Idempotency-Key` via `options.idempotencyKey`.
     */
    create(
        body: NonNullable<paths['/v2/users']['post']['requestBody']>['content']['application/json'],
        options?: RequestOptions,
    ): Promise<paths['/v2/users']['post']['responses']['200']['content']['application/json']> {
        return this._core.request<
            paths['/v2/users']['post']['responses']['200']['content']['application/json']
        >('POST', '/v2/users', { body, idempotency: 'optional', options });
    }

    /**
     * Get user
     *
     * This endpoint gets a user by ID.
     *
     * `GET /v2/users/{id}` — requires OAuth scope: `users`, `users.readonly`
     */
    get(
        id: paths['/v2/users/{id}']['get']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<paths['/v2/users/{id}']['get']['responses']['200']['content']['application/json']> {
        return this._core.request<
            paths['/v2/users/{id}']['get']['responses']['200']['content']['application/json']
        >('GET', `/v2/users/${encodeURIComponent(id)}`, { options });
    }

    /**
     * Get limit for the user
     *
     * This endpoint gets the monthly limit for the user including the monthly available limit.
     *
     * `GET /v2/users/{id}/limit` — requires OAuth scope: `users`, `users.readonly`
     */
    getLimit(
        id: paths['/v2/users/{id}/limit']['get']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<
        paths['/v2/users/{id}/limit']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v2/users/{id}/limit']['get']['responses']['200']['content']['application/json']
        >('GET', `/v2/users/${encodeURIComponent(id)}/limit`, { options });
    }

    /**
     * Get current user
     *
     * This endpoint returns the user associated with the OAuth2 access token.
     *
     * `GET /v2/users/me` — requires OAuth scope: `users`, `users.readonly`
     */
    getMe(
        options?: RequestOptions,
    ): Promise<paths['/v2/users/me']['get']['responses']['200']['content']['application/json']> {
        return this._core.request<
            paths['/v2/users/me']['get']['responses']['200']['content']['application/json']
        >('GET', '/v2/users/me', { options });
    }

    /**
     * List users
     *
     * This endpoint lists all users. To find a user id by email, you can filter using the `email` query parameter.
     *
     * `GET /v2/users` — requires OAuth scope: `users`, `users.readonly`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    list(
        query?: paths['/v2/users']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<paths['/v2/users']['get']['responses']['200']['content']['application/json']> {
        return this._core.list<
            paths['/v2/users']['get']['responses']['200']['content']['application/json']
        >('/v2/users', { query, options });
    }

    /**
     * Set limit for the user
     *
     * This endpoint sets the monthly limit for a user.
     * The limit amount must be non-negative.
     * To unset the monthly limit of the user, just set `monthly_limit` to null.
     *
     * `POST /v2/users/{id}/limit` — requires OAuth scope: `users`
     * Supports an optional `Idempotency-Key` via `options.idempotencyKey`.
     */
    setLimit(
        id: paths['/v2/users/{id}/limit']['post']['parameters']['path']['id'],
        body: NonNullable<
            paths['/v2/users/{id}/limit']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<
        paths['/v2/users/{id}/limit']['post']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v2/users/{id}/limit']['post']['responses']['200']['content']['application/json']
        >('POST', `/v2/users/${encodeURIComponent(id)}/limit`, {
            body,
            idempotency: 'optional',
            options,
        });
    }

    /**
     * Update user
     *
     * This endpoint updates a user. Any parameters not provided will be left unchanged.
     *
     * `PUT /v2/users/{id}` — requires OAuth scope: `users`
     * Supports an optional `Idempotency-Key` via `options.idempotencyKey`.
     */
    update(
        id: paths['/v2/users/{id}']['put']['parameters']['path']['id'],
        body: NonNullable<
            paths['/v2/users/{id}']['put']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<paths['/v2/users/{id}']['put']['responses']['200']['content']['application/json']> {
        return this._core.request<
            paths['/v2/users/{id}']['put']['responses']['200']['content']['application/json']
        >('PUT', `/v2/users/${encodeURIComponent(id)}`, { body, idempotency: 'optional', options });
    }
}

export class BrexTeam {
    readonly cards: Cards;
    readonly companies: Companies;
    readonly departments: Departments;
    readonly legalEntities: LegalEntities;
    readonly locations: Locations;
    readonly titles: Titles;
    readonly users: Users;
    constructor(core: BrexCore) {
        this.cards = new Cards(core);
        this.companies = new Companies(core);
        this.departments = new Departments(core);
        this.legalEntities = new LegalEntities(core);
        this.locations = new Locations(core);
        this.titles = new Titles(core);
        this.users = new Users(core);
    }
}
