// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import { BrexCore } from '../core/client';
import type { BrexOptions } from '../core/options';
import { BrexTeam } from './client.gen';

export * from '../core';
export {
    BrexTeam,
    Cards,
    Companies,
    Departments,
    LegalEntities,
    Locations,
    Titles,
    Users,
} from './client.gen';
export type * from './schemas.gen';
export type { components as TeamComponents, paths as TeamPaths } from './types.gen';

/** Standalone client for the Brex Team API. */
export function createTeamClient(options: BrexOptions): BrexTeam {
    return new BrexTeam(new BrexCore(options));
}
