// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import type { components } from './types.gen';

export type AccountType = components['schemas']['AccountType'];
export type Address = components['schemas']['Address'];
export type Card = components['schemas']['Card'];
export type CardAttributePreferences = components['schemas']['CardAttributePreferences'];
export type CardExpiration = components['schemas']['CardExpiration'];
export type CardNumberResponse = components['schemas']['CardNumberResponse'];
export type CardOwner = components['schemas']['CardOwner'];
export type CardStatus = components['schemas']['CardStatus'];
export type CardType = components['schemas']['CardType'];
export type ChangeCardReason = components['schemas']['ChangeCardReason'];
export type CompanyResponse = components['schemas']['CompanyResponse'];
export type CreateCardRequest = components['schemas']['CreateCardRequest'];
export type CreateDepartmentRequest = components['schemas']['CreateDepartmentRequest'];
export type CreateLocationRequest = components['schemas']['CreateLocationRequest'];
export type CreateTitleRequest = components['schemas']['CreateTitleRequest'];
export type CreateUserRequest = components['schemas']['CreateUserRequest'];
export type DepartmentResponse = components['schemas']['DepartmentResponse'];
export type LegalEntity = components['schemas']['LegalEntity'];
export type LegalEntityStatus = components['schemas']['LegalEntityStatus'];
export type LimitType = components['schemas']['LimitType'];
export type LocationResponse = components['schemas']['LocationResponse'];
export type LockCardRequest = components['schemas']['LockCardRequest'];
export type LockedMerchantDetails = components['schemas']['LockedMerchantDetails'];
export type Money = components['schemas']['Money'];
export type OwnerType = components['schemas']['OwnerType'];
export type Page_Card_ = components['schemas']['Page_Card_'];
export type Page_DepartmentResponse_ = components['schemas']['Page_DepartmentResponse_'];
export type Page_LegalEntity_ = components['schemas']['Page_LegalEntity_'];
export type Page_LocationResponse_ = components['schemas']['Page_LocationResponse_'];
export type Page_TitleResponse_ = components['schemas']['Page_TitleResponse_'];
export type Page_UserResponse_ = components['schemas']['Page_UserResponse_'];
export type SecureEmailForCardDetailsRequest =
    components['schemas']['SecureEmailForCardDetailsRequest'];
export type SetUserLimitRequest = components['schemas']['SetUserLimitRequest'];
export type SpendControl = components['schemas']['SpendControl'];
export type SpendControlRequest = components['schemas']['SpendControlRequest'];
export type SpendControlUpdateRequest = components['schemas']['SpendControlUpdateRequest'];
export type SpendDuration = components['schemas']['SpendDuration'];
export type TerminateCardRequest = components['schemas']['TerminateCardRequest'];
export type ThreeDomainSecureEnabledPreference =
    components['schemas']['ThreeDomainSecureEnabledPreference'];
export type TitleResponse = components['schemas']['TitleResponse'];
export type UpdateCardRequest = components['schemas']['UpdateCardRequest'];
export type UpdateUserRequest = components['schemas']['UpdateUserRequest'];
export type UpdateUserStatus = components['schemas']['UpdateUserStatus'];
export type UserLimitResponse = components['schemas']['UserLimitResponse'];
export type UserOwner = components['schemas']['UserOwner'];
export type UserResponse = components['schemas']['UserResponse'];
export type UserStatus = components['schemas']['UserStatus'];
