// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate
export interface paths {
  "/v2/cards": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List cards
     * @description Lists all cards by a `user_id`.
     *     Only cards with `limit_type = CARD` have `spend_controls`
     */
    get: operations["listCardsByUserId"];
    put?: never;
    /**
     * Create card
     * @description Creates a new card.
     *     The `spend_controls` field is required when `limit_type` = `CARD`.
     *     The `mailing_address` field is required for physical cards and is the shipping address used to send the card; it is not the same as the billing and mailing address used for online purchases.
     *     The first 2 lines of this address must be under 60 characters long. Each user can only have up to 10 active physical cards.
     *     For Empower accounts, this endpoint requires budget management. If your account does not have access to budget management features, a 403 response status will be returned.
     *     If this is the case and you want to gain access to this endpoint, please contact Brex support.
     */
    post: operations["createCard"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/cards/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get card
     * @description Retrieves a card by ID. Only cards with `limit_type = CARD` have `spend_controls`
     */
    get: operations["getCardById"];
    /**
     * Update card
     * @description Update an existing vendor card
     */
    put: operations["updateCard"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/cards/{id}/lock": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Lock card
     * @description Locks an existing, unlocked card. And the card owner will receive a notification about it.
     */
    post: operations["lockCard"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/cards/{id}/pan": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get card number
     * @description Retrieves card number, CVV, and expiration date of a card by ID.
     */
    get: operations["getCardNumber"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/cards/{id}/secure_email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create secure email to send card number
     * @description Creates a secure email to send card number, CVV, and expiration date of a card by ID to the specified email.
     *
     *     This endpoint is currently gated. If you would like to request access, please reach out to
     *     developer-support@brex.com
     */
    post: operations["emailCardNumber"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/cards/{id}/terminate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Terminate card
     * @description Terminates an existing card. The card owner will receive a notification about it.
     */
    post: operations["terminateCard"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/cards/{id}/unlock": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Unlock card
     * @description Unlocks an existing card.
     */
    post: operations["unlockCard"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/company": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get company
     * @description This endpoint returns the company associated with the OAuth2 access token.
     */
    get: operations["getCompany"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/departments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List departments
     * @description This endpoint lists all departments.
     */
    get: operations["listDepartments"];
    put?: never;
    /**
     * Create department
     * @description This endpoint creates a new department
     */
    post: operations["createDepartment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/departments/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get department
     * @description This endpoint gets a department by ID.
     */
    get: operations["getDepartmentById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/legal_entities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List legal entities
     * @description List legal entities for the account.
     */
    get: operations["listLegalEntities"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/legal_entities/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get legal entity
     * @description Get a legal entity by its ID.
     */
    get: operations["getLegalEntity"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/locations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List locations
     * @description This endpoint lists all locations.
     */
    get: operations["listLocations"];
    put?: never;
    /**
     * Create location
     * @description This endpoint creates a new location.
     */
    post: operations["createLocation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/locations/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get location
     * @description This endpoint gets a location by ID.
     */
    get: operations["getLocationById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/titles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List titles
     * @description This endpoint lists all titles.
     */
    get: operations["listTitles"];
    put?: never;
    /**
     * Create title
     * @description This endpoint creates a new title
     */
    post: operations["createTitle"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/titles/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get title
     * @description This endpoint gets a title by ID.
     */
    get: operations["getTitleById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List users
     * @description This endpoint lists all users. To find a user id by email, you can filter using the `email` query parameter.
     */
    get: operations["listUsers"];
    put?: never;
    /**
     * Invite user
     * @description This endpoint invites a new user as an employee.
     *     To update user's role, check out [this article](https://support.brex.com/how-do-i-change-another-user-s-role/).
     */
    post: operations["createUser"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/users/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user
     * @description This endpoint gets a user by ID.
     */
    get: operations["getUserById"];
    /**
     * Update user
     * @description This endpoint updates a user. Any parameters not provided will be left unchanged.
     */
    put: operations["updateUser"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/users/{id}/limit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get limit for the user
     * @description This endpoint gets the monthly limit for the user including the monthly available limit.
     */
    get: operations["getUserLimit"];
    put?: never;
    /**
     * Set limit for the user
     * @description This endpoint sets the monthly limit for a user.
     *     The limit amount must be non-negative.
     *     To unset the monthly limit of the user, just set `monthly_limit` to null.
     */
    post: operations["setUserLimit"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get current user
     * @description This endpoint returns the user associated with the OAuth2 access token.
     */
    get: operations["getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    AccountType: "BREX_CLASSIC" | "BREX_EMPOWER";
    /** @description Company business address (must be in the US; no PO box or virtual/forwarding addresses allowed). */
    Address: {
      /** @description City, district, suburb, town, or village. */
      city?: string | null;
      /** @description Two-letter country code (ISO 3166-1 alpha-2). */
      country?: string | null;
      /** @description Address line 1, no PO Box. */
      line1?: string | null;
      /** @description Address line 2 (e.g., apartment, suite, unit, or building). */
      line2?: string | null;
      /** @description Phone number. */
      phone_number?: string | null;
      /** @description ZIP or postal code. */
      postal_code?: string | null;
      /** @description For US-addressed the 2-letter State abbreviation. For international-addresses the county, providence, or region. */
      state?: string | null;
    };
    /** @description Only cards with limit_type = CARD have spend_controls */
    Card: {
      billing_address: components["schemas"]["Address"];
      budget_id?: string | null;
      card_name: string;
      card_type?: components["schemas"]["CardType"] | null;
      expiration_date: components["schemas"]["CardExpiration"];
      /**
       * @description Indicates whether a card has been transferred. Transferred cards have a spending restriction: we only allow transactions \
       *     at online vendors where this card was previously used before the transfer.
       */
      has_been_transferred?: boolean;
      id: string;
      last_four: string;
      limit_type: components["schemas"]["LimitType"];
      mailing_address?: components["schemas"]["Address"] | null;
      /**
       * @description Set of key value pairs associated with this object. Please do not store any personally identifiable or sensitive information here.
       *     Limitations: maximum of 50 keys, keys cannot exceed 40 characters, values cannot exceed 500 characters.
       */
      metadata?: {
        [key: string]: string;
      } | null;
      owner: components["schemas"]["CardOwner"];
      spend_controls?: components["schemas"]["SpendControl"] | null;
      status?: components["schemas"]["CardStatus"] | null;
    };
    CardAttributePreferences: {
      three_domain_secure_enabled_preference?:
        | components["schemas"]["ThreeDomainSecureEnabledPreference"]
        | null;
    };
    /**
     * @description Card expiration year and month. Cards expire on the last day of the expiration month.
     *
     *     The expiration date is in UTC for cards starting with 555671, 428803 and 485932.
     *     And the expiration date is in PST for cards starting with 511572.
     */
    CardExpiration: {
      /** Format: int32 */
      month: number;
      /** Format: int32 */
      year: number;
    };
    /** @description Card number, CVV, and expiration date of a card. */
    CardNumberResponse: {
      cvv: string;
      expiration_date: components["schemas"]["CardExpiration"];
      holder_name: string;
      id: string;
      number: string;
    };
    CardOwner: components["schemas"]["UserOwner"];
    /** @enum {string} */
    CardStatus: "ACTIVE" | "SHIPPED" | "LOCKED" | "TERMINATED";
    /** @enum {string} */
    CardType: "VIRTUAL" | "PHYSICAL";
    /**
     * @description Reason for card termination.
     * @enum {string}
     */
    ChangeCardReason:
      | "CARD_DAMAGED"
      | "CARD_LOST"
      | "CARD_NOT_RECEIVED"
      | "DO_NOT_NEED_PHYSICAL_CARD"
      | "DO_NOT_NEED_VIRTUAL_CARD"
      | "FRAUD"
      | "OTHER";
    CompanyResponse: {
      accountType: components["schemas"]["AccountType"];
      id: string;
      legal_name: string;
      mailing_address: components["schemas"]["Address"];
    };
    /**
     * @description The `spend_controls` field is required when `limit_type` = `CARD`.
     *     The `shipping_address` field is required for physical cards, and the first 2 lines of the address must be under 60 characters long.
     */
    CreateCardRequest: {
      card_attribute_preferences?: components["schemas"]["CardAttributePreferences"] | null;
      card_name: string;
      card_type: components["schemas"]["CardType"];
      limit_type: components["schemas"]["LimitType"];
      mailing_address?: components["schemas"]["Address"] | null;
      /**
       * @description Set of key value pairs associated with this object. Please do not store any personally identifiable or sensitive information here.
       *     Limitations: maximum of 50 keys, keys cannot exceed 40 characters, values cannot exceed 500 characters.
       */
      metadata?: {
        [key: string]: string;
      } | null;
      owner: components["schemas"]["CardOwner"];
      spend_controls?: components["schemas"]["SpendControlRequest"] | null;
    };
    CreateDepartmentRequest: {
      /** @description Description of the department */
      description?: string | null;
      /** @description Name of the department */
      name: string;
    };
    CreateLocationRequest: {
      /** @description Description of the location */
      description?: string | null;
      /** @description Name of the location */
      name: string;
    };
    CreateTitleRequest: {
      /** @description Name of the title */
      name: string;
    };
    CreateUserRequest: {
      department_id?: string | null;
      /** Format: email */
      email: string;
      first_name: string;
      last_name: string;
      location_id?: string | null;
      manager_id?: string | null;
      /** @description The metadata or customized attributes of the user. Maximum number of entries: 100 */
      metadata?: {
        [key: string]: string;
      } | null;
      title_id?: string | null;
    };
    DepartmentResponse: {
      /** @description Description of the department */
      description?: string | null;
      id: string;
      /** @description Name of the department */
      name: string;
    };
    /**
     * Legal Entity
     * @description A Brex legal entity.
     */
    LegalEntity: {
      billingAddress: components["schemas"]["Address"] & unknown;
      /**
       * Format: date-time
       * @description Timestamp, in UTC, when this legal entity was created.
       */
      createdAt: string;
      /** @description The display name of this legal entity. */
      displayName: string;
      /** @description The ID of this legal entity. */
      id: string;
      /** @description Whether this is the default entity of the account. */
      isDefault?: boolean;
      status: components["schemas"]["LegalEntityStatus"] & unknown;
    };
    /**
     * @description The possible statuses for an entity's verification in Brex.
     * @enum {string}
     */
    LegalEntityStatus: "UNSUBMITTED" | "UNVERIFIED" | "IN_PROGRESS" | "VERIFIED" | "REJECTED";
    /**
     * @description `limit_type = CARD` for vendor cards. Vendor cards must have a `card_type` of `VIRTUAL`
     *     and do not rely on the user specific limit.
     *
     *     For corporate cards, `limit_type = USER`.
     *
     *     Learn more about different card types [here](https://support.brex.com/what-are-the-different-types-of-cards-i-can-get/).
     * @enum {string}
     */
    LimitType: "CARD" | "USER";
    LocationResponse: {
      /** @description Description of the location */
      description?: string | null;
      id: string;
      /** @description Name of the location */
      name: string;
    };
    /** @description Parameters for locking a card. */
    LockCardRequest: {
      /** @description Description for locking a card */
      description?: string | null;
      reason: components["schemas"]["ChangeCardReason"];
    };
    /** @description Merchant details used for restricting or blocking transactions. */
    LockedMerchantDetails: {
      /**
       * @description The name of the merchant.
       * @example Github
       */
      name: string;
    };
    /**
     * @description Money fields can be signed or unsigned. Fields are signed (an unsigned value will be interpreted as positive). The amount of money will be represented in the smallest denomination
     *     of the currency indicated. For example, USD 7.00 will be represented in cents with an amount of 700.
     */
    Money: {
      /**
       * Format: int64
       * @description The amount of money, in the smallest denomination of the currency indicated by currency. For example, when currency is USD, amount is in cents.
       * @example 700
       */
      amount: number;
      /**
       * @description The type of currency, in ISO 4217 format.
       * @default USD
       * @example USD
       */
      currency: string | null;
    };
    /** @enum {string} */
    OwnerType: "USER";
    Page_Card_: {
      items: components["schemas"]["Card"][];
      next_cursor?: string | null;
    };
    Page_DepartmentResponse_: {
      items: components["schemas"]["DepartmentResponse"][];
      next_cursor?: string | null;
    };
    Page_LegalEntity_: {
      items: components["schemas"]["LegalEntity"][];
      next_cursor?: string | null;
    };
    Page_LocationResponse_: {
      items: components["schemas"]["LocationResponse"][];
      next_cursor?: string | null;
    };
    Page_TitleResponse_: {
      items: components["schemas"]["TitleResponse"][];
      next_cursor?: string | null;
    };
    Page_UserResponse_: {
      items: components["schemas"]["UserResponse"][];
      next_cursor?: string | null;
    };
    SecureEmailForCardDetailsRequest: {
      /**
       * Format: int32
       * @description Link expiry in number of days. Defaults to 30
       */
      expiry_days?: number | null;
      /** @description Message to send with the card details */
      message?: string | null;
      /** @description Email address to send card details to */
      recipient_email: string;
      /** @description Sender name. Shows up in the subject of the email */
      sender_name: string;
    };
    /** @description Request that sets the monthly user limit. */
    SetUserLimitRequest: {
      monthly_limit?: components["schemas"]["Money"] | null;
    };
    SpendControl: {
      /**
       * @description List of merchant details where card transactions are allowed. Empty if no allowed merchant details are configured.
       * @example [{"name": "Github"}, {"name": "AWS"}]
       */
      allowed_merchant_details?: components["schemas"]["LockedMerchantDetails"][] | null;
      /**
       * @description List of merchant details where card transactions are blocked. Empty if no blocked merchant details are configured.
       * @example [{"name": "Apple"}, {"name": "Amazon"}]
       */
      blocked_merchant_details?: components["schemas"]["LockedMerchantDetails"][] | null;
      /**
       * Format: date
       * @description The `lock_after_date` is in UTC.
       */
      lock_after_date?: string | null;
      reason?: string | null;
      spend_available?: components["schemas"]["Money"] | null;
      spend_duration?: components["schemas"]["SpendDuration"] | null;
      spend_limit?: components["schemas"]["Money"] | null;
    };
    /** @description When `limit_type = CARD`, `spend_controls` must be set. When `limit type = USER`, `spend_controls` must be `null`. */
    SpendControlRequest: {
      /**
       * @description List of merchants where card transactions are allowed. Cannot be used together with blocked_merchant_details. Maximum 50
       *     merchant details.
       * @example [{"name": "Github"}, {"name": "AWS"}]
       */
      allowed_merchant_details?: components["schemas"]["LockedMerchantDetails"][] | null;
      /**
       * @description List of merchants where card transactions are blocked. Cannot be used together with allowed_merchant_details. Maximum 50
       *     merchant details.
       * @example [{"name": "Apple"}, {"name": "Amazon"}]
       */
      blocked_merchant_details?: components["schemas"]["LockedMerchantDetails"][] | null;
      /** Format: date */
      lock_after_date?: string | null;
      /**
       * @description If using the Empower platform, a new `budget` will be created for this card. You can specify a `parent_budget` that your new
       *     `budget` will be nested under. If `parent_budget_id` is null, we will nest the new budget under the top-level account `budget`.
       */
      parent_budget_id?: string | null;
      policy_id?: string | null;
      reason?: string | null;
      spend_duration: components["schemas"]["SpendDuration"];
      spend_limit: components["schemas"]["Money"];
    };
    SpendControlUpdateRequest: {
      /**
       * @description List of merchants where card transactions are allowed. Cannot be used together with blocked_merchant_details. Maximum 50
       *     merchant details.
       * @example [{"name": "Github"}, {"name": "AWS"}]
       */
      allowed_merchant_details?: components["schemas"]["LockedMerchantDetails"][] | null;
      /**
       * @description List of merchants where card transactions are blocked. Cannot be used together with allowed_merchant_details. Maximum 50
       *     merchant details.
       * @example [{"name": "Apple"}, {"name": "Amazon"}]
       */
      blocked_merchant_details?: components["schemas"]["LockedMerchantDetails"][] | null;
      /** Format: date */
      lock_after_date?: string | null;
      reason?: string | null;
      spend_duration?: components["schemas"]["SpendDuration"] | null;
      spend_limit?: components["schemas"]["Money"] | null;
    };
    /**
     * @description Spend limit refresh frequency
     *         - MONTHLY: The spend limit refreshes every month
     *         - QUARTERLY: The spend limit refreshes every quarter
     *         - YEARLY: The spend limit refreshes every year
     *         - ONE_TIME: The limit does not refresh
     * @enum {string}
     */
    SpendDuration: "MONTHLY" | "QUARTERLY" | "YEARLY" | "ONE_TIME";
    /** @description Parameters for terminating a card. */
    TerminateCardRequest: {
      /** @description Description for terminating a card */
      description?: string | null;
      reason: components["schemas"]["ChangeCardReason"];
    };
    /**
     * @description Whether to enable 3-D secure protocol on this card.
     * @enum {string}
     */
    ThreeDomainSecureEnabledPreference:
      | "THREE_DOMAIN_SECURE_ENABLED"
      | "THREE_DOMAIN_SECURE_DISABLED";
    TitleResponse: {
      id: string;
      /** @description Name of the title */
      name: string;
    };
    UpdateCardRequest: {
      /**
       * @description Set of key value pairs associated with this object. Please do not store any personally identifiable or sensitive information here.
       *     Limitations: maximum of 50 keys, keys cannot exceed 40 characters, values cannot exceed 500 characters.
       */
      metadata?: {
        [key: string]: string;
      } | null;
      spend_controls?: components["schemas"]["SpendControlUpdateRequest"] | null;
    };
    UpdateUserRequest: {
      department_id?: string | null;
      location_id?: string | null;
      /** @description The user id of the manager of this user */
      manager_id?: string | null;
      /** @description The metadata or customized attributes of the user. Maximum number of entries: 100 */
      metadata?: {
        [key: string]: string;
      } | null;
      status?: components["schemas"]["UpdateUserStatus"] | null;
      title_id?: string | null;
    };
    /**
     * @description Acceptable user status for update. To suspend a user, set status to 'disabled'. To unsuspend a user, set status to 'active'.
     * @enum {string}
     */
    UpdateUserStatus: "ACTIVE" | "DISABLED";
    UserLimitResponse: {
      monthly_available?: components["schemas"]["Money"] | null;
      monthly_limit?: components["schemas"]["Money"] | null;
    };
    UserOwner: {
      type: components["schemas"]["OwnerType"];
      user_id: string;
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "USER";
    };
    UserResponse: {
      department_id?: string | null;
      /** @description Email address of the user */
      email: string;
      /** @description First name of the user */
      first_name: string;
      id: string;
      /** @description Last name of the user */
      last_name: string;
      location_id?: string | null;
      /** @description The user id of the manager of this user */
      manager_id?: string | null;
      /** @description The metadata or customized attributes of the user. Maximum number of entries: 100 */
      metadata?: {
        [key: string]: string;
      } | null;
      /** @description Identifier that is displayed on the IDP or HR system, eg, if OKTA identifies you as user xyz */
      remote_display_id?: string | null;
      status?: components["schemas"]["UserStatus"] | null;
      title_id?: string | null;
    };
    /**
     * @description Status of the user
     * @enum {string}
     */
    UserStatus:
      | "INVITED"
      | "ACTIVE"
      | "CLOSED"
      | "DISABLED"
      | "DELETED"
      | "PENDING_ACTIVATION"
      | "INACTIVE"
      | "ARCHIVED";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listCardsByUserId: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number | null;
        user_id?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description listCardsByUserId 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_Card_"];
        };
      };
    };
  };
  createCard: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCardRequest"];
      };
    };
    responses: {
      /** @description createCard 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Card"];
        };
      };
    };
  };
  getCardById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getCardById 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Card"];
        };
      };
    };
  };
  updateCard: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCardRequest"];
      };
    };
    responses: {
      /** @description updateCard 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Card"];
        };
      };
    };
  };
  lockCard: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LockCardRequest"];
      };
    };
    responses: {
      /** @description lockCard 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Card"];
        };
      };
    };
  };
  getCardNumber: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getCardNumber 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CardNumberResponse"];
        };
      };
    };
  };
  emailCardNumber: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SecureEmailForCardDetailsRequest"];
      };
    };
    responses: {
      /** @description emailCardNumber 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  terminateCard: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TerminateCardRequest"];
      };
    };
    responses: {
      /** @description terminateCard 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Card"];
        };
      };
    };
  };
  unlockCard: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description unlockCard 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Card"];
        };
      };
    };
  };
  getCompany: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getCompany 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompanyResponse"];
        };
      };
    };
  };
  listDepartments: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number | null;
        name?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description listDepartments 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_DepartmentResponse_"];
        };
      };
    };
  };
  createDepartment: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateDepartmentRequest"];
      };
    };
    responses: {
      /** @description createDepartment 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DepartmentResponse"];
        };
      };
    };
  };
  getDepartmentById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getDepartmentById 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DepartmentResponse"];
        };
      };
    };
  };
  listLegalEntities: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description listLegalEntities 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_LegalEntity_"];
        };
      };
    };
  };
  getLegalEntity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getLegalEntity 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LegalEntity"];
        };
      };
    };
  };
  listLocations: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number | null;
        name?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description listLocations 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_LocationResponse_"];
        };
      };
    };
  };
  createLocation: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateLocationRequest"];
      };
    };
    responses: {
      /** @description createLocation 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LocationResponse"];
        };
      };
    };
  };
  getLocationById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getLocationById 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LocationResponse"];
        };
      };
    };
  };
  listTitles: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number | null;
        name?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description listTitles 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_TitleResponse_"];
        };
      };
    };
  };
  createTitle: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTitleRequest"];
      };
    };
    responses: {
      /** @description createTitle 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TitleResponse"];
        };
      };
    };
  };
  getTitleById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getTitleById 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TitleResponse"];
        };
      };
    };
  };
  listUsers: {
    parameters: {
      query?: {
        cursor?: string | null;
        email?: string | null;
        "expand[]"?: string[] | null;
        limit?: number | null;
        remote_display_id?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description listUsers 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_UserResponse_"];
        };
      };
    };
  };
  createUser: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserRequest"];
      };
    };
    responses: {
      /** @description createUser 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  getUserById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getUserById 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  updateUser: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserRequest"];
      };
    };
    responses: {
      /** @description updateUser 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  getUserLimit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getUserLimit 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserLimitResponse"];
        };
      };
    };
  };
  setUserLimit: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetUserLimitRequest"];
      };
    };
    responses: {
      /** @description setUserLimit 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserLimitResponse"];
        };
      };
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description getMe 200 response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
}
