// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import { BrexCore } from '../core/client';
import type { BrexOptions } from '../core/options';
import { BrexFields } from './client.gen';

export * from '../core';
export { BrexFields, Fields, FieldValues } from './client.gen';
export type * from './schemas.gen';
export type { components as FieldsComponents, paths as FieldsPaths } from './types.gen';

/** Standalone client for the Brex Fields API. */
export function createFieldsClient(options: BrexOptions): BrexFields {
    return new BrexFields(new BrexCore(options));
}
