// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import type { components } from './types.gen';

export type CreateFieldValueBody = components['schemas']['CreateFieldValueBody'];
export type CreateFieldValueListBody = components['schemas']['CreateFieldValueListBody'];
export type CreateFieldValueListResponse = components['schemas']['CreateFieldValueListResponse'];
export type DeleteFieldValue_ByBrexId = components['schemas']['DeleteFieldValue.ByBrexId'];
export type DeleteFieldValue_ByRemoteId = components['schemas']['DeleteFieldValue.ByRemoteId'];
export type DeleteFieldValue_ByValueId = components['schemas']['DeleteFieldValue.ByValueId'];
export type DeleteFieldValueBody = components['schemas']['DeleteFieldValueBody'];
export type DeleteFieldValueListBody = components['schemas']['DeleteFieldValueListBody'];
export type DeletedFieldValueListResponse = components['schemas']['DeletedFieldValueListResponse'];
export type Field = components['schemas']['Field'];
export type FieldCreateBody = components['schemas']['FieldCreateBody'];
export type FieldGroup = components['schemas']['FieldGroup'];
export type FieldUpdateBody = components['schemas']['FieldUpdateBody'];
export type FieldValue = components['schemas']['FieldValue'];
export type Page_FieldValue_ = components['schemas']['Page_FieldValue_'];
export type Page_Field_ = components['schemas']['Page_Field_'];
export type UpdateFieldValue_ByBrexId = components['schemas']['UpdateFieldValue.ByBrexId'];
export type UpdateFieldValue_ByRemoteId = components['schemas']['UpdateFieldValue.ByRemoteId'];
export type UpdateFieldValue_ByValueId = components['schemas']['UpdateFieldValue.ByValueId'];
export type UpdateFieldValueBody = components['schemas']['UpdateFieldValueBody'];
export type UpdateFieldValueDataBody = components['schemas']['UpdateFieldValueDataBody'];
export type UpdateFieldValueListBody = components['schemas']['UpdateFieldValueListBody'];
export type UpdateFieldValueListResponse = components['schemas']['UpdateFieldValueListResponse'];
