// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate
export interface paths {
    '/v1/fields': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List custom fields
         * @description List custom fields under the same account
         */
        get: operations['listFields'];
        put?: never;
        /**
         * Create a custom field
         * @description Create a custom field
         */
        post: operations['createField'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/fields/{field_id}/values': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List custom field values
         * @description List values under the same custom field
         */
        get: operations['listFieldValues'];
        /**
         * Update custom field values
         * @description Update custom field values (up to 1000 values at once) for a specific field
         */
        put: operations['updateFieldValues'];
        /**
         * Create custom field values
         * @description Create custom field values (up to 1000 values at once) for a specific field
         */
        post: operations['createFieldValues'];
        /**
         * Delete custom field values
         * @description Delete custom field values (up to 1000 values at once) for a specific field
         */
        delete: operations['deleteFieldValues'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/fields/{field_id}/values/{brex_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a field value
         * @description Get a field value by field ID and field value ID
         */
        get: operations['getFieldValueById'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/fields/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get custom field
         * @description Get a custom field by Brex ID
         */
        get: operations['getFieldById'];
        /**
         * Update a custom field
         * @description Update a field by ID
         */
        put: operations['updateField'];
        post?: never;
        /**
         * Delete a custom field
         * @description Delete a custom field by Brex ID
         */
        delete: operations['deleteField'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Field value creation
         * @description Represents the data needed to create a field value
         */
        CreateFieldValueBody: {
            /** @description Indicates whether the field value is disabled. A disabled value is not selectable: it no longer appears as a selectable option in the dropdown and cannot be chosen on new transactions. Records that already use the value are unaffected. */
            is_disabled?: boolean | null;
            /**
             * @description Remote/external ID of custom field value from external system (e.g. ERP or HRIS system)
             * @example foo_bar
             */
            remote_id?: string | null;
            /** @description The display name of the field value */
            value: string;
            /**
             * @description The value ID or code of the field value; Usually it is a unique identifier for the custom field value in the remote system
             * @example FooBar
             */
            value_id?: string | null;
        };
        /**
         * Field value list creation
         * @description Represents the data needed to create multiple field values. It can't contain more than 1000 values at once.
         */
        CreateFieldValueListBody: {
            /** @description The list of field values to be created */
            items: components['schemas']['CreateFieldValueBody'][];
        };
        /**
         * Field value list
         * @description Represents a list of field values definition
         */
        CreateFieldValueListResponse: {
            /** @description The list of created field values */
            items: components['schemas']['FieldValue'][];
        };
        /**
         * Field value deleted response
         * @description Represents the confirmation of number of deleted field values
         */
        DeletedFieldValueListResponse: Record<string, never>;
        /**
         * by `brex_id`
         * @description Represents the data needed to delete a field value using its `brex_id`.
         */
        'DeleteFieldValue.ByBrexId': {
            /**
             * @description The internal Brex ID of the field value
             * @example efo_foobar
             */
            brex_id: string;
        };
        /**
         * by `remote_id`
         * @description Represents the data needed to delete a field value using its `remote_id`.
         */
        'DeleteFieldValue.ByRemoteId': {
            /**
             * @description Remote/external ID of custom field value from external system (e.g. ERP or HRIS system)
             * @example foo_bar
             */
            remote_id: string;
        };
        /**
         * by `value_id`
         * @description Represents the data needed to delete a field value using its `value_id`.
         */
        'DeleteFieldValue.ByValueId': {
            /**
             * @description The value ID or code of the field value; Usually it is a unique identifier for the custom field value in the remote system
             * @example FooBar
             */
            value_id: string;
        };
        /**
         * Field value to delete
         * @description Represents the data needed to delete a field value.
         */
        DeleteFieldValueBody:
            | components['schemas']['DeleteFieldValue.ByBrexId']
            | components['schemas']['DeleteFieldValue.ByValueId']
            | components['schemas']['DeleteFieldValue.ByRemoteId'];
        /**
         * Field value list deletion
         * @description Represents the data needed to delete field values. It can't contain more than 1000 values at once.
         */
        DeleteFieldValueListBody: {
            items: components['schemas']['DeleteFieldValueBody'][];
        };
        /**
         * Field
         * @description Represents a field definition
         */
        Field: {
            /**
             * @description The internal Brex ID of the field
             * @example extended_field_foobar
             */
            brex_id: string;
            group?: (components['schemas']['FieldGroup'] & unknown) | null;
            /** @description Indicates whether the field is disabled. A disabled field is not selectable: it is no longer offered as an option in the Brex dropdown and cannot be applied to new transactions. Records that already reference the field are unaffected. */
            is_disabled: boolean;
            /** @description The name of the field */
            name: string | null;
            /**
             * @description Remote/external ID of custom field from external system (e.g. ERP or HRIS system)
             * @example foo_bar
             */
            remote_id?: string | null;
            /**
             * Format: date-time
             * @description The last updated timestamp of the field
             */
            updated_at: string;
        };
        /**
         * Field creation
         * @description Represents the data needed to create a field. To create a field in the `ERP` group you must first set up an Accounting Integration and supply its `integration_id`.
         */
        FieldCreateBody: {
            group: components['schemas']['FieldGroup'] & unknown;
            /**
             * @description The ID of the Accounting Integration to associate this field with. This property is **required** when `group` is `ERP`: it must reference an existing Accounting Integration, and requests that omit it or send `null` for an `ERP` field are rejected. For all other groups (`ACCOUNTING`, `USER`, `TRAVEL`) `integration_id` is not applicable and should be left null.
             * @example int_123
             */
            integration_id?: string | null;
            /** @description Indicates whether the field is disabled. A disabled field is not selectable: it is no longer offered as an option in the Brex dropdown and cannot be applied to new transactions. Records that already reference the field are unaffected. */
            is_disabled?: boolean | null;
            /** @description The name of the field */
            name: string;
            /**
             * @description Remote/external ID of custom field from external system (e.g. ERP or HRIS system)
             * @example foo_bar
             */
            remote_id?: string | null;
        };
        /**
         * @description The category of the field, indicating its purpose or context. Supported groups are:
         *
         *     * `ACCOUNTING` — Fields used to categorize transactions for accounting purposes (for example, expense categories or cost centers) that are managed directly within Brex.
         *
         *     * `USER` — Fields associated with users, used to capture user-specific attributes.
         *
         *     * `ERP` — Fields that are synced with an external ERP/accounting system through an Accounting Integration. Creating an Accounting Integration is a prerequisite for creating fields in the `ERP` group, and each `ERP` field must reference that integration through `integration_id`.
         *
         *     * `TRAVEL` — Fields used in the context of travel bookings and expenses.
         * @enum {string}
         */
        FieldGroup: 'ACCOUNTING' | 'USER' | 'ERP' | 'TRAVEL';
        /**
         * Field update
         * @description Represents the data needed to update a field
         */
        FieldUpdateBody: {
            /** @description Indicates whether the field is disabled. A disabled field is not selectable: it is no longer offered as an option in the Brex dropdown and cannot be applied to new transactions. Records that already reference the field are unaffected. */
            is_disabled?: boolean | null;
            /** @description The name of the field */
            name?: string | null;
        };
        /**
         * Field value
         * @description Represents a field value definition
         */
        FieldValue: {
            /**
             * @description The internal Brex ID of the field value
             * @example efo_foobar
             */
            brex_id: string;
            /**
             * @description The ID of the parent field this value belongs to
             * @example extended_field_foobar
             */
            field_id: string;
            /** @description Indicates whether the field value is disabled. A disabled value is not selectable: it no longer appears as a selectable option in the dropdown and cannot be chosen on new transactions. Records that already use the value are unaffected. */
            is_disabled: boolean;
            /**
             * @description Remote/external ID of custom field value from external system (e.g. ERP or HRIS system)
             * @example foo_bar
             */
            remote_id?: string | null;
            /**
             * Format: date-time
             * @description The last updated timestamp of the field value
             */
            updated_at: string;
            /** @description The display name of the field value */
            value: string;
            /**
             * @description The value ID or code of the field value; Usually it is a unique identifier for the custom field value in the remote system
             * @example foo_bar
             */
            value_id?: string | null;
        };
        Page_Field_: {
            items: components['schemas']['Field'][];
            next_cursor?: string | null;
        };
        Page_FieldValue_: {
            items: components['schemas']['FieldValue'][];
            next_cursor?: string | null;
        };
        /**
         * by `brex_id`
         * @description Represents the data needed to update a field value using its `brex_id`.
         */
        'UpdateFieldValue.ByBrexId': {
            /**
             * @description The internal Brex ID of the field value
             * @example efo_foobar
             */
            brex_id: string;
            data: components['schemas']['UpdateFieldValueDataBody'] & unknown;
        };
        /**
         * by `remote_id`
         * @description Represents the data needed to update a field value using its `remote_id`.
         */
        'UpdateFieldValue.ByRemoteId': {
            data: components['schemas']['UpdateFieldValueDataBody'] & unknown;
            /**
             * @description Remote/external ID of custom field value from external system (e.g. ERP or HRIS system)
             * @example foo_bar
             */
            remote_id: string;
        };
        /**
         * by `value_id`
         * @description Represents the data needed to update a field value using its `value_id`.
         */
        'UpdateFieldValue.ByValueId': {
            data: components['schemas']['UpdateFieldValueDataBody'] & unknown;
            /**
             * @description The value ID or code of the field value; Usually it is a unique identifier for the custom field value in the remote system
             * @example FooBar
             */
            value_id: string;
        };
        /**
         * Field value to update
         * @description Represents the data needed to update a field value.
         */
        UpdateFieldValueBody:
            | components['schemas']['UpdateFieldValue.ByBrexId']
            | components['schemas']['UpdateFieldValue.ByValueId']
            | components['schemas']['UpdateFieldValue.ByRemoteId'];
        /**
         * Field value update data
         * @description Represents the updated data of a field value
         */
        UpdateFieldValueDataBody: {
            /** @description Indicates whether the field value is disabled. A disabled value is not selectable: it no longer appears as a selectable option in the dropdown and cannot be chosen on new transactions. Records that already use the value are unaffected. */
            is_disabled?: boolean | null;
            /** @description The display name of the field value */
            value?: string | null;
        };
        /**
         * Field value list update
         * @description Represents the data needed to update multiple field values. It can't contain more than 1000 values at once.
         */
        UpdateFieldValueListBody: {
            items: components['schemas']['UpdateFieldValueBody'][];
        };
        /**
         * Field value updated list
         * @description Represents a list of updated field values
         */
        UpdateFieldValueListResponse: {
            /** @description The list of updated field values */
            items: components['schemas']['FieldValue'][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listFields: {
        parameters: {
            query?: {
                /** @description The cursor to use for pagination. This is the `next_cursor` value returned from the previous response. */
                cursor?: string | null;
                /**
                 * @description The Brex identifiers of the field to filter by
                 * @example extended_field_foobar
                 */
                'field_id[]'?: string[] | null;
                /** @description Controls the maximum number of field values returned in the response. It can't be greater than 1000. */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List custom fields response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Page_Field_'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createField: {
        parameters: {
            query?: never;
            header: {
                /** @description Idempotency key for this request. */
                'Idempotency-Key': string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['FieldCreateBody'];
            };
        };
        responses: {
            /** @description Create custom field response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Field'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listFieldValues: {
        parameters: {
            query?: {
                /**
                 * @description Field value Brex identifier(s) to filter by
                 * @example efo_foobar
                 */
                'brex_id[]'?: string[] | null;
                /** @description The cursor to use for pagination. This is the `next_cursor` value returned from the previous response. */
                cursor?: string | null;
                /** @description Controls the maximum number of field values returned in the response. It can't be greater than 1000. */
                limit?: number | null;
                /**
                 * @description Field value remote identifier(s) to filter by
                 * @example foo_bar
                 */
                'remote_id[]'?: string[] | null;
                /**
                 * @description Field value's value to filter by
                 * @example Foobar
                 */
                value?: string | null;
                /**
                 * @description Field value identifier(s) to filter by
                 * @example FooBar
                 */
                'value_id[]'?: string[] | null;
            };
            header?: never;
            path: {
                /**
                 * @description The Field Brex identifier
                 * @example extended_field_foobar
                 */
                field_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List custom field values response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Page_FieldValue_'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateFieldValues: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The Field Brex identifier
                 * @example extended_field_foobar
                 */
                field_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['UpdateFieldValueListBody'];
            };
        };
        responses: {
            /** @description Update custom field value list response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['UpdateFieldValueListResponse'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createFieldValues: {
        parameters: {
            query?: never;
            header: {
                /** @description Idempotency key for this request. */
                'Idempotency-Key': string;
            };
            path: {
                /**
                 * @description The Field Brex identifier
                 * @example extended_field_foobar
                 */
                field_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['CreateFieldValueListBody'];
            };
        };
        responses: {
            /** @description Create custom field values response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['CreateFieldValueListResponse'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteFieldValues: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The Field Brex identifier
                 * @example extended_field_foobar
                 */
                field_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['DeleteFieldValueListBody'];
            };
        };
        responses: {
            /** @description Delete custom field value list response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['DeletedFieldValueListResponse'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFieldValueById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The field value ID (`brex_id`) to retrieve.
                 * @example efo_foobar
                 */
                brex_id: string;
                /**
                 * @description The Field Brex identifier
                 * @example extended_field_foobar
                 */
                field_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get a field value response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['FieldValue'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFieldById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The Brex identifier of the field to retrieve
                 * @example extended_field_foobar
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get custom field response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Field'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateField: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The Brex identifier of the field to update
                 * @example extended_field_foobar
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['FieldUpdateBody'];
            };
        };
        responses: {
            /** @description Update custom field response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Field'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteField: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The Brex identifier of the field to delete
                 * @example extended_field_foobar
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete custom field response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
