// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import type { BrexCore } from '../core/client';
import type { RequestOptions } from '../core/options';
import type { PagePromise } from '../core/pagination';
import type { paths } from './types.gen';

export class CardExpenses {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Get a card expense
     *
     * This endpoint is deprecated. Use the "Get an expense" (`GET /v1/expenses/{id}`) endpoint instead.
     *
     * `GET /v1/expenses/card/{expense_id}` — requires OAuth scope: `expenses.card.readonly`, `expenses.card`
     * @deprecated Marked deprecated in the Brex OpenAPI spec.
     */
    get(
        expenseId: paths['/v1/expenses/card/{expense_id}']['get']['parameters']['path']['expense_id'],
        query?: paths['/v1/expenses/card/{expense_id}']['get']['parameters']['query'],
        options?: RequestOptions,
    ): Promise<
        paths['/v1/expenses/card/{expense_id}']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v1/expenses/card/{expense_id}']['get']['responses']['200']['content']['application/json']
        >('GET', `/v1/expenses/card/${encodeURIComponent(expenseId)}`, { query, options });
    }

    /**
     * List card expenses
     *
     * This endpoint is deprecated. Use the "List expenses" (`GET /v1/expenses`) endpoint instead.
     *
     * `GET /v1/expenses/card` — requires OAuth scope: `expenses.card.readonly`, `expenses.card`
     * Await for a single page, or `for await` to iterate items across all pages.
     * @deprecated Marked deprecated in the Brex OpenAPI spec.
     */
    list(
        query?: paths['/v1/expenses/card']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<
        paths['/v1/expenses/card']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.list<
            paths['/v1/expenses/card']['get']['responses']['200']['content']['application/json']
        >('/v1/expenses/card', { query, options });
    }

    /**
     * Update an expense
     *
     * Update an expense. Admin and bookkeeper have access to any expense, and regular users can only access their own.
     *
     * `PUT /v1/expenses/card/{expense_id}` — requires OAuth scope: `expenses.card`
     */
    update(
        expenseId: paths['/v1/expenses/card/{expense_id}']['put']['parameters']['path']['expense_id'],
        body: NonNullable<
            paths['/v1/expenses/card/{expense_id}']['put']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<
        paths['/v1/expenses/card/{expense_id}']['put']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v1/expenses/card/{expense_id}']['put']['responses']['200']['content']['application/json']
        >('PUT', `/v1/expenses/card/${encodeURIComponent(expenseId)}`, { body, options });
    }
}

export class Expenses {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Get an expense
     *
     * Get an expense by its ID.
     *
     * `GET /v1/expenses/{id}` — requires OAuth scope: `expenses.card.readonly`, `expenses.card`
     */
    get(
        id: paths['/v1/expenses/{id}']['get']['parameters']['path']['id'],
        query?: paths['/v1/expenses/{id}']['get']['parameters']['query'],
        options?: RequestOptions,
    ): Promise<
        paths['/v1/expenses/{id}']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v1/expenses/{id}']['get']['responses']['200']['content']['application/json']
        >('GET', `/v1/expenses/${encodeURIComponent(id)}`, { query, options });
    }

    /**
     * List expenses
     *
     * List expenses under the same account. Admin and bookkeeper have access to any expense, and regular users can only access their own.
     *
     * `GET /v1/expenses` — requires OAuth scope: `expenses.card.readonly`, `expenses.card`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    list(
        query?: paths['/v1/expenses']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<
        paths['/v1/expenses']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.list<
            paths['/v1/expenses']['get']['responses']['200']['content']['application/json']
        >('/v1/expenses', { query, options });
    }
}

export class Receipts {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Create a new receipt match
     *
     * The `uri` will be a pre-signed S3 URL allowing you to upload the receipt securely. This URL can only be used for a `PUT` operation and expires 30 minutes after its creation. Once your upload is complete, we will try to match the receipt with existing expenses.
     *
     * Refer to these [docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html) on how to upload to this pre-signed S3 URL. We highly recommend using one of AWS SDKs if they're available for your language to upload these files.
     *
     * `POST /v1/expenses/card/receipt_match`
     */
    match(
        body: NonNullable<
            paths['/v1/expenses/card/receipt_match']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<
        paths['/v1/expenses/card/receipt_match']['post']['responses']['201']['content']['application/json']
    > {
        return this._core.request<
            paths['/v1/expenses/card/receipt_match']['post']['responses']['201']['content']['application/json']
        >('POST', '/v1/expenses/card/receipt_match', { body, options });
    }

    /**
     * Create a new receipt upload
     *
     * The `uri` will be a pre-signed S3 URL allowing you to upload the receipt securely. This URL can only be used for a `PUT` operation and expires 30 minutes after its creation. Once your upload is complete, we will try to match the receipt with existing expenses.
     *
     * Refer to these [docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html) on how to upload to this pre-signed S3 URL. We highly recommend using one of AWS SDKs if they're available for your language to upload these files.
     *
     * `POST /v1/expenses/card/{expense_id}/receipt_upload`
     */
    upload(
        expenseId: paths['/v1/expenses/card/{expense_id}/receipt_upload']['post']['parameters']['path']['expense_id'],
        body: NonNullable<
            paths['/v1/expenses/card/{expense_id}/receipt_upload']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<
        paths['/v1/expenses/card/{expense_id}/receipt_upload']['post']['responses']['201']['content']['application/json']
    > {
        return this._core.request<
            paths['/v1/expenses/card/{expense_id}/receipt_upload']['post']['responses']['201']['content']['application/json']
        >('POST', `/v1/expenses/card/${encodeURIComponent(expenseId)}/receipt_upload`, {
            body,
            options,
        });
    }
}

export class BrexExpenses {
    readonly cardExpenses: CardExpenses;
    readonly expenses: Expenses;
    readonly receipts: Receipts;
    constructor(core: BrexCore) {
        this.cardExpenses = new CardExpenses(core);
        this.expenses = new Expenses(core);
        this.receipts = new Receipts(core);
    }
}
