// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import { BrexCore } from '../core/client';
import type { BrexOptions } from '../core/options';
import { BrexExpenses } from './client.gen';

export * from '../core';
export { BrexExpenses, CardExpenses, Expenses, Receipts } from './client.gen';
export type * from './schemas.gen';
export type { components as ExpensesComponents, paths as ExpensesPaths } from './types.gen';

/** Standalone client for the Brex Expenses API. */
export function createExpensesClient(options: BrexOptions): BrexExpenses {
    return new BrexExpenses(new BrexCore(options));
}
