// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate
export interface paths {
    '/v1/expenses': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List expenses
         * @description List expenses under the same account. Admin and bookkeeper have access to any expense, and regular users can only access their own.
         */
        get: operations['listExpenses'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/expenses/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an expense
         * @description Get an expense by its ID.
         */
        get: operations['getExpense'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/expenses/card': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List card expenses
         * @deprecated
         * @description This endpoint is deprecated. Use the "List expenses" (`GET /v1/expenses`) endpoint instead.
         */
        get: operations['listExpenses_1'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/expenses/card/{expense_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a card expense
         * @deprecated
         * @description This endpoint is deprecated. Use the "Get an expense" (`GET /v1/expenses/{id}`) endpoint instead.
         */
        get: operations['getCardExpense'];
        /**
         * Update an expense
         * @description Update an expense. Admin and bookkeeper have access to any expense, and regular users can only access their own.
         */
        put: operations['updateExpense'];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/expenses/card/{expense_id}/receipt_upload': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new receipt upload
         * @description The `uri` will be a pre-signed S3 URL allowing you to upload the receipt securely. This URL can only be used for a `PUT` operation and expires 30 minutes after its creation. Once your upload is complete, we will try to match the receipt with existing expenses.
         *
         *     Refer to these [docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html) on how to upload to this pre-signed S3 URL. We highly recommend using one of AWS SDKs if they're available for your language to upload these files.
         */
        post: operations['receiptUpload'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/expenses/card/receipt_match': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new receipt match
         * @description The `uri` will be a pre-signed S3 URL allowing you to upload the receipt securely. This URL can only be used for a `PUT` operation and expires 30 minutes after its creation. Once your upload is complete, we will try to match the receipt with existing expenses.
         *
         *     Refer to these [docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html) on how to upload to this pre-signed S3 URL. We highly recommend using one of AWS SDKs if they're available for your language to upload these files.
         */
        post: operations['receiptMatch'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Company business address (must be in the US; no PO box or virtual/forwarding addresses allowed). */
        Address: {
            /** @description City, district, suburb, town, or village. */
            city?: string | null;
            /** @description Two-letter country code (ISO 3166-1 alpha-2). */
            country?: string | null;
            /** @description Address line 1, no PO Box. */
            line1?: string | null;
            /** @description Address line 2 (e.g., apartment, suite, unit, or building). */
            line2?: string | null;
            /** @description Phone number. */
            phone_number?: string | null;
            /** @description ZIP or postal code. */
            postal_code?: string | null;
            /** @description For US-addressed the 2-letter State abbreviation. For international-addresses the county, providence, or region. */
            state?: string | null;
        };
        ApprovalStepDetails: {
            copilot_reviewer?: components['schemas']['User'] | null;
            pending_reviewers?: components['schemas']['User'][] | null;
            /** Format: date-time */
            resolved_at?: string | null;
            reviewer?: components['schemas']['User'] | null;
            status?: string | null;
        };
        /**
         * Boolean list value
         * @description Boolean list value for a custom field
         */
        BooleanListValue: {
            data?: boolean[] | null;
            /**
             * @description The type of the custom field data.
             * @enum {string}
             */
            data_type: 'BOOLEAN';
        } & (components['schemas']['CustomField.ValueWrapper.MultipleValueWrapper'] &
            WithRequired<components['schemas']['CustomField.ValueWrapper'], 'data_type'>);
        /**
         * Boolean value
         * @description Boolean value for a custom field
         */
        BooleanValue: {
            /** @description The data of the custom field. */
            data?: boolean | null;
            /**
             * @description The type of the custom field data.
             * @enum {string}
             */
            data_type: 'BOOLEAN';
        } & (components['schemas']['CustomField.ValueWrapper.SingleValueWrapper'] &
            WithRequired<components['schemas']['CustomField.ValueWrapper'], 'data_type'>);
        Budget: {
            /** @description Unique ID for the Budget. */
            id: string;
            /** @description Name for the Budget. */
            name: string;
        };
        CardPaymentInstrument: {
            type: components['schemas']['PaymentInstrumentType'];
        } & {
            /** @description Unique ID for the card. */
            id: string;
            type: components['schemas']['PaymentInstrumentType'];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: 'CARD';
        };
        /**
         * @description The category of expenses.
         * @enum {string}
         */
        Category:
            | 'ADVERTISING_AND_MARKETING'
            | 'GROCERY'
            | 'TELEPHONY'
            | 'OFFICE_SUPPLIES'
            | 'PRIVATE_AIR_TRAVEL'
            | 'CLOTHING'
            | 'CAR_RENTAL'
            | 'VEHICLE_EXPENSES'
            | 'RESTAURANTS'
            | 'GAMBLING'
            | 'FLOWERS'
            | 'ELECTRONICS'
            | 'LEGAL_SERVICES'
            | 'UTILITIES'
            | 'FURNITURE'
            | 'BARS_AND_NIGHTLIFE'
            | 'LAUNDRY'
            | 'EVENT_EXPENSES'
            | 'SHIPPING'
            | 'OTHER_TRAVEL_EXPENSES'
            | 'CHARITY'
            | 'SOFTWARE_NON_RECURRING'
            | 'LODGING'
            | 'FACILITIES_EXPENSES'
            | 'SERVERS'
            | 'CONFERENCES'
            | 'FOOD_DELIVERY'
            | 'RENT'
            | 'AIRLINE_EXPENSES'
            | 'OTHER_BUSINESS_EXPENSES'
            | 'BANK_AND_FINANCIAL_FEES'
            | 'BOOKS_AND_NEWSPAPERS'
            | 'CONSULTANT_AND_CONTRACTOR'
            | 'CORPORATE_INSURANCE'
            | 'DIGITAL_GOODS'
            | 'FEES_AND_LICENSES_AND_TAXES'
            | 'GAS_AND_FUEL'
            | 'GENERAL_MERCHANDISE'
            | 'MEDICAL'
            | 'MEMBERSHIPS_AND_CLUBS'
            | 'PARKING_EXPENSES'
            | 'POLITICAL_DONATIONS'
            | 'PUBLIC_TRANSPORTATION'
            | 'RECURRING_SOFTWARE_AND_SAAS'
            | 'RIDESHARE_AND_TAXI'
            | 'TOLL_AND_BRIDGE_FEES'
            | 'TRAINING_AND_EDUCATION'
            | 'TRAVEL_WIFI';
        /** @description The pre-signed file upload URI and unique identifier of the request. */
        CreateAsyncFileUploadResponse: {
            /** @description The unique identifier for the request. */
            id: string;
            /**
             * @description The pre-signed S3 link that should be used to upload the file.
             *     The maximum size accepted for this document is 50 MB.
             */
            uri: string;
        };
        /** @description The location associated with the expense. */
        CustomerLocation: {
            /** @description The unique identifier for the location. */
            id: string;
            /** @description The name of the location. */
            name: string;
        };
        CustomField: {
            /** @description The key of the custom field. */
            key: string;
            value: components['schemas']['CustomField.ValueWrapper'] &
                (
                    | components['schemas']['StringValue']
                    | components['schemas']['DecimalValue']
                    | components['schemas']['BooleanValue']
                    | components['schemas']['EnumValue']
                    | components['schemas']['TimestampValue']
                    | components['schemas']['DateValue']
                    | components['schemas']['MoneyValue']
                    | components['schemas']['OptionStringValue']
                    | components['schemas']['StringListValue']
                    | components['schemas']['DecimalListValue']
                    | components['schemas']['BooleanListValue']
                    | components['schemas']['EnumListValue']
                    | components['schemas']['TimestampListValue']
                    | components['schemas']['DateListValue']
                    | components['schemas']['MoneyListValue']
                    | components['schemas']['OptionStringListValue']
                );
        };
        /** @description Base class for custom field values */
        'CustomField.ValueWrapper': {
            data_type: components['schemas']['CustomFieldDataType'] & unknown;
            value_type: components['schemas']['CustomFieldValueType'] & unknown;
        };
        /** @description Multiple value wrapper for custom fields */
        'CustomField.ValueWrapper.MultipleValueWrapper': {
            value_type: components['schemas']['CustomFieldValueType'] & unknown;
        } & WithRequired<components['schemas']['CustomField.ValueWrapper'], 'value_type'>;
        /** @description Single value wrapper for custom fields */
        'CustomField.ValueWrapper.SingleValueWrapper': {
            value_type: components['schemas']['CustomFieldValueType'] & unknown;
        } & WithRequired<components['schemas']['CustomField.ValueWrapper'], 'value_type'>;
        /**
         * @description The type of the custom field data.
         * @enum {string}
         */
        CustomFieldDataType:
            | 'STRING'
            | 'DECIMAL'
            | 'BOOLEAN'
            | 'ENUM'
            | 'TIMESTAMP'
            | 'DATE'
            | 'MONEY'
            | 'OPTION_STRING';
        /**
         * @description The type of the custom field value.
         * @enum {string}
         */
        CustomFieldValueType: 'SINGLE_VALUE' | 'LIST';
        /**
         * Date list value
         * @description Date list value for a custom field
         */
        DateListValue: {
            data?: string[] | null;
            /**
             * @description The type of the custom field data.
             * @enum {string}
             */
            data_type: 'DATE';
        } & (components['schemas']['CustomField.ValueWrapper.MultipleValueWrapper'] &
            WithRequired<components['schemas']['CustomField.ValueWrapper'], 'data_type'>);
        /**
         * Date value
         * @description Date value for a custom field
         */
        DateValue: {
            /**
             * Format: date
             * @description The data of the custom field.
             */
            data?: string | null;
            /**
             * @description The type of the custom field data.
             * @enum {string}
             */
            data_type: 'DATE';
        } & (components['schemas']['CustomField.ValueWrapper.SingleValueWrapper'] &
            WithRequired<components['schemas']['CustomField.ValueWrapper'], 'data_type'>);
        /**
         * Decimal list value
         * @description Decimal list value for a custom field
         */
        DecimalListValue: {
            data?: number[] | null;
            /**
             * @description The type of the custom field data.
             * @enum {string}
             */
            data_type: 'DECIMAL';
        } & (components['schemas']['CustomField.ValueWrapper.MultipleValueWrapper'] &
            WithRequired<components['schemas']['CustomField.ValueWrapper'], 'data_type'>);
        /**
         * Decimal value
         * @description Decimal value for a custom field
         */
        DecimalValue: {
            /** @description The data of the custom field. */
            data?: number | null;
            /**
             * @description The type of the custom field data.
             * @enum {string}
             */
            data_type: 'DECIMAL';
        } & (components['schemas']['CustomField.ValueWrapper.SingleValueWrapper'] &
            WithRequired<components['schemas']['CustomField.ValueWrapper'], 'data_type'>);
        /** @description The department associated with the expense. */
        Department: {
            /** @description The unique identifier for the department. */
            id: string;
            /** @description The name of the department. */
            name: string;
        };
        /**
         * Enum list value
         * @description Enum list value for a custom field
         */
        EnumListValue: {
            data?: string[] | null;
            /**
             * @description The type of the custom field data.
             * @enum {string}
             */
            data_type: 'ENUM';
        } & (components['schemas']['CustomField.ValueWrapper.MultipleValueWrapper'] &
            WithRequired<components['schemas']['CustomField.ValueWrapper'], 'data_type'>);
        /**
         * Enum value
         * @description Enum value for a custom field
         */
        EnumValue: {
            /**
             * Format: enum
             * @description The data of the custom field.
             */
            data?: string | null;
            /**
             * @description The type of the custom field data.
             * @enum {string}
             */
            data_type: 'ENUM';
        } & (components['schemas']['CustomField.ValueWrapper.SingleValueWrapper'] &
            WithRequired<components['schemas']['CustomField.ValueWrapper'], 'data_type'>);
        /** @description The expense object that has expandable fields, e.g., `location`, `department`, `merchant`, `receipts.download_uris`, `user`, `budget`, `payment`, `spending_entity`, and `policy`. */
        ExpandableExpense: {
            address?: components['schemas']['Location'] | null;
            /**
             * Format: date-time
             * @description The time the expense is approved.
             */
            approved_at?: string | null;
            billing_amount?: (components['schemas']['Money'] & unknown) | null;
            /** @description ID of the legal entity responsible for billing the expense. */
            billing_entity_id?: string | null;
            /** @description The booking ID associated with the expense if it is a trip expense. */
            booking_id?: string | null;
            budget?: components['schemas']['Budget'] | null;
            budget_amount?: (components['schemas']['Money'] & unknown) | null;
            budget_id?: string | null;
            category?: components['schemas']['Category'] | null;
            /**
             * Format: date-time
             * @description The time payment will be completed/is completed.
             */
            completion_date?: string | null;
            /** @description A list of custom field values associated with the expense. */
            custom_fields?: components['schemas']['CustomField'][] | null;
            /** @description URL to view the expense in the Brex dashboard. */
            dashboard_url: string;
            department?: components['schemas']['Department'] | null;
            department_id?: string | null;
            /** @description The expense line items. Limited to 100 items. */
            expense_line_items?: components['schemas']['ExpandableExpense'][] | null;
            expense_type?: components['schemas']['ExpenseType'] | null;
            /**
             * Format: date-time
             * @description Timestamp when the expense was exported to the accounting system.
             */
            exported_at?: string | null;
            /** @description Unique ID associated with the expense. */
            id: string;
            /** @description ID of the billing entity in accounting. */
            integration_billing_entity_id?: string | null;
            /** @description ID of the spending entity in accounting. */
            integration_spending_entity_id?: string | null;
            location?: (components['schemas']['CustomerLocation'] & unknown) | null;
            location_id?: string | null;
            /** @description The memo of the expense. */
            memo?: string | null;
            merchant?: components['schemas']['Merchant'] | null;
            merchant_id?: string | null;
            original_amount?: (components['schemas']['Money'] & unknown) | null;
            payment?: components['schemas']['Payment'] | null;
            /** Format: date-time */
            payment_posted_at?: string | null;
            payment_status?: components['schemas']['ExpensePaymentStatus'] | null;
            policy?: (components['schemas']['Policy'] & unknown) | null;
            purchased_amount?: (components['schemas']['Money'] & unknown) | null;
            /**
             * Format: date-time
             * @description The time the purchase was made.
             */
            purchased_at?: string | null;
            /** @description A list of receipts associated with the expense. */
            receipts?: components['schemas']['Receipt'][] | null;
            repayment?: (components['schemas']['Repayment'] & unknown) | null;
            review?: (components['schemas']['Review'] & unknown) | null;
            spending_entity?: (components['schemas']['LegalEntity'] & unknown) | null;
            /** @description The spending entity ID associated with the expense. */
            spending_entity_id?: string | null;
            status?: components['schemas']['ExpenseStatus'] | null;
            /**
             * Format: date-time
             * @description The time the expense is submitted,
             */
            submitted_at?: string | null;
            /** @description The trip ID associated with the expense if it is a trip expense. */
            trip_id?: string | null;
            /**
             * Format: date-time
             * @description The last time the expense was updated.
             */
            updated_at: string;
            usd_equivalent_amount?: (components['schemas']['Money'] & unknown) | null;
            user?: components['schemas']['User'] | null;
            user_id?: string | null;
        };
        Expense: {
            billing_amount?: (components['schemas']['Money'] & unknown) | null;
            budget_id?: string | null;
            category?: components['schemas']['Category'] | null;
            department_id?: string | null;
            /** @description Unique ID associated with the expense. */
            id: string;
            location_id?: string | null;
            /** @description The memo of the expense. */
            memo?: string | null;
            merchant_id?: string | null;
            original_amount?: (components['schemas']['Money'] & unknown) | null;
            payment_status?: components['schemas']['ExpensePaymentStatus'] | null;
            /**
             * Format: date-time
             * @description The time the purchase was made.
             */
            purchased_at?: string | null;
            status?: components['schemas']['ExpenseStatus'] | null;
            /**
             * Format: date-time
             * @description The last time the expense was updated.
             */
            updated_at: string;
        };
        /** @enum {string} */
        ExpensePaymentStatus:
            | 'NOT_STARTED'
            | 'PROCESSING'
            | 'CANCELED'
            | 'DECLINED'
            | 'CLEARED'
            | 'REFUNDING'
            | 'REFUNDED'
            | 'CASH_ADVANCE'
            | 'CREDITED'
            | 'AWAITING_PAYMENT'
            | 'SCHEDULED';
        /** @enum {string} */
        ExpenseStatus:
            | 'DRAFT'
            | 'SUBMITTED'
            | 'APPROVED'
            | 'OUT_OF_POLICY'
            | 'VOID'
            | 'CANCELED'
            | 'SPLIT'
            | 'SETTLED';
        /** @enum {string} */
        ExpenseType: 'CARD' | 'BILLPAY' | 'REIMBURSEMENT' | 'CLAWBACK' | 'UNSET';
        /**
         * Legal Entity
         * @description A Brex legal entity.
         */
        LegalEntity: {
            billing_address: components['schemas']['Address'] & unknown;
            /**
             * Format: date-time
             * @description Timestamp, in UTC, when this legal entity was created.
             */
            created_at: string;
            /** @description The display name of this legal entity. */
            display_name: string;
            /** @description The ID of this legal entity. */
            id: string;
            /** @description Whether this is the default entity of the account. */
            is_default?: boolean;
            status: components['schemas']['LegalEntityStatus'] & unknown;
        };
        /**
         * @description The possible statuses for an entity's verification in Brex.
         * @enum {string}
         */
        LegalEntityStatus: 'UNSUBMITTED' | 'UNVERIFIED' | 'IN_PROGRESS' | 'VERIFIED' | 'REJECTED';
        /** @description Location */
        Location: {
            /** @description City, district, suburb, town, or village. */
            city?: string | null;
            coordinates?: components['schemas']['Location.LatLong'] | null;
            /** @description Two-letter country code (ISO 3166-1 alpha-2). */
            country?: string | null;
            /** @description Address line 1, no PO Box. */
            line1?: string | null;
            /** @description Address line 2 (e.g., apartment, suite, unit, or building). */
            line2?: string | null;
            /** @description ZIP or postal code. */
            postal_code?: string | null;
            /** @description For US-addressed the 2-letter State abbreviation. For international-addresses the county, providence, or region. */
            state?: string | null;
            /** @description Timezone. */
            timezone?: string | null;
        };
        /** @description Latitude and longitude */
        'Location.LatLong': {
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
        };
        Merchant: {
            /** @description Merchant's country, in ISO 3166-1 alpha-3 format. */
            country: string;
            /** @description A four-digit number listed in ISO 18245 for retail financial services, e.g. 4121 for Taxicabs and Rideshares. Please refer to https://en.wikipedia.org/wiki/Merchant_category_code for more details. */
            mcc: string;
            /** @description Merchant descriptor, it can be the merchant name. */
            raw_descriptor: string;
        };
        /**
         * @description Money fields can be signed or unsigned. Fields are signed (an unsigned value will be interpreted as positive). The amount of money will be represented in the smallest denomination
         *     of the currency indicated. For example, USD 7.00 will be represented in cents with an amount of 700.
         */
        Money: {
            /**
             * Format: int64
             * @description The amount of money, in the smallest denomination of the currency indicated by currency. For example, when currency is USD, amount is in cents.
             * @example 700
             */
            amount: number;
            /**
             * @description The type of currency, in ISO 4217 format.
             * @default USD
             * @example USD
             */
            currency: string | null;
        };
        /**
         * Money list value
         * @description Money list value for a custom field
         */
        MoneyListValue: {
            data?: components['schemas']['Money'][] | null;
            /**
             * @description The type of the custom field data.
             * @enum {string}
             */
            data_type: 'MONEY';
        } & (components['schemas']['CustomField.ValueWrapper.MultipleValueWrapper'] &
            WithRequired<components['schemas']['CustomField.ValueWrapper'], 'data_type'>);
        /**
         * Money value
         * @description Money value for a custom field
         */
        MoneyValue: {
            data?: (components['schemas']['Money'] & unknown) | null;
            /**
             * @description The type of the custom field data.
             * @enum {string}
             */
            data_type: 'MONEY';
        } & (components['schemas']['CustomField.ValueWrapper.SingleValueWrapper'] &
            WithRequired<components['schemas']['CustomField.ValueWrapper'], 'data_type'>);
        /** @description Option string fields have a label and a identifier. */
        OptionString: {
            /** @description The identifier when custom field data is of type option string. */
            option_id?: string | null;
            /** @description The label when custom field data is of type option string. */
            option_label?: string | null;
        };
        /**
         * Option string list value
         * @description Option string list value for a custom field
         */
        OptionStringListValue: {
            data?: components['schemas']['OptionString'][] | null;
            /**
             * @description The type of the custom field data.
             * @enum {string}
             */
            data_type: 'OPTION_STRING';
        } & (components['schemas']['CustomField.ValueWrapper.MultipleValueWrapper'] &
            WithRequired<components['schemas']['CustomField.ValueWrapper'], 'data_type'>);
        /**
         * Option string value
         * @description Option string value for a custom field
         */
        OptionStringValue: {
            data?: (components['schemas']['OptionString'] & unknown) | null;
            /**
             * @description The type of the custom field data.
             * @enum {string}
             */
            data_type: 'OPTION_STRING';
        } & (components['schemas']['CustomField.ValueWrapper.SingleValueWrapper'] &
            WithRequired<components['schemas']['CustomField.ValueWrapper'], 'data_type'>);
        Page_ExpandableExpense_: {
            items: components['schemas']['ExpandableExpense'][];
            next_cursor?: string | null;
        };
        /** @description The payment associated with the expense. */
        Payment: {
            /** @description Unique ID for the payment. */
            id: string;
            paymentInstrument: Omit<components['schemas']['PaymentInstrument'], 'type'> & unknown;
            statusReason: components['schemas']['PaymentStatusReason'];
        };
        PaymentInstrument: components['schemas']['CardPaymentInstrument'];
        /** @enum {string} */
        PaymentInstrumentType: 'CARD';
        /**
         * @description The reason for the payment's status.
         * @enum {string}
         */
        PaymentStatusReason:
            | 'OTHER'
            | 'APPROVED'
            | 'EXCEEDED_BUDGET_LIMIT'
            | 'BUDGET_EXPIRED'
            | 'NO_BUDGET'
            | 'BUDGET_NOT_YET_STARTED'
            | 'BUDGET_CATEGORY_RESTRICTION'
            | 'BUDGET_MERCHANT_RESTRICTION'
            | 'SUSPECTED_FRAUD'
            | 'EXCEEDED_GLOBAL_LIMIT'
            | 'EXCEEDED_USER_LIMIT'
            | 'EXCEEDED_CARD_LIMIT'
            | 'INVALID_EXPIRATION_DATE'
            | 'CARD_NOT_ACTIVE'
            | 'INVALID_CARD_CREDENTIALS'
            | 'INVALID_BILLING_ADDRESS'
            | 'CARD_SUSPENDED'
            | 'CARD_TERMINATED'
            | 'CARD_EXPIRED'
            | 'MCC_BLOCKED'
            | 'USER_SUSPENDED'
            | 'INVALID_PIN'
            | 'INVALID_CVV'
            | 'EXCEEDED_PIN_ATTEMPTS'
            | 'INSIDE_SANCTIONED_COUNTRY'
            | 'SOFT_EXPIRATION'
            | 'TRANSFERRED_CARD_NEW_MERCHANT'
            | 'EXCEEDED_ANCESTOR_BUDGET_LIMIT'
            | 'EXCEEDED_BUDGET_TRANSACTION_LIMIT'
            | 'TOS_BLOCKED'
            | 'COMPLIANCE_BLOCKED';
        /** @description The policy associated with the expense. */
        Policy: {
            /** @description The unique identifier for the policy. */
            id: string;
            /** @description The display name of the policy. */
            name: string;
        };
        /** @description The receipt associated with the expense. */
        Receipt: {
            /** @description [Presigned S3 link](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html)(s) to download file(s) of the receipt. Link(s) expire in 15 minutes. */
            download_uris?: string[] | null;
            /** @description The unique identifier for the receipt. */
            id: string;
        };
        /** @description The parameter for creating a receipt match. */
        ReceiptMatchRequest: {
            /** @description The name of the receipt (with the file extension). It will be used in the matching result email. */
            receipt_name: string;
        };
        /** @description The parameter for creating a receipt upload. */
        ReceiptUploadRequest: {
            /** @description The name of the receipt (with the file extension). */
            receipt_name: string;
        };
        Repayment: {
            repayment_initiated_by?: components['schemas']['User'] | null;
            /** Format: date-time */
            repayment_initiation_date?: string | null;
        };
        Review: {
            /** @description Information for each approval step of the expense */
            approval_steps: components['schemas']['ApprovalStepDetails'][] | null;
            /** @description Compliance status of the expense */
            compliance_status: string | null;
        };
        /**
         * String list value
         * @description String list value for a custom field
         */
        StringListValue: {
            data?: string[] | null;
            /**
             * @description The type of the custom field data.
             * @enum {string}
             */
            data_type: 'STRING';
        } & (components['schemas']['CustomField.ValueWrapper.MultipleValueWrapper'] &
            WithRequired<components['schemas']['CustomField.ValueWrapper'], 'data_type'>);
        /**
         * String value
         * @description String value for a custom field
         */
        StringValue: {
            /** @description The data of the custom field. */
            data?: string | null;
            /**
             * @description The type of the custom field data.
             * @enum {string}
             */
            data_type: 'STRING';
        } & (components['schemas']['CustomField.ValueWrapper.SingleValueWrapper'] &
            WithRequired<components['schemas']['CustomField.ValueWrapper'], 'data_type'>);
        /**
         * Timestamp list value
         * @description Timestamp list value for a custom field
         */
        TimestampListValue: {
            data?: string[] | null;
            /**
             * @description The type of the custom field data.
             * @enum {string}
             */
            data_type: 'TIMESTAMP';
        } & (components['schemas']['CustomField.ValueWrapper.MultipleValueWrapper'] &
            WithRequired<components['schemas']['CustomField.ValueWrapper'], 'data_type'>);
        /**
         * Timestamp value
         * @description Timestamp value for a custom field
         */
        TimestampValue: {
            /**
             * Format: date-time
             * @description The data of the custom field.
             */
            data?: string | null;
            /**
             * @description The type of the custom field data.
             * @enum {string}
             */
            data_type: 'TIMESTAMP';
        } & (components['schemas']['CustomField.ValueWrapper.SingleValueWrapper'] &
            WithRequired<components['schemas']['CustomField.ValueWrapper'], 'data_type'>);
        /** @description The parameter for updating an expense. */
        UpdateExpenseRequest: {
            /** @description Expense memo. */
            memo?: string | null;
        };
        User: {
            department_id?: string | null;
            /** @description First name of the User. */
            first_name: string;
            /** @description Unique ID for the User. */
            id: string;
            /** @description Last name of the User. */
            last_name: string;
            location_id?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listExpenses: {
        parameters: {
            query?: {
                'budget_id[]'?: string[] | null;
                /** @description The cursor to use for pagination. This is the `next_cursor` value returned from the previous response. */
                cursor?: string | null;
                /**
                 * @description Get additional details for the expense, e.g. merchant mcc code, by passing in `expand[]=merchant`. Query parameters include `location`, `department`, `merchant`, `receipts.download_uris`, `user`, `budget`, `payment`, `spending_entity` and `policy`.
                 * @example ?expand[]=merchant&expand[]=location
                 */
                'expand[]'?: string[] | null;
                'expense_type[]'?: components['schemas']['ExpenseType'][] | null;
                /** @description Controls the maximum number of expenses returned in the response, can't be greater than 100 */
                limit?: number | null;
                /** @description Load custom fields for the expenses. */
                load_custom_fields?: boolean | null;
                /** @description Get itemized expenses belong to provided parent expenses ID(s). */
                'parent_expense_id[]'?: string[] | null;
                /**
                 * @description Shows only expenses with a `payment_posted_at` on or before this date-time. This parameter is the date-time notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6), e.g. 2022-11-12T23:59:59.999
                 * @example 2023-01-10T23:59:59.999
                 */
                payment_posted_at_end?: string | null;
                /**
                 * @description Shows only expenses with a `payment_posted_at` on or after this date-time. This parameter is the date-time notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6), e.g. 2022-11-12T23:59:59.999
                 * @example 2023-01-01T23:59:59.999
                 */
                payment_posted_at_start?: string | null;
                'payment_status[]'?: components['schemas']['ExpensePaymentStatus'][] | null;
                /**
                 * @description Shows only expenses with a `purchased_at` on or before this date-time. This parameter is the date-time notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6), e.g. 2022-11-12T23:59:59.999
                 * @example 2023-01-10T23:59:59.999
                 */
                purchased_at_end?: string | null;
                /**
                 * @description Shows only expenses with a `purchased_at` on or after this date-time. This parameter is the date-time notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6), e.g. 2022-11-12T23:59:59.999
                 * @example 2023-01-01T23:59:59.999
                 */
                purchased_at_start?: string | null;
                'spending_entity_id[]'?: string[] | null;
                'status[]'?: components['schemas']['ExpenseStatus'][] | null;
                /**
                 * @description Shows only expenses with a `updated_at` on or before this date-time. This parameter is the date-time notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6), e.g. 2022-11-12T23:59:59.999
                 * @example 2023-01-10T23:59:59.999
                 */
                updated_at_end?: string | null;
                /**
                 * @description Shows only expenses with a `updated_at` on or after this date-time. This parameter is the date-time notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6), e.g. 2022-11-12T23:59:59.999
                 * @example 2023-01-01T23:59:59.999
                 */
                updated_at_start?: string | null;
                /** @description Get expenses belong to provided user(s). */
                'user_id[]'?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List expenses response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Page_ExpandableExpense_'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getExpense: {
        parameters: {
            query?: {
                /**
                 * @description Get additional details for the expense, e.g. merchant mcc code, by passing in `expand[]=merchant`. Query parameters include `location`, `department`, `merchant`, `receipts.download_uris`, `user`, `budget`, `payment`, `spending_entity` and `policy`.
                 * @example ?expand[]=merchant&expand[]=location
                 */
                'expand[]'?: string[] | null;
                /** @description Load custom fields for the expense. */
                load_custom_fields?: boolean | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get an expense response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ExpandableExpense'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listExpenses_1: {
        parameters: {
            query?: {
                'budget_id[]'?: string[] | null;
                /** @description The cursor to use for pagination. This is the `next_cursor` value returned from the previous response. */
                cursor?: string | null;
                /**
                 * @description Get additional details for the expense, e.g. merchant mcc code, by passing in `expand[]=merchant`. Query parameters include `location`, `department`, `merchant`, `receipts.download_uris`, `user`, `budget`, `payment`, `spending_entity` and `policy`.
                 * @example ?expand[]=merchant&expand[]=location
                 */
                'expand[]'?: string[] | null;
                /** @description Controls the maximum number of expenses returned in the response, can't be greater than 100 */
                limit?: number | null;
                /** @description Load custom fields for the expenses. */
                load_custom_fields?: boolean | null;
                /** @description Get itemized expenses belong to provided parent expenses ID(s). */
                'parent_expense_id[]'?: string[] | null;
                /**
                 * @description Shows only expenses with a `payment_posted_at` on or before this date-time. This parameter is the date-time notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6), e.g. 2022-11-12T23:59:59.999
                 * @example 2023-01-10T23:59:59.999
                 */
                payment_posted_at_end?: string | null;
                /**
                 * @description Shows only expenses with a `payment_posted_at` on or after this date-time. This parameter is the date-time notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6), e.g. 2022-11-12T23:59:59.999
                 * @example 2023-01-01T23:59:59.999
                 */
                payment_posted_at_start?: string | null;
                'payment_status[]'?: components['schemas']['ExpensePaymentStatus'][] | null;
                /**
                 * @description Shows only expenses with a `purchased_at` on or before this date-time. This parameter is the date-time notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6), e.g. 2022-11-12T23:59:59.999
                 * @example 2023-01-10T23:59:59.999
                 */
                purchased_at_end?: string | null;
                /**
                 * @description Shows only expenses with a `purchased_at` on or after this date-time. This parameter is the date-time notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6), e.g. 2022-11-12T23:59:59.999
                 * @example 2023-01-01T23:59:59.999
                 */
                purchased_at_start?: string | null;
                'spending_entity_id[]'?: string[] | null;
                'status[]'?: components['schemas']['ExpenseStatus'][] | null;
                /**
                 * @description Shows only expenses with a `updated_at` on or before this date-time. This parameter is the date-time notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6), e.g. 2022-11-12T23:59:59.999
                 * @example 2023-01-10T23:59:59.999
                 */
                updated_at_end?: string | null;
                /**
                 * @description Shows only expenses with a `updated_at` on or after this date-time. This parameter is the date-time notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6), e.g. 2022-11-12T23:59:59.999
                 * @example 2023-01-01T23:59:59.999
                 */
                updated_at_start?: string | null;
                /** @description Get expenses belong to provided user(s). */
                'user_id[]'?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List expenses response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Page_ExpandableExpense_'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCardExpense: {
        parameters: {
            query?: {
                /**
                 * @description Get additional details for the expense, e.g. merchant mcc code, by passing in `expand[]=merchant`. Query parameters include `location`, `department`, `merchant`, `receipts.download_uris`, `user`, `budget`, `payment`, `spending_entity` and `policy`.
                 * @example ?expand[]=merchant&expand[]=location
                 */
                'expand[]'?: string[] | null;
                /** @description Load custom fields for the expense. */
                load_custom_fields?: boolean | null;
            };
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get an expense response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ExpandableExpense'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['UpdateExpenseRequest'];
            };
        };
        responses: {
            /** @description Update an expense response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Expense'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    receiptUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['ReceiptUploadRequest'];
            };
        };
        responses: {
            /** @description Upload a new receipt response. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['CreateAsyncFileUploadResponse'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    receiptMatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['ReceiptMatchRequest'];
            };
        };
        responses: {
            /** @description Create a new receipt match response. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['CreateAsyncFileUploadResponse'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
