// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import type { BrexCore } from '../core/client';
import type { RequestOptions } from '../core/options';
import type { PagePromise } from '../core/pagination';
import type { paths } from './types.gen';

export class BudgetPrograms {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Get Budget Program
     * `GET /v1/budget_programs/{id}` — requires OAuth scope: `budgets.readonly`, `budgets`
     */
    get(
        id: paths['/v1/budget_programs/{id}']['get']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<
        paths['/v1/budget_programs/{id}']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v1/budget_programs/{id}']['get']['responses']['200']['content']['application/json']
        >('GET', `/v1/budget_programs/${encodeURIComponent(id)}`, { options });
    }

    /**
     * List Budget Programs
     * `GET /v1/budget_programs` — requires OAuth scope: `budgets.readonly`, `budgets`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    list(
        query?: paths['/v1/budget_programs']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<
        paths['/v1/budget_programs']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.list<
            paths['/v1/budget_programs']['get']['responses']['200']['content']['application/json']
        >('/v1/budget_programs', { query, options });
    }
}

export class Budgets {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Archive a Budget
     * `POST /v2/budgets/{id}/archive` — requires OAuth scope: `budgets`
     */
    archive(
        id: paths['/v2/budgets/{id}/archive']['post']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<void> {
        return this._core.request<void>('POST', `/v2/budgets/${encodeURIComponent(id)}/archive`, {
            options,
        });
    }

    /**
     * Create Budget
     * `POST /v2/budgets` — requires OAuth scope: `budgets`
     * Sends an `Idempotency-Key` header: `options.idempotencyKey`, or an auto-generated UUID.
     */
    create(
        body: NonNullable<
            paths['/v2/budgets']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<paths['/v2/budgets']['post']['responses']['200']['content']['application/json']> {
        return this._core.request<
            paths['/v2/budgets']['post']['responses']['200']['content']['application/json']
        >('POST', '/v2/budgets', { body, idempotency: 'required', options });
    }

    /**
     * Get Budget
     * `GET /v2/budgets/{id}` — requires OAuth scope: `budgets.readonly`, `budgets`
     */
    get(
        id: paths['/v2/budgets/{id}']['get']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<
        paths['/v2/budgets/{id}']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v2/budgets/{id}']['get']['responses']['200']['content']['application/json']
        >('GET', `/v2/budgets/${encodeURIComponent(id)}`, { options });
    }

    /**
     * List Budgets
     * `GET /v2/budgets` — requires OAuth scope: `budgets.readonly`, `budgets`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    list(
        query?: paths['/v2/budgets']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<paths['/v2/budgets']['get']['responses']['200']['content']['application/json']> {
        return this._core.list<
            paths['/v2/budgets']['get']['responses']['200']['content']['application/json']
        >('/v2/budgets', { query, options });
    }

    /**
     * Update Budget
     * `PUT /v2/budgets/{id}` — requires OAuth scope: `budgets`
     * Sends an `Idempotency-Key` header: `options.idempotencyKey`, or an auto-generated UUID.
     */
    update(
        id: paths['/v2/budgets/{id}']['put']['parameters']['path']['id'],
        body: NonNullable<
            paths['/v2/budgets/{id}']['put']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<
        paths['/v2/budgets/{id}']['put']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v2/budgets/{id}']['put']['responses']['200']['content']['application/json']
        >('PUT', `/v2/budgets/${encodeURIComponent(id)}`, {
            body,
            idempotency: 'required',
            options,
        });
    }
}

export class BudgetsV1 {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Archive a Spend Limit
     * `POST /v1/budgets/{id}/archive` — requires OAuth scope: `budgets`
     */
    archive(
        id: paths['/v1/budgets/{id}/archive']['post']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<void> {
        return this._core.request<void>('POST', `/v1/budgets/${encodeURIComponent(id)}/archive`, {
            options,
        });
    }

    /**
     * Create Spend Limit
     * `POST /v1/budgets` — requires OAuth scope: `budgets`
     * Sends an `Idempotency-Key` header: `options.idempotencyKey`, or an auto-generated UUID.
     */
    create(
        body: NonNullable<
            paths['/v1/budgets']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<paths['/v1/budgets']['post']['responses']['200']['content']['application/json']> {
        return this._core.request<
            paths['/v1/budgets']['post']['responses']['200']['content']['application/json']
        >('POST', '/v1/budgets', { body, idempotency: 'required', options });
    }

    /**
     * Get Spend Limit
     * `GET /v1/budgets/{id}` — requires OAuth scope: `budgets.readonly`, `budgets`
     */
    get(
        id: paths['/v1/budgets/{id}']['get']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<
        paths['/v1/budgets/{id}']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v1/budgets/{id}']['get']['responses']['200']['content']['application/json']
        >('GET', `/v1/budgets/${encodeURIComponent(id)}`, { options });
    }

    /**
     * List Spend Limits
     * `GET /v1/budgets` — requires OAuth scope: `budgets.readonly`, `budgets`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    list(
        query?: paths['/v1/budgets']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<paths['/v1/budgets']['get']['responses']['200']['content']['application/json']> {
        return this._core.list<
            paths['/v1/budgets']['get']['responses']['200']['content']['application/json']
        >('/v1/budgets', { query, options });
    }

    /**
     * Update Spend Limit
     * `PUT /v1/budgets/{id}` — requires OAuth scope: `budgets`
     * Sends an `Idempotency-Key` header: `options.idempotencyKey`, or an auto-generated UUID.
     */
    update(
        id: paths['/v1/budgets/{id}']['put']['parameters']['path']['id'],
        body: NonNullable<
            paths['/v1/budgets/{id}']['put']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<
        paths['/v1/budgets/{id}']['put']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v1/budgets/{id}']['put']['responses']['200']['content']['application/json']
        >('PUT', `/v1/budgets/${encodeURIComponent(id)}`, {
            body,
            idempotency: 'required',
            options,
        });
    }
}

export class SpendLimits {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Archive a Spend Limit
     * `POST /v2/spend_limits/{id}/archive` — requires OAuth scope: `budgets`
     */
    archive(
        id: paths['/v2/spend_limits/{id}/archive']['post']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<void> {
        return this._core.request<void>(
            'POST',
            `/v2/spend_limits/${encodeURIComponent(id)}/archive`,
            { options },
        );
    }

    /**
     * Create Spend Limit
     * `POST /v2/spend_limits` — requires OAuth scope: `budgets`
     * Sends an `Idempotency-Key` header: `options.idempotencyKey`, or an auto-generated UUID.
     */
    create(
        body: NonNullable<
            paths['/v2/spend_limits']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<
        paths['/v2/spend_limits']['post']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v2/spend_limits']['post']['responses']['200']['content']['application/json']
        >('POST', '/v2/spend_limits', { body, idempotency: 'required', options });
    }

    /**
     * Get Spend Limit
     * `GET /v2/spend_limits/{id}` — requires OAuth scope: `budgets.readonly`, `budgets`
     */
    get(
        id: paths['/v2/spend_limits/{id}']['get']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<
        paths['/v2/spend_limits/{id}']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v2/spend_limits/{id}']['get']['responses']['200']['content']['application/json']
        >('GET', `/v2/spend_limits/${encodeURIComponent(id)}`, { options });
    }

    /**
     * List Spend Limits
     * `GET /v2/spend_limits` — requires OAuth scope: `budgets.readonly`, `budgets`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    list(
        query?: paths['/v2/spend_limits']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<
        paths['/v2/spend_limits']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.list<
            paths['/v2/spend_limits']['get']['responses']['200']['content']['application/json']
        >('/v2/spend_limits', { query, options });
    }

    /**
     * Update Spend Limit
     * `PUT /v2/spend_limits/{id}` — requires OAuth scope: `budgets`
     * Sends an `Idempotency-Key` header: `options.idempotencyKey`, or an auto-generated UUID.
     */
    update(
        id: paths['/v2/spend_limits/{id}']['put']['parameters']['path']['id'],
        body: NonNullable<
            paths['/v2/spend_limits/{id}']['put']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<
        paths['/v2/spend_limits/{id}']['put']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v2/spend_limits/{id}']['put']['responses']['200']['content']['application/json']
        >('PUT', `/v2/spend_limits/${encodeURIComponent(id)}`, {
            body,
            idempotency: 'required',
            options,
        });
    }
}

export class BrexBudgets {
    readonly budgetPrograms: BudgetPrograms;
    readonly budgets: Budgets;
    readonly budgetsV1: BudgetsV1;
    readonly spendLimits: SpendLimits;
    constructor(core: BrexCore) {
        this.budgetPrograms = new BudgetPrograms(core);
        this.budgets = new Budgets(core);
        this.budgetsV1 = new BudgetsV1(core);
        this.spendLimits = new SpendLimits(core);
    }
}
