// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import { BrexCore } from '../core/client';
import type { BrexOptions } from '../core/options';
import { BrexBudgets } from './client.gen';

export * from '../core';
export { BrexBudgets, BudgetPrograms, Budgets, BudgetsV1, SpendLimits } from './client.gen';
export type * from './schemas.gen';
export type { components as BudgetsComponents, paths as BudgetsPaths } from './types.gen';

/** Standalone client for the Brex Budgets API. */
export function createBudgetsClient(options: BrexOptions): BrexBudgets {
    return new BrexBudgets(new BrexCore(options));
}
