// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate
export interface paths {
  "/v1/budget_programs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Budget Programs
     * @description Lists Budget Programs belonging to this account
     */
    get: operations["listBudgetPrograms"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/budget_programs/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Budget Program
     * @description Retrieves a Budget Program by ID
     */
    get: operations["getBudgetProgramById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/budgets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Spend Limits
     * @description Lists Spend Limits belonging to this account
     */
    get: operations["listBudgets"];
    put?: never;
    /**
     * Create Spend Limit
     * @description Creates a Spend Limit
     */
    post: operations["createBudget"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/budgets/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Spend Limit
     * @description Retrieves a Spend Limit by ID
     */
    get: operations["getBudgetById"];
    /**
     * Update Spend Limit
     * @description Updates a Spend Limit
     */
    put: operations["updateBudget"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/budgets/{id}/archive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Archive a Spend Limit
     * @description Archives a Spend Limit, making it unusable for future expenses and removing it from the UI
     */
    post: operations["archiveBudget"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/budgets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Budgets
     * @description Retrieves a list of Budgets
     */
    get: operations["listSpendBudgets"];
    put?: never;
    /**
     * Create Budget
     * @description Creates a Budget
     */
    post: operations["createSpendBudget"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/budgets/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Budget
     * @description Retrieves a Budget by ID
     */
    get: operations["getSpendBudgetById"];
    /**
     * Update Budget
     * @description Updates a Budget
     */
    put: operations["updateSpendBudget"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/budgets/{id}/archive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Archive a Budget
     * @description Archives a Budget, making any Spend Limits beneath it unusable for future expenses and removing it from the UI
     */
    post: operations["archiveSpendBudget"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/spend_limits": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Spend Limits
     * @description Retrieves a list of Spend Limits
     */
    get: operations["listSpendLimits"];
    put?: never;
    /**
     * Create Spend Limit
     * @description Creates a Spend Limit
     */
    post: operations["createSpendLimit"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/spend_limits/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Spend Limit
     * @description Retrieves a Spend Limit by ID
     */
    get: operations["getSpendLimitById"];
    /**
     * Update Spend Limit
     * @description Updates a Spend Limit
     */
    put: operations["updateSpendLimit"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v2/spend_limits/{id}/archive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Archive a Spend Limit
     * @description Archives a Spend Limit, making it unusable for future expenses and removing it from the UI
     */
    post: operations["archiveSpendLimit"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AuthorizationSettings: {
      authorization_type: components["schemas"]["AuthorizationType"] & unknown;
      base_limit: components["schemas"]["Money"] & unknown;
      /**
       * Format: int32
       * @description The percentage of flexible buffer on the limit as a 0-100 integer.
       */
      limit_buffer_percentage?: number | null;
      limit_with_increases: components["schemas"]["Money"] & unknown;
      rollover_refresh_rate: components["schemas"]["RolloverRefreshRate"] & unknown;
    };
    /**
     * @description Whether authorizations will decline based on available balance.
     * @enum {string}
     */
    AuthorizationType: "HARD" | "SOFT";
    /**
     * @description Describes if the limit of the Spend Limit is visible to all members, or just controllers, bookkeepers, and owners (direct or ancestral).
     * @enum {string}
     */
    AuthorizationVisibility: "PUBLIC" | "PRIVATE";
    /**
     * @description Setting for how auto limit card creation works for members.
     * @enum {string}
     */
    AutoCreateLimitCardsSetting: "DISABLED" | "ALL_MEMBERS";
    /**
     * @description Setting for how auto transfer works for virtual cards.
     * @enum {string}
     */
    AutoTransferCardsSetting: "DISABLED" | "ENABLED";
    Budget: {
      /** @description The Brex account this Spend Limit belongs to. */
      account_id: string;
      /** @description Unique ID for the Spend Limit. */
      budget_id: string;
      budget_status: components["schemas"]["BudgetStatus"];
      budget_type: components["schemas"]["BudgetType"] & unknown;
      /** @description The ID of the user who originally created this Spend Limit. */
      creator_user_id?: string | null;
      current_period_balance?: components["schemas"]["BudgetPeriodBalance"] | null;
      /** @description Description of what the Spend Limit is used for. */
      description?: string | null;
      /**
       * Format: date
       * @description The UTC date when the Spend Limit should stop counting.
       */
      end_date?: string | null;
      limit?: components["schemas"]["Money"] | null;
      limit_type?: components["schemas"]["LimitType"] | null;
      limit_visibility: components["schemas"]["BudgetLimitVisibilityType"] & unknown;
      /** @description User IDs of the members of the Spend Limit. */
      member_user_ids: string[];
      /** @description Name for the Spend Limit. */
      name: string;
      /** @description User IDs of the owners of the Spend Limit. */
      owner_user_ids: string[];
      /** @description ID of parent Budget. */
      parent_budget_id?: string | null;
      period_type: components["schemas"]["PeriodType"];
      spend_type: components["schemas"]["SpendType"];
      /**
       * Format: date
       * @description The UTC date when the Spend Limit should start counting.
       */
      start_date?: string | null;
      templateId?: string | null;
    };
    /** @description Blueprint for provisioning Spend Limits for a Budget Program. */
    BudgetBlueprint: {
      /** @description Description of what the Spend Limit is used for. */
      description?: string | null;
      /**
       * Format: date
       * @description The UTC date when the Spend Limit should stop counting.
       */
      end_date?: string | null;
      id: string;
      limit?: components["schemas"]["Money"] | null;
      limit_type: components["schemas"]["LimitType"];
      limit_visibility: components["schemas"]["BudgetLimitVisibilityType"];
      /** @description Name for the Spend Limit. */
      name: string;
      /** @description User IDs of the owners of the Spend Limit. */
      owner_user_ids: string[];
      /** @description ID of parent Budget. */
      parent_budget_id: string;
      period_type: components["schemas"]["PeriodType"];
      spend_type: components["schemas"]["SpendType"];
      /**
       * Format: date
       * @description The UTC date when the Spend Limit should start counting.
       */
      start_date?: string | null;
    };
    /**
     * @description Determines if Spend Limit members are allowed to view the Spend Limit's limit.
     * @enum {string}
     */
    BudgetLimitVisibilityType: "SHARED" | "PRIVATE";
    /** @description Current Spend Limit period balance. */
    BudgetPeriodBalance: {
      balance?: components["schemas"]["Money"] | null;
      /** Format: date */
      end_date?: string | null;
      /** Format: date */
      start_date?: string | null;
    };
    /** @description Budget Program used to create Spend Limits for eligible users. */
    BudgetProgram: {
      budget_blueprints: components["schemas"]["BudgetBlueprint"][];
      budget_program_status: components["schemas"]["BudgetProgramStatus"];
      /** Format: date */
      created_at: string;
      creator_user_id?: string | null;
      description?: string | null;
      employee_filter?: components["schemas"]["EmployeeFilter"] | null;
      /** @description IDs for existing Spend Limits associated with this Budget Program. */
      existing_budget_ids?: string[] | null;
      id: string;
      name: string;
      /** Format: date */
      updated_at: string;
    };
    /** @enum {string} */
    BudgetProgramStatus:
      | "BUDGET_PROGRAM_STATUS_ACTIVE"
      | "BUDGET_PROGRAM_STATUS_INACTIVE"
      | "BUDGET_PROGRAM_STATUS_DELETED";
    /**
     * @description Status of the Spend Limit e.g. APPROVED.
     * @enum {string}
     */
    BudgetStatus: "APPROVED" | "EXPIRED" | "TERMINATED" | "DELETED";
    /**
     * @description Whether this is a Budget or a Spend Limit for post-bifurcation entities.
     * @enum {string}
     */
    BudgetType: "BUDGET" | "SPEND_LIMIT";
    CreateAuthorizationSettings: {
      authorization_type: components["schemas"]["AuthorizationType"] & unknown;
      base_limit: components["schemas"]["Money"] & unknown;
      /**
       * Format: int32
       * @description The percentage of flexible buffer on the limit as a 0-100 integer.
       */
      limit_buffer_percentage?: number | null;
      rollover_refresh_rate: components["schemas"]["RolloverRefreshRate"] & unknown;
    };
    /** @description Blueprint for provisioning Spend Limits for a Budget Program. */
    CreateBudgetBlueprintRequest: {
      /** @description Description of what the Spend Limit is used for. */
      description: string;
      /**
       * Format: date
       * @description The UTC date when the Spend Limit should stop counting.
       */
      end_date?: string | null;
      limit: components["schemas"]["Money"];
      limit_type: components["schemas"]["LimitType"];
      limit_visibility: components["schemas"]["BudgetLimitVisibilityType"];
      /** @description Name for the Spend Limit. */
      name: string;
      /** @description User IDs of the owners of the Spend Limit. */
      owner_user_ids?: string[] | null;
      /** @description ID of parent Budget. */
      parent_budget_id: string;
      period_type: components["schemas"]["PeriodType"];
      spend_type: components["schemas"]["SpendType"];
      /**
       * Format: date
       * @description The UTC date when the Spend Limit should start counting.
       */
      start_date?: string | null;
    };
    /** @description Budget Program used to create Spend Limits for eligible users. */
    CreateBudgetProgramRequest: {
      budget_blueprints: components["schemas"]["CreateBudgetBlueprintRequest"][];
      description?: string | null;
      employee_filter?: components["schemas"]["EmployeeFilter"] | null;
      /** @description IDs for existing Spend Limits associated with this Budget Program. */
      existing_budget_ids?: string[] | null;
      name: string;
    };
    CreateBudgetRequest: {
      /** @description Description of what the Spend Limit is used for. */
      description: string;
      /**
       * Format: date
       * @description The UTC date when the Spend Limit should stop counting.
       */
      end_date?: string | null;
      entity_id?: string | null;
      limit: components["schemas"]["Money"];
      limit_type: components["schemas"]["LimitType"];
      limit_visibility: components["schemas"]["BudgetLimitVisibilityType"];
      /** @description User IDs of the members of the Spend Limit. */
      member_user_ids?: string[] | null;
      /** @description Name for the Spend Limit. */
      name: string;
      /** @description User IDs of the owners of the Spend Limit. */
      owner_user_ids?: string[] | null;
      /** @description ID of parent Budget. */
      parent_budget_id: string;
      period_type: components["schemas"]["PeriodType"];
      policy_id?: string | null;
      spend_type: components["schemas"]["SpendType"];
      /**
       * Format: date
       * @description The UTC date when the Spend Limit should start counting.
       */
      start_date?: string | null;
    };
    CreateSpendBudgetRequest: {
      amount: components["schemas"]["Money"];
      /** @description Description of what the Budget is used for. */
      description: string;
      /**
       * Format: date
       * @description The date when the Budget should stop counting.
       */
      end_date?: string | null;
      /** @deprecated */
      limit_type?: (components["schemas"]["LimitType_3"] & unknown) | null;
      /** @description Name for the Budget. */
      name: string;
      /** @description User IDs of the owners of the Budget. */
      owner_user_ids?: string[] | null;
      /** @description ID of parent Budget. */
      parent_budget_id: string;
      period_recurrence_type: components["schemas"]["PeriodRecurrenceType"] & unknown;
      /**
       * Format: date
       * @description The date when the Budget should start counting.
       */
      start_date?: string | null;
    };
    CreateSpendLimitRequest: {
      authorization_settings: components["schemas"]["CreateAuthorizationSettings"] & unknown;
      authorization_visibility: components["schemas"]["AuthorizationVisibility"] & unknown;
      auto_create_limit_cards_setting: components["schemas"]["AutoCreateLimitCardsSetting"] &
        unknown;
      auto_transfer_cards_setting: components["schemas"]["AutoTransferCardsSetting"] & unknown;
      /** @description The department ID to which Spend Limit expenses will be attributed. */
      department_id?: string | null;
      /** @description Description of what the Spend Limit is used for. */
      description?: string | null;
      /**
       * Format: date
       * @description The date when the Spend Limit should expire.
       */
      end_date?: string | null;
      /** @description The ID of the expense policy corresponding to this Spend Limit. */
      expense_policy_id: string;
      expense_visibility: components["schemas"]["ExpenseVisibility"] & unknown;
      /** @description The legal entity ID to which Spend Limit expenses will be attributed. If not set, expenses will be attributed to the spending user's entity. */
      legal_entity_id?: string | null;
      /** @description The ID of the policy for limit increase approval requests. Meant to replace limit_increase_request_policy_id. */
      limit_approval_policy_id?: string | null;
      /** @description The ID of the policy for limit increase requests for this Spend Limit. */
      limit_increase_request_policy_id?: string | null;
      limit_increase_setting: components["schemas"]["LimitIncreaseSetting"] & unknown;
      /** @description User IDs of the members of the Spend Limit. */
      member_user_ids?: string[] | null;
      /** @description Name for the Spend Limit. */
      name: string;
      /** @description User IDs of the owners of the Spend Limit. */
      owner_user_ids?: string[] | null;
      /** @description ID of parent Budget. */
      parent_budget_id?: string | null;
      period_recurrence_type: components["schemas"]["SpendLimitPeriodRecurrenceType"] & unknown;
      spend_type: components["schemas"]["SpendType"] & unknown;
      /**
       * Format: date
       * @description The date when the Spend Limit should start counting.
       */
      start_date?: string | null;
      transaction_limit?: (components["schemas"]["Money"] & unknown) | null;
    };
    /** @description A filter used to determine if a user adheres to a Budget Program. */
    EmployeeFilter: {
      employment_status?: components["schemas"]["EmploymentStatus"] | null;
      employment_type?: components["schemas"]["EmploymentType"] | null;
    };
    /**
     * @description A filter used to determine if a user adheres to a Budget Program.
     * @enum {string}
     */
    EmploymentStatus:
      | "EMPLOYMENT_STATUS_ACTIVE"
      | "EMPLOYMENT_STATUS_INACTIVE"
      | "EMPLOYMENT_STATUS_PENDING";
    /**
     * @description What kind of employment the employee has.
     * @enum {string}
     */
    EmploymentType:
      | "EMPLOYMENT_TYPE_FULL_TIME"
      | "EMPLOYMENT_TYPE_PART_TIME"
      | "EMPLOYMENT_TYPE_CONTRACTOR"
      | "EMPLOYMENT_TYPE_INTERN"
      | "EMPLOYMENT_TYPE_FREELANCE";
    /**
     * @description Whether or not expense related to this Spend Limit should be viewable to all members.
     * @enum {string}
     */
    ExpenseVisibility: "SHARED" | "PRIVATE";
    /**
     * @description Whether or not members can request limit increases.
     * @enum {string}
     */
    LimitIncreaseSetting: "ENABLED" | "DISABLED";
    /**
     * @description Whether the Spend Limit's limit blocks spend.
     * @enum {string}
     */
    LimitType: "HARD" | "SOFT";
    /**
     * @description Whether the Budget amount blocks spend. `HARD` is rejected; use `/v2/spend_limits` for hard-auth limits.
     * @enum {string}
     */
    LimitType_1: "HARD" | "SOFT";
    /**
     * @description Whether the Budget amount blocks spend. `HARD` is rejected; use `/v2/spend_limits` for hard-auth limits.
     * @enum {string}
     */
    LimitType_3: "HARD" | "SOFT";
    /**
     * @description Whether the Budget amount blocks spend. `HARD` is rejected; use `/v2/spend_limits` for hard-auth limits.
     * @enum {string}
     */
    LimitType_4: "HARD" | "SOFT";
    /** @enum {string} */
    MerchantCategory:
      | "ADVERTISING_MARKETING"
      | "GROCERY"
      | "TELEPHONY"
      | "OFFICE_SUPPLIES"
      | "PRIVATE_AIR_TRAVEL"
      | "CLOTHING"
      | "CAR_RENTAL"
      | "VEHICLE_EXPENSES"
      | "RESTAURANTS"
      | "GAMBLING"
      | "FLOWERS"
      | "ELECTRONICS"
      | "LEGAL_SERVICES"
      | "UTILITIES"
      | "FURNITURE"
      | "BARS_NIGHTLIFE"
      | "LAUNDRY"
      | "EVENT_EXPENSES"
      | "SHIPPING"
      | "OTHER_TRAVEL_EXPENSES"
      | "CHARITY"
      | "SOFTWARE"
      | "LODGING"
      | "FACILITIES_EXPENSES"
      | "SERVERS"
      | "CONFERENCES"
      | "FOOD_DELIVERY"
      | "RENT"
      | "AIRLINE_EXPENSES"
      | "OTHER_BUSINESS_EXPENSES"
      | "BANK_FINANCIAL_FEES"
      | "BOOKS_NEWSPAPERS"
      | "CONSULTANT_CONTRACTOR"
      | "CORPORATE_INSURANCE"
      | "DIGITAL_GOODS"
      | "LICENSES_TAXES"
      | "GAS_FUEL"
      | "GENERAL_MERCHANDISE"
      | "MEDICAL"
      | "MEMBERSHIPS_CLUBS"
      | "PARKING_EXPENSES"
      | "POLITICAL_DONATIONS"
      | "PUBLIC_TRANSPORTATION"
      | "RECURRING_SOFTWARE_SAAS"
      | "RIDESHARE_TAXI"
      | "TOLL_BRIDGE_FEES"
      | "TRAINING_EDUCATION"
      | "TRAVEL";
    MerchantCategoryControls: {
      allowed_merchant_categories?: components["schemas"]["MerchantCategory"][] | null;
      blocked_merchant_categories?: components["schemas"]["MerchantCategory"][] | null;
    };
    /**
     * @description Money fields can be signed or unsigned. Fields are signed (an unsigned value will be interpreted as positive). The amount of money will be represented in the smallest denomination
     *     of the currency indicated. For example, USD 7.00 will be represented in cents with an amount of 700.
     */
    Money: {
      /**
       * Format: int64
       * @description The amount of money, in the smallest denomination of the currency indicated by currency. For example, when currency is USD, amount is in cents.
       * @example 700
       */
      amount: number;
      /**
       * @description The type of currency, in ISO 4217 format.
       * @default USD
       * @example USD
       */
      currency: string | null;
    };
    Page_Budget_: {
      items: components["schemas"]["Budget"][];
      next_cursor?: string | null;
    };
    Page_BudgetProgram_: {
      items: components["schemas"]["BudgetProgram"][];
      next_cursor?: string | null;
    };
    Page_SpendBudget_: {
      items: components["schemas"]["SpendBudget"][];
      next_cursor?: string | null;
    };
    Page_SpendLimit_: {
      items: components["schemas"]["SpendLimit"][];
      next_cursor?: string | null;
    };
    /**
     * @description Period type of the Budget e.g. MONTHLY.
     * @enum {string}
     */
    PeriodRecurrenceType: "WEEKLY" | "MONTHLY" | "QUARTERLY" | "YEARLY" | "ONE_TIME";
    /**
     * @description Period type of the Spend Limit e.g. MONTHLY.
     * @enum {string}
     */
    PeriodType: "WEEKLY" | "MONTHLY" | "QUARTERLY" | "YEARLY" | "ONE_TIME";
    /**
     * @description The rollover refresh rate for this spend limit (the recurrence by which all rolled over unused funds within the cycle should no longer roll over to the next period).
     * @enum {string}
     */
    RolloverRefreshRate: "OFF" | "NEVER" | "PER_MONTH" | "PER_QUARTER" | "PER_YEAR";
    SpendBudget: {
      /** @description The Brex account this Budget belongs to. */
      account_id: string;
      amount?: components["schemas"]["Money"] | null;
      /** @description Unique ID for the Budget. */
      budget_id: string;
      /** @description Description of what the Budget is used for. */
      description?: string | null;
      /**
       * Format: date
       * @description The date when the Budget should stop counting.
       */
      end_date?: string | null;
      /** @deprecated */
      limit_type?: (components["schemas"]["LimitType_1"] & unknown) | null;
      /** @description Name for the Budget. */
      name: string;
      /** @description User IDs of the owners of the Budget. */
      owner_user_ids: string[];
      /** @description ID of parent Budget. */
      parent_budget_id?: string | null;
      period_recurrence_type: components["schemas"]["PeriodRecurrenceType"] & unknown;
      spend_budget_status: components["schemas"]["SpendBudgetStatus"] & unknown;
      /**
       * Format: date
       * @description The date when the Budget should start counting.
       */
      start_date?: string | null;
    };
    /**
     * @description Status of the Budget e.g. ACTIVE.
     * @enum {string}
     */
    SpendBudgetStatus: "ACTIVE" | "ARCHIVED" | "DELETED" | "EXPIRED";
    SpendLimit: {
      /** @description The Brex account this Spend Limit belongs to. */
      account_id: string;
      authorization_settings?: (components["schemas"]["AuthorizationSettings"] & unknown) | null;
      authorization_visibility: components["schemas"]["AuthorizationVisibility"] & unknown;
      auto_create_limit_cards_setting: components["schemas"]["AutoCreateLimitCardsSetting"] &
        unknown;
      auto_transfer_cards_setting: components["schemas"]["AutoTransferCardsSetting"] & unknown;
      current_period_balance?: components["schemas"]["SpendLimitPeriodBalance"] | null;
      /** @description The department ID to which Spend Limit expenses will be attributed. */
      department_id?: string | null;
      /** @description Description of what the Spend Limit is used for. */
      description?: string | null;
      /**
       * Format: date
       * @description The date when the Spend Limit should expire.
       */
      end_date?: string | null;
      /**
       * Format: date-time
       * @description The UTC time when the Spend Limit should expire.
       */
      end_time_utc?: string | null;
      /** @description The ID of the expense policy corresponding to this Spend Limit. */
      expense_policy_id: string;
      expense_visibility: components["schemas"]["ExpenseVisibility"] & unknown;
      /** @description Unique ID for the Spend Limit. */
      id: string;
      /** @description The legal entity ID to which Spend Limit expenses will be attributed. If not set, expenses will be attributed to the spending user's entity. */
      legal_entity_id?: string | null;
      /** @description The ID of the policy for limit increase approval requests. Meant to replace limit_increase_request_policy_id. */
      limit_approval_policy_id?: string | null;
      /** @description The ID of the policy for limit increase requests for this Spend Limit. */
      limit_increase_request_policy_id?: string | null;
      limit_increase_setting: components["schemas"]["LimitIncreaseSetting"] & unknown;
      /** @description User IDs of the members of the Spend Limit. */
      member_user_ids: string[];
      merchant_category_controls?:
        | (components["schemas"]["MerchantCategoryControls"] & unknown)
        | null;
      /** @description Name for the Spend Limit. */
      name: string;
      /** @description User IDs of the owners of the Spend Limit. */
      owner_user_ids: string[];
      /** @description ID of parent Budget. */
      parent_budget_id?: string | null;
      period_recurrence_type: components["schemas"]["SpendLimitPeriodRecurrenceType"] & unknown;
      spend_type: components["schemas"]["SpendType"] & unknown;
      /**
       * Format: date
       * @description The date when the Spend Limit should start counting.
       */
      start_date?: string | null;
      /**
       * Format: date-time
       * @description The UTC time when the Spend Limit should start counting.
       */
      start_time_utc?: string | null;
      status: components["schemas"]["SpendLimitStatus"] & unknown;
      transaction_limit?: (components["schemas"]["Money"] & unknown) | null;
    };
    SpendLimitPeriodBalance: {
      amount_spent?: components["schemas"]["Money"] | null;
      /** Format: date */
      end_date?: string | null;
      /** Format: date-time */
      end_time?: string | null;
      rollover_amount?: components["schemas"]["Money"] | null;
      /** Format: date */
      start_date?: string | null;
      /** Format: date-time */
      start_time?: string | null;
    };
    /**
     * @description Period type of the Spend Limit e.g. MONTHLY.
     * @enum {string}
     */
    SpendLimitPeriodRecurrenceType:
      | "PER_WEEK"
      | "PER_MONTH"
      | "PER_QUARTER"
      | "PER_YEAR"
      | "ONE_TIME";
    /**
     * @description Status of the Spend Limit e.g. ACTIVE.
     * @enum {string}
     */
    SpendLimitStatus: "ACTIVE" | "EXPIRED" | "ARCHIVED" | "DELETED";
    /**
     * @description Whether this Spend Limit only can be spent from by cards provisioned by this Spend Limit.
     * @enum {string}
     */
    SpendType: "BUDGET_PROVISIONED_CARDS_ONLY" | "NON_BUDGET_PROVISIONED_CARDS_ALLOWED";
    UpdateAuthorizationSettings: {
      authorization_type?: (components["schemas"]["AuthorizationType"] & unknown) | null;
      base_limit?: (components["schemas"]["Money"] & unknown) | null;
      /**
       * Format: int32
       * @description The percentage of flexible buffer on the limit as a 0-100 integer.
       */
      limit_buffer_percentage?: number | null;
      rollover_refresh_rate?: (components["schemas"]["RolloverRefreshRate"] & unknown) | null;
    };
    /** @description Blueprint for provisioning Spend Limits for a Budget Program. */
    UpdateBudgetBlueprintRequest: {
      /** @description Description of what the Spend Limit is used for. */
      description?: string | null;
      /**
       * Format: date
       * @description The UTC date when the Spend Limit should stop counting.
       */
      end_date?: string | null;
      /** @description ID of budget blueprint to update, omit if adding new budget blueprint to budget program. */
      id?: string | null;
      limit?: components["schemas"]["Money"] | null;
      limit_type?: components["schemas"]["LimitType"] | null;
      /** @description Name for the Spend Limit. */
      name?: string | null;
      /** @description User IDs of the owners of the Spend Limit. */
      owner_user_ids?: string[] | null;
      /** @description ID of parent Budget. */
      parent_budget_id?: string | null;
      period_type?: components["schemas"]["PeriodType"] | null;
      spend_type?: components["schemas"]["SpendType"] | null;
      /**
       * Format: date
       * @description The UTC date when the Spend Limit should start counting.
       */
      start_date?: string | null;
    };
    /** @description Budget Program used to create Spend Limits for eligible users. */
    UpdateBudgetProgramRequest: {
      /**
       * @description The Blueprints to update the budget program with. Blueprints without an ID are treated as new blueprints to be created.
       *     Blueprints that exist currently on the Budget Program, but are missing from the input, will be deleted.
       */
      budget_blueprints?: components["schemas"]["UpdateBudgetBlueprintRequest"][] | null;
      description?: string | null;
      employee_filter?: components["schemas"]["EmployeeFilter"] | null;
      /** @description IDs for existing Spend Limits associated with this Budget Program. */
      existing_budget_ids?: string[] | null;
      name?: string | null;
    };
    UpdateBudgetRequest: {
      /** @description Description of what the Spend Limit is used for. */
      description?: string | null;
      /**
       * Format: date
       * @description The UTC date when the Spend Limit should stop counting.
       */
      end_date?: string | null;
      limit?: components["schemas"]["Money"] | null;
      limit_type?: components["schemas"]["LimitType"] | null;
      limit_visibility?: components["schemas"]["BudgetLimitVisibilityType"] | null;
      /** @description User IDs of the members of the Spend Limit. */
      member_user_ids?: string[] | null;
      /** @description Name for the Spend Limit. */
      name?: string | null;
      /** @description User IDs of the owners of the Spend Limit. */
      owner_user_ids?: string[] | null;
      period_type?: components["schemas"]["PeriodType"] | null;
      spend_type?: components["schemas"]["SpendType"] | null;
      /**
       * Format: date
       * @description The UTC date when the Spend Limit should start counting.
       */
      start_date?: string | null;
    };
    UpdateSpendBudgetRequest: {
      amount?: (components["schemas"]["Money"] & unknown) | null;
      /** @description Description of what the Budget is used for. */
      description?: string | null;
      /**
       * Format: date
       * @description The date when the Budget should stop counting.
       */
      end_date?: string | null;
      /** @deprecated */
      limit_type?: (components["schemas"]["LimitType_4"] & unknown) | null;
      /** @description Name for the Budget. */
      name?: string | null;
      /** @description User IDs of the owners of the Budget. */
      owner_user_ids?: string[] | null;
      /** @description ID of parent Budget. */
      parent_budget_id?: string | null;
      period_recurrence_type?: (components["schemas"]["PeriodRecurrenceType"] & unknown) | null;
      /**
       * Format: date
       * @description The date when the Budget should start counting.
       */
      start_date?: string | null;
    };
    UpdateSpendLimitRequest: {
      authorization_settings?:
        | (components["schemas"]["UpdateAuthorizationSettings"] & unknown)
        | null;
      authorization_visibility?:
        | (components["schemas"]["AuthorizationVisibility"] & unknown)
        | null;
      auto_create_limit_cards_setting?:
        | (components["schemas"]["AutoCreateLimitCardsSetting"] & unknown)
        | null;
      auto_transfer_cards_setting?:
        | (components["schemas"]["AutoTransferCardsSetting"] & unknown)
        | null;
      /** @description The department ID to which Spend Limit expenses will be attributed. */
      department_id?: string | null;
      /** @description Description of what the Spend Limit is used for. */
      description?: string | null;
      /**
       * Format: date
       * @description The date when the Spend Limit should expire.
       */
      end_date?: string | null;
      /** @description The ID of the expense policy corresponding to this Spend Limit. */
      expense_policy_id?: string | null;
      expense_visibility?: (components["schemas"]["ExpenseVisibility"] & unknown) | null;
      /** @description The legal entity ID to which Spend Limit expenses will be attributed. If not set, expenses will be attributed to the spending user's entity. */
      legal_entity_id?: string | null;
      /** @description The ID of the policy for limit increase approval requests. Meant to replace limit_increase_request_policy_id. */
      limit_approval_policy_id?: string | null;
      /** @description The ID of the policy for limit increase requests for this Spend Limit. */
      limit_increase_request_policy_id?: string | null;
      limit_increase_setting?: (components["schemas"]["LimitIncreaseSetting"] & unknown) | null;
      /** @description User IDs of the members of the Spend Limit. */
      member_user_ids?: string[] | null;
      merchant_category_controls?:
        | (components["schemas"]["MerchantCategoryControls"] & unknown)
        | null;
      /** @description Name for the Spend Limit. */
      name?: string | null;
      /** @description User IDs of the owners of the Spend Limit. */
      owner_user_ids?: string[] | null;
      period_recurrence_type?:
        | (components["schemas"]["SpendLimitPeriodRecurrenceType"] & unknown)
        | null;
      /** @description Set the date when the Spend Limit should expire to null. */
      set_end_date_null?: boolean | null;
      /** @description Set the date when the Spend Limit should start counting to null. */
      set_start_date_null?: boolean | null;
      /** @description Set the transaction limit that this Spend Limit will enforce to null. */
      set_transaction_limit_null?: boolean | null;
      spend_type?: (components["schemas"]["SpendType"] & unknown) | null;
      /**
       * Format: date
       * @description The date when the Spend Limit should start counting.
       */
      start_date?: string | null;
      status?: (components["schemas"]["SpendLimitStatus"] & unknown) | null;
      transaction_limit?: (components["schemas"]["Money"] & unknown) | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listBudgetPrograms: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A page with a list of Budget Programs */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_BudgetProgram_"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getBudgetProgramById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Budget Program that was retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BudgetProgram"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listBudgets: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A page with a list of Spend Limits */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_Budget_"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createBudget: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBudgetRequest"];
      };
    };
    responses: {
      /** @description The Spend Limit that was created */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Budget"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getBudgetById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Spend Limit that was retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Budget"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateBudget: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateBudgetRequest"];
      };
    };
    responses: {
      /** @description The Spend Limit that was updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Budget"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  archiveBudget: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Spend Limit that was archived */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listSpendBudgets: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A page with a list of Budgets */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_SpendBudget_"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createSpendBudget: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSpendBudgetRequest"];
      };
    };
    responses: {
      /** @description The Budget that was created */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SpendBudget"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getSpendBudgetById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Budget that was retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SpendBudget"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateSpendBudget: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateSpendBudgetRequest"];
      };
    };
    responses: {
      /** @description The Budget that was updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SpendBudget"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  archiveSpendBudget: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Budget that was archived */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listSpendLimits: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number | null;
        "member_user_id[]"?: string[] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A page with a list of Spend Limits */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_SpendLimit_"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createSpendLimit: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSpendLimitRequest"];
      };
    };
    responses: {
      /** @description The Spend Limit that was created */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SpendLimit"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getSpendLimitById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Spend Limit that was retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SpendLimit"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateSpendLimit: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateSpendLimitRequest"];
      };
    };
    responses: {
      /** @description The Spend Limit that was updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SpendLimit"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  archiveSpendLimit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Spend Limit that was archived */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
