// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import type { BrexCore } from '../core/client';
import type { RequestOptions } from '../core/options';
import type { PagePromise } from '../core/pagination';
import type { paths } from './types.gen';

export class Referrals {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Create a new document upload
     *
     * The `uri` will be a presigned S3 URL allowing you to upload the referral doc securely. This URL can only be used for a `PUT` operation and expires 30 minutes after its creation. Once your upload is complete, we will use this to prefill the application.
     *
     * Refer to these [docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html) on how to upload to this presigned S3 URL. We highly recommend using one of AWS SDKs if they're available for your language to upload these files.
     *
     * `POST /v1/referrals/{id}/document_upload`
     */
    createDocument(
        id: paths['/v1/referrals/{id}/document_upload']['post']['parameters']['path']['id'],
        body: NonNullable<
            paths['/v1/referrals/{id}/document_upload']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<
        paths['/v1/referrals/{id}/document_upload']['post']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v1/referrals/{id}/document_upload']['post']['responses']['200']['content']['application/json']
        >('POST', `/v1/referrals/${encodeURIComponent(id)}/document_upload`, { body, options });
    }

    /**
     * Creates a referral
     *
     * This creates new referrals. The response will contain an identifier and a unique personalized link to an application flow. Many fields are optional and when they're provided they'll prefill the application flow for Brex.  You should handle and store these references securely as they contain sensitive information about the referral.
     *
     * `POST /v1/referrals`
     */
    createRequest(
        body: NonNullable<
            paths['/v1/referrals']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<paths['/v1/referrals']['post']['responses']['200']['content']['application/json']> {
        return this._core.request<
            paths['/v1/referrals']['post']['responses']['200']['content']['application/json']
        >('POST', '/v1/referrals', { body, options });
    }

    /**
     * Gets a referral by ID
     *
     * Returns a referral object by ID if it exists.
     *
     * `GET /v1/referrals/{id}`
     */
    get(
        id: paths['/v1/referrals/{id}']['get']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<
        paths['/v1/referrals/{id}']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v1/referrals/{id}']['get']['responses']['200']['content']['application/json']
        >('GET', `/v1/referrals/${encodeURIComponent(id)}`, { options });
    }

    /**
     * List referrals
     *
     * Returns referrals created.
     * *Note*: This doesn't include referrals that have expired.
     *
     * `GET /v1/referrals`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    list(
        query?: paths['/v1/referrals']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<
        paths['/v1/referrals']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.list<
            paths['/v1/referrals']['get']['responses']['200']['content']['application/json']
        >('/v1/referrals', { query, options });
    }

    /**
     * Process a delayed EIN document after upload
     *
     * Processes a delayed EIN document after it has been uploaded.
     *
     * This endpoint should be called after successfully uploading an IRS EIN Confirmation document (CP-575, CP-575 fax sheet, or 147C) using the
     * standard document upload flow (`/v1/referrals/{id}/document_upload` with `type: IRS_EIN_CONFIRMATION`).
     *
     * The `document_id` should be the `id` returned from the document upload request.
     *
     * `POST /v1/referrals/{id}/process_ein_document`
     */
    processDelayedEINDocument(
        id: paths['/v1/referrals/{id}/process_ein_document']['post']['parameters']['path']['id'],
        body: NonNullable<
            paths['/v1/referrals/{id}/process_ein_document']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<void> {
        return this._core.request<void>(
            'POST',
            `/v1/referrals/${encodeURIComponent(id)}/process_ein_document`,
            { body, options },
        );
    }
}

export class BrexOnboarding {
    readonly referrals: Referrals;
    constructor(core: BrexCore) {
        this.referrals = new Referrals(core);
    }
}
