// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import { BrexCore } from '../core/client';
import type { BrexOptions } from '../core/options';
import { BrexOnboarding } from './client.gen';

export * from '../core';
export { BrexOnboarding, Referrals } from './client.gen';
export type * from './schemas.gen';
export type { components as OnboardingComponents, paths as OnboardingPaths } from './types.gen';

/** Standalone client for the Brex Onboarding API. */
export function createOnboardingClient(options: BrexOptions): BrexOnboarding {
    return new BrexOnboarding(new BrexCore(options));
}
