// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import type { components } from './types.gen';

export type Account = components['schemas']['Account'];
export type Address = components['schemas']['Address'];
export type Applicant = components['schemas']['Applicant'];
export type Application = components['schemas']['Application'];
export type ApplicationStatus = components['schemas']['ApplicationStatus'];
export type BeneficialOwner = components['schemas']['BeneficialOwner'];
export type Business = components['schemas']['Business'];
export type Cash = components['schemas']['Cash'];
export type CompanyRelationship = components['schemas']['CompanyRelationship'];
export type ContactPreference = components['schemas']['ContactPreference'];
export type CreateDocumentRequest = components['schemas']['CreateDocumentRequest'];
export type CreateReferralRequest = components['schemas']['CreateReferralRequest'];
export type Document = components['schemas']['Document'];
export type DocumentType = components['schemas']['DocumentType'];
export type DomesticInstruction = components['schemas']['DomesticInstruction'];
export type IdentityDocument = components['schemas']['IdentityDocument'];
export type IdentityDocumentType = components['schemas']['IdentityDocumentType'];
export type IncorporationType = components['schemas']['IncorporationType'];
export type Instruction = components['schemas']['Instruction'];
export type InternationalInstruction = components['schemas']['InternationalInstruction'];
export type ProcessDelayedEINDocumentRequest =
    components['schemas']['ProcessDelayedEINDocumentRequest'];
export type Product = components['schemas']['Product'];
export type Prong = components['schemas']['Prong'];
export type Referral = components['schemas']['Referral'];
export type ReferralPage = components['schemas']['ReferralPage'];
export type ReferralStatus = components['schemas']['ReferralStatus'];
