// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import type { BrexCore } from '../core/client';
import type { RequestOptions } from '../core/options';
import type { PagePromise } from '../core/pagination';
import type { paths } from './types.gen';

export class WebhookGroups {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Add Webhook Group Members
     * `POST /v1/webhooks/groups/{id}/add_members`
     */
    addMembers(
        id: paths['/v1/webhooks/groups/{id}/add_members']['post']['parameters']['path']['id'],
        body: NonNullable<
            paths['/v1/webhooks/groups/{id}/add_members']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<void> {
        return this._core.request<void>(
            'POST',
            `/v1/webhooks/groups/${encodeURIComponent(id)}/add_members`,
            { body, options },
        );
    }

    /**
     * Create Webhook Group
     * `POST /v1/webhooks/groups`
     * Sends an `Idempotency-Key` header: `options.idempotencyKey`, or an auto-generated UUID.
     */
    create(
        body: NonNullable<
            paths['/v1/webhooks/groups']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<
        paths['/v1/webhooks/groups']['post']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v1/webhooks/groups']['post']['responses']['200']['content']['application/json']
        >('POST', '/v1/webhooks/groups', { body, idempotency: 'required', options });
    }

    /**
     * Delete Webhook Group
     * `DELETE /v1/webhooks/groups/{id}`
     */
    delete(
        id: paths['/v1/webhooks/groups/{id}']['delete']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<void> {
        return this._core.request<void>('DELETE', `/v1/webhooks/groups/${encodeURIComponent(id)}`, {
            options,
        });
    }

    /**
     * Get Webhook Group
     * `GET /v1/webhooks/groups/{id}`
     */
    get(
        id: paths['/v1/webhooks/groups/{id}']['get']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<
        paths['/v1/webhooks/groups/{id}']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v1/webhooks/groups/{id}']['get']['responses']['200']['content']['application/json']
        >('GET', `/v1/webhooks/groups/${encodeURIComponent(id)}`, { options });
    }

    /**
     * List Webhook Groups
     * `GET /v1/webhooks/groups`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    list(
        query?: paths['/v1/webhooks/groups']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<
        paths['/v1/webhooks/groups']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.list<
            paths['/v1/webhooks/groups']['get']['responses']['200']['content']['application/json']
        >('/v1/webhooks/groups', { query, options });
    }

    /**
     * List Webhook Group Members
     * `GET /v1/webhooks/groups/{id}/members`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    listMembers(
        id: paths['/v1/webhooks/groups/{id}/members']['get']['parameters']['path']['id'],
        query?: paths['/v1/webhooks/groups/{id}/members']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<
        paths['/v1/webhooks/groups/{id}/members']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.list<
            paths['/v1/webhooks/groups/{id}/members']['get']['responses']['200']['content']['application/json']
        >(`/v1/webhooks/groups/${encodeURIComponent(id)}/members`, { query, options });
    }

    /**
     * Remove Webhook Group Members
     * `POST /v1/webhooks/groups/{id}/remove_members`
     */
    removeMembers(
        id: paths['/v1/webhooks/groups/{id}/remove_members']['post']['parameters']['path']['id'],
        body: NonNullable<
            paths['/v1/webhooks/groups/{id}/remove_members']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<void> {
        return this._core.request<void>(
            'POST',
            `/v1/webhooks/groups/${encodeURIComponent(id)}/remove_members`,
            { body, options },
        );
    }
}

export class Webhooks {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Register Webhook
     * `POST /v1/webhooks`
     * Sends an `Idempotency-Key` header: `options.idempotencyKey`, or an auto-generated UUID.
     */
    create(
        body: NonNullable<
            paths['/v1/webhooks']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<paths['/v1/webhooks']['post']['responses']['200']['content']['application/json']> {
        return this._core.request<
            paths['/v1/webhooks']['post']['responses']['200']['content']['application/json']
        >('POST', '/v1/webhooks', { body, idempotency: 'required', options });
    }

    /**
     * Unregister Webhook
     * `DELETE /v1/webhooks/{id}`
     */
    delete(
        id: paths['/v1/webhooks/{id}']['delete']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<void> {
        return this._core.request<void>('DELETE', `/v1/webhooks/${encodeURIComponent(id)}`, {
            options,
        });
    }

    /**
     * Get Webhook
     * `GET /v1/webhooks/{id}`
     */
    get(
        id: paths['/v1/webhooks/{id}']['get']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<
        paths['/v1/webhooks/{id}']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v1/webhooks/{id}']['get']['responses']['200']['content']['application/json']
        >('GET', `/v1/webhooks/${encodeURIComponent(id)}`, { options });
    }

    /**
     * List Webhooks
     * `GET /v1/webhooks`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    list(
        query?: paths['/v1/webhooks']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<
        paths['/v1/webhooks']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.list<
            paths['/v1/webhooks']['get']['responses']['200']['content']['application/json']
        >('/v1/webhooks', { query, options });
    }

    /**
     * List Webhook Secrets
     * `GET /v1/webhooks/secrets`
     */
    listSecrets(
        options?: RequestOptions,
    ): Promise<
        paths['/v1/webhooks/secrets']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v1/webhooks/secrets']['get']['responses']['200']['content']['application/json']
        >('GET', '/v1/webhooks/secrets', { options });
    }

    /**
     * Update Webhook
     * `PUT /v1/webhooks/{id}`
     */
    update(
        id: paths['/v1/webhooks/{id}']['put']['parameters']['path']['id'],
        body: NonNullable<
            paths['/v1/webhooks/{id}']['put']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<
        paths['/v1/webhooks/{id}']['put']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v1/webhooks/{id}']['put']['responses']['200']['content']['application/json']
        >('PUT', `/v1/webhooks/${encodeURIComponent(id)}`, { body, options });
    }
}

export class BrexWebhooks {
    readonly webhookGroups: WebhookGroups;
    readonly webhooks: Webhooks;
    constructor(core: BrexCore) {
        this.webhookGroups = new WebhookGroups(core);
        this.webhooks = new Webhooks(core);
    }
}
