// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import { BrexCore } from "../core/client";
import type { BrexOptions } from "../core/options";
import { BrexWebhooks } from "./client.gen";

export * from "../core";
export { BrexWebhooks, WebhookGroups, Webhooks } from "./client.gen";
export type * from "./schemas.gen";
export type { components as WebhooksComponents, paths as WebhooksPaths } from "./types.gen";

/** Standalone client for the Brex Webhooks API. */
export function createWebhooksClient(options: BrexOptions): BrexWebhooks {
  return new BrexWebhooks(new BrexCore(options));
}
