// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import type { components } from "./types.gen";

export type AccountingRecordReadyForExport =
  components["schemas"]["AccountingRecordReadyForExport"];
export type AddWebhookGroupMembersRequest = components["schemas"]["AddWebhookGroupMembersRequest"];
export type ApplicationStatus = components["schemas"]["ApplicationStatus"];
export type CreateWebhookGroupRequest = components["schemas"]["CreateWebhookGroupRequest"];
export type CreateWebhookSubscriptionRequest =
  components["schemas"]["CreateWebhookSubscriptionRequest"];
export type EventWrapper = components["schemas"]["EventWrapper"];
export type ExpensePaymentStatus = components["schemas"]["ExpensePaymentStatus"];
export type ExpensePaymentType = components["schemas"]["ExpensePaymentType"];
export type ExpensePaymentUpdated = components["schemas"]["ExpensePaymentUpdated"];
export type Merchant = components["schemas"]["Merchant"];
export type Money = components["schemas"]["Money"];
export type Page_WebhookGroupMember_ = components["schemas"]["Page_WebhookGroupMember_"];
export type Page_WebhookGroup_ = components["schemas"]["Page_WebhookGroup_"];
export type Page_WebhookSubscription_ = components["schemas"]["Page_WebhookSubscription_"];
export type PaymentStatusReason = components["schemas"]["PaymentStatusReason"];
export type PaymentType = components["schemas"]["PaymentType"];
export type ProductApplication = components["schemas"]["ProductApplication"];
export type ReferralActivated = components["schemas"]["ReferralActivated"];
export type ReferralApplicationStatusChanged =
  components["schemas"]["ReferralApplicationStatusChanged"];
export type ReferralCreated = components["schemas"]["ReferralCreated"];
export type RemoveWebhookGroupMembersRequest =
  components["schemas"]["RemoveWebhookGroupMembersRequest"];
export type TransferFailed = components["schemas"]["TransferFailed"];
export type TransferProcessed = components["schemas"]["TransferProcessed"];
export type UpdateWebhookSubscriptionRequest =
  components["schemas"]["UpdateWebhookSubscriptionRequest"];
export type UserAttributes = components["schemas"]["UserAttributes"];
export type UserUpdated = components["schemas"]["UserUpdated"];
export type WebhookEventType = components["schemas"]["WebhookEventType"];
export type WebhookGroup = components["schemas"]["WebhookGroup"];
export type WebhookGroupMember = components["schemas"]["WebhookGroupMember"];
export type WebhookGroupMemberInput = components["schemas"]["WebhookGroupMemberInput"];
export type WebhookGroupMemberType = components["schemas"]["WebhookGroupMemberType"];
export type WebhookSecret = components["schemas"]["WebhookSecret"];
export type WebhookSecretStatus = components["schemas"]["WebhookSecretStatus"];
export type WebhookSubscription = components["schemas"]["WebhookSubscription"];
export type WebhookSubscriptionStatus = components["schemas"]["WebhookSubscriptionStatus"];
