// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate
export interface paths {
    '/v1/webhooks': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Webhooks
         * @description List the webhooks you have registered
         */
        get: operations['listWebhookSubscriptions'];
        put?: never;
        /**
         * Register Webhook
         * @description Register an endpoint to start receiving selected webhook events
         */
        post: operations['createWebhookSubscription'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/webhooks/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Webhook
         * @description Get details of a webhook
         */
        get: operations['getWebhookSubscription'];
        /**
         * Update Webhook
         * @description Update a webhook.
         *     You can update the endpoint url, event types that the endpoint receives, or temporarily deactivate the webhook.
         */
        put: operations['updateWebhookSubscription'];
        post?: never;
        /**
         * Unregister Webhook
         * @description Unregister a webhook if you want to stop receiving webhook events
         */
        delete: operations['deleteWebhookSubscription'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/webhooks/groups': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Webhook Groups
         * @description Lists webhook groups.
         */
        get: operations['listWebhookGroups'];
        put?: never;
        /**
         * Create Webhook Group
         * @description Creates a webhook group.
         */
        post: operations['createWebhookGroup'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/webhooks/groups/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Webhook Group
         * @description Gets a webhook group.
         */
        get: operations['getWebhookGroup'];
        put?: never;
        post?: never;
        /**
         * Delete Webhook Group
         * @description Deletes a webhook group and all its members.
         */
        delete: operations['deleteWebhookGroup'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/webhooks/groups/{id}/add_members': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Webhook Group Members
         * @description Adds members to webhook groups.
         */
        post: operations['addWebhookGroupMembers'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/webhooks/groups/{id}/members': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Webhook Group Members
         * @description Lists the members currently in the specified webhook group.
         */
        get: operations['listWebhookGroupMembers'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/webhooks/groups/{id}/remove_members': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Remove Webhook Group Members
         * @description Removes members from webhook groups.
         */
        post: operations['removeWebhookGroupMembers'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v1/webhooks/secrets': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Webhook Secrets
         * @description This endpoint returns a set of webhook signing secrets used to validate the webhook.
         *     Usually only one key will be returned in the response. After key rotation, this endpoint will return two keys:
         *     the new key, and the key that will be revoked soon. There will also be two signatures in the 'Webhook-Signature' request header.
         *     Your application should use all keys available to validate the webhook request. If validation passes for any
         *     of the keys returned, the webhook payload is valid.
         */
        get: operations['listWebhookSecrets'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A list of accounting records are ready for export. */
        AccountingRecordReadyForExport: {
            /** @description List of accounting record IDs ready for export. */
            accountingRecordIds: string[];
            /**
             * @description This is the `id` returned in the [Get Company](/openapi/team_api/#operation/getCompany) endpoint.
             *     You can use the `company_id` to determine which access token to use when you get the details from our API endpoints.
             */
            companyId: string;
            event_type: components['schemas']['WebhookEventType'] & unknown;
        } & components['schemas']['EventWrapper'];
        AddWebhookGroupMembersRequest: {
            /** @description The list of webhook group members to add to the group. */
            members: components['schemas']['WebhookGroupMemberInput'][];
        };
        /**
         * @description Application status of a product.
         *
         *     `NO_ACCOUNT` - There is no active application, and the product account is not provisioned.
         *
         *     `ACTIVE` - The application is approved, and the product account is provisioned.
         *
         *     `NOT_SUBMITTED` - The application is started but not yet submitted.
         *
         *     `INFORMATION_PENDING` - The application is submitted and additional information is requested.
         *
         *     `MANUAL_REVIEW` - The application is under manual review.
         *
         *     `PROCESSING` - The application is submitted and is under review.
         *
         *     `REJECTED` - The application is rejected.
         *
         *     `CLOSED` - The product account is closed.
         * @enum {string}
         */
        ApplicationStatus:
            | 'NO_ACCOUNT'
            | 'ACTIVE'
            | 'NOT_SUBMITTED'
            | 'INFORMATION_PENDING'
            | 'MANUAL_REVIEW'
            | 'PROCESSING'
            | 'REJECTED'
            | 'CLOSED';
        CreateWebhookGroupRequest: {
            /**
             * @description The name for the webhook group.
             * @example Some Webhook Group
             */
            name: string;
        };
        CreateWebhookSubscriptionRequest: {
            /** @description A list of the webhook event types this subscription will listen to. */
            event_types: components['schemas']['WebhookEventType'][];
            /**
             * @description ID of the webhook group to which this subscription applies, if any. This is only available for partners.
             * @example wg_123
             */
            group_id?: string | null;
            /**
             * @description The URL to which webhook events will be sent. Must be a valid HTTPS URL.
             * @example https://example.com/webhook
             */
            url: string;
        };
        EventWrapper: Record<string, never>;
        /**
         * @description `PENDING`:The transaction is yet to be captured. It may be approved, yet to be approved, or yet to be declined.
         *
         *     `DECLINED`: The transaction was declined.
         * @enum {string}
         */
        ExpensePaymentStatus: 'PENDING' | 'DECLINED';
        /**
         * @description `PURCHASE`: A pending transaction for making a purchase.
         *
         *     `REFUND`: A pending transaction for a refund.
         *
         *     `WITHDRAWAL`: A pending transaction for a withdrawal.
         *
         *     `DECLINED`: A pending transaction that was declined and will not be completed.
         * @enum {string}
         */
        ExpensePaymentType: 'PURCHASE' | 'REFUND' | 'WITHDRAWAL' | 'DECLINED';
        /**
         * @description The webhook will be sent when an expense payment changes status.
         *      Subscription must be registered with a user with the CARD_ADMIN role.
         */
        ExpensePaymentUpdated: {
            amount?: (components['schemas']['Money'] & unknown) | null;
            billing_amount?: (components['schemas']['Money'] & unknown) | null;
            /** @description The ID of the card that is associated with the expense. */
            card_id: string;
            /**
             * @description This is the `id` returned in the [Get Company](/openapi/team_api/#operation/getCompany) endpoint.
             *     You can use the `company_id` to determine which access token to use when you get the details from our API endpoints.
             */
            company_id: string;
            event_type: components['schemas']['WebhookEventType'];
            /** @description Unique ID associated with the expense. */
            expense_id: string;
            merchant: components['schemas']['Merchant'] & unknown;
            original_amount?: (components['schemas']['Money'] & unknown) | null;
            /** @description The authorization code of the associated card expense. */
            payment_authorization_code?: string | null;
            /**
             * @deprecated
             * @description Succeeded by the merchant::raw_descriptor field.
             */
            payment_description: string;
            payment_status: components['schemas']['ExpensePaymentStatus'];
            payment_status_reason: components['schemas']['PaymentStatusReason'];
            payment_type: components['schemas']['ExpensePaymentType'];
            /**
             * Format: date-time
             * @description The time the purchase was made.
             */
            purchased_at?: string | null;
            /**
             * Format: int32
             * @description Version of this expense. This value starts at 1 and is incremented by 1 with every update.
             * @example 1
             */
            version: number;
        } & components['schemas']['EventWrapper'];
        Merchant: {
            /** @description Merchant's country, in ISO 3166-1 alpha-3 format. */
            country: string;
            /** @description A four-digit number listed in ISO 18245 for retail financial services, e.g. 4121 for Taxicabs and Rideshares. Please refer to https://en.wikipedia.org/wiki/Merchant_category_code for more details. */
            mcc: string;
            /** @description Merchant descriptor, it can be the merchant name. */
            raw_descriptor: string;
        };
        /**
         * @description Money fields can be signed or unsigned. Fields are signed (an unsigned value will be interpreted as positive). The amount of money will be represented in the smallest denomination
         *     of the currency indicated. For example, USD 7.00 will be represented in cents with an amount of 700.
         */
        Money: {
            /**
             * Format: int64
             * @description The amount of money, in the smallest denomination of the currency indicated by currency. For example, when currency is USD, amount is in cents.
             * @example 700
             */
            amount: number;
            /**
             * @description The type of currency, in ISO 4217 format.
             * @default USD
             * @example USD
             */
            currency: string | null;
        };
        Page_WebhookGroup_: {
            items: components['schemas']['WebhookGroup'][];
            next_cursor?: string | null;
        };
        Page_WebhookGroupMember_: {
            items: components['schemas']['WebhookGroupMember'][];
            next_cursor?: string | null;
        };
        Page_WebhookSubscription_: {
            items: components['schemas']['WebhookSubscription'][];
            next_cursor?: string | null;
        };
        /**
         * @description The reason for the payment's status.
         * @enum {string}
         */
        PaymentStatusReason:
            | 'OTHER'
            | 'APPROVED'
            | 'EXCEEDED_BUDGET_LIMIT'
            | 'BUDGET_EXPIRED'
            | 'NO_BUDGET'
            | 'BUDGET_NOT_YET_STARTED'
            | 'BUDGET_CATEGORY_RESTRICTION'
            | 'BUDGET_MERCHANT_RESTRICTION'
            | 'SUSPECTED_FRAUD'
            | 'EXCEEDED_GLOBAL_LIMIT'
            | 'EXCEEDED_USER_LIMIT'
            | 'EXCEEDED_CARD_LIMIT'
            | 'INVALID_EXPIRATION_DATE'
            | 'CARD_NOT_ACTIVE'
            | 'INVALID_CARD_CREDENTIALS'
            | 'INVALID_BILLING_ADDRESS'
            | 'CARD_SUSPENDED'
            | 'CARD_TERMINATED'
            | 'CARD_EXPIRED'
            | 'MCC_BLOCKED'
            | 'USER_SUSPENDED'
            | 'INVALID_PIN'
            | 'INVALID_CVV'
            | 'EXCEEDED_PIN_ATTEMPTS'
            | 'INSIDE_SANCTIONED_COUNTRY'
            | 'SOFT_EXPIRATION'
            | 'TRANSFERRED_CARD_NEW_MERCHANT'
            | 'EXCEEDED_ANCESTOR_BUDGET_LIMIT'
            | 'EXCEEDED_BUDGET_TRANSACTION_LIMIT'
            | 'TOS_BLOCKED'
            | 'COMPLIANCE_BLOCKED';
        /**
         * @description Only ACH, DOMESTIC_WIRE, CHEQUE, INTERNATIONAL_WIRE, BOOK_TRANSFER, and STABLECOIN details can be retrieved from the Payments API.
         * @enum {string}
         */
        PaymentType:
            | 'ACH'
            | 'DOMESTIC_WIRE'
            | 'CHEQUE'
            | 'INTERNATIONAL_WIRE'
            | 'BOOK_TRANSFER'
            | 'STABLECOIN'
            | 'ACH_RETURN'
            | 'WIRE_RETURN'
            | 'CHEQUE_RETURN';
        /** @description The product application details for the referral. */
        ProductApplication: {
            cash: components['schemas']['ApplicationStatus'];
        };
        /** @description The webhook will be sent when a user signs up with the referral link. */
        ReferralActivated: {
            event_type: components['schemas']['WebhookEventType'];
            /** @description The referral ID */
            referral_id: string;
        } & components['schemas']['EventWrapper'];
        /** @description The webhook will be sent when the application status is changed. */
        ReferralApplicationStatusChanged: {
            application: components['schemas']['ProductApplication'];
            event_type: components['schemas']['WebhookEventType'];
            /** @description The referral ID */
            referral_id: string;
        } & components['schemas']['EventWrapper'];
        /** @description The webhook will be sent when a referral is created. */
        ReferralCreated: {
            event_type: components['schemas']['WebhookEventType'];
            /** @description The referral ID */
            referral_id: string;
        } & components['schemas']['EventWrapper'];
        RemoveWebhookGroupMembersRequest: {
            /** @description The list of webhook group members to remove from the group. */
            members: components['schemas']['WebhookGroupMemberInput'][];
        };
        /** @description The webhook will be sent when a transfer failed. */
        TransferFailed: {
            /** @description This is the `id` returned in the [Get Company](/openapi/team_api/#operation/getCompany) endpoint. You can use the `company_id` to determine which access token to use when you get the details from our API endpoints. */
            company_id: string;
            event_type: components['schemas']['WebhookEventType'];
            payment_type: components['schemas']['PaymentType'];
            /** @description The original transaction ID that is returned when the payment type is ACH_RETURN, WIRE_RETURN and CHEQUE_RETURN. */
            return_for_id?: string | null;
            /** @description The transfer ID */
            transfer_id: string;
        } & components['schemas']['EventWrapper'];
        /** @description The webhook will be sent when a transfer is processed. */
        TransferProcessed: {
            /** @description This is the `id` returned in the [Get Company](/openapi/team_api/#operation/getCompany) endpoint. You can use the `company_id` to determine which access token to use when you get the details from our API endpoints. */
            company_id: string;
            event_type: components['schemas']['WebhookEventType'];
            payment_type: components['schemas']['PaymentType'];
            /** @description The original transaction ID that is returned when the payment type is ACH_RETURN, WIRE_RETURN and CHEQUE_RETURN. */
            return_for_id?: string | null;
            /** @description The transfer ID */
            transfer_id: string;
        } & components['schemas']['EventWrapper'];
        UpdateWebhookSubscriptionRequest: {
            /** @description A list of the webhook event types this subscription will listen to. */
            event_types: components['schemas']['WebhookEventType'][];
            /**
             * @description ID of the webhook group to which this subscription applies, if any. This is only available for partners.
             * @example wg_123
             */
            group_id?: string | null;
            status: components['schemas']['WebhookSubscriptionStatus'] & unknown;
            /**
             * @description The URL to which webhook events will be sent. Must be a valid HTTPS URL.
             * @example https://example.com/webhook
             */
            url: string;
        };
        /** @enum {string} */
        UserAttributes: 'STATUS' | 'MANAGER_ID' | 'DEPARTMENT_ID' | 'LOCATION_ID';
        /** @description The webhook will be sent when a user is updated. */
        UserUpdated: {
            company_id: string;
            event_type: components['schemas']['WebhookEventType'];
            updated_attributes: components['schemas']['UserAttributes'][];
            user_id: string;
        } & components['schemas']['EventWrapper'];
        /** @enum {string} */
        WebhookEventType:
            | 'REFERRAL_CREATED'
            | 'REFERRAL_ACTIVATED'
            | 'REFERRAL_APPLICATION_STATUS_CHANGED'
            | 'TRANSFER_PROCESSED'
            | 'TRANSFER_FAILED'
            | 'EXPENSE_PAYMENT_UPDATED'
            | 'USER_UPDATED'
            | 'EMBEDDED_CARD_TRANSACTION_UPDATED'
            | 'EMBEDDED_CARD_UPDATED'
            | 'EMBEDDED_ACCOUNT_UPDATED'
            | 'EMBEDDED_CARD_SHIPPING_UPDATED'
            | 'EMBEDDED_DISPUTE_UPDATED'
            | 'PARTNERSHIP_INTEGRATION_CONNECTION_UPDATED'
            | 'EMBEDDED_CARD_AUTHORIZATION'
            | 'EMBEDDED_FRAUD_ALERT'
            | 'EMBEDDED_BILLING_GROUP_UPDATED'
            | 'EMBEDDED_LEGAL_ENTITY_UPDATED'
            | 'EMBEDDED_BILLING_STATEMENT_UPDATED'
            | 'EMBEDDED_USER_STATUS_UPDATED'
            | 'ACCOUNTING_RECORD_READY_FOR_EXPORT';
        /**
         * Webhook Group
         * @description A webhook group, which can be used by webhook subscriptions to target only the webhook group members. When an event occurs and it belongs to a member of the group, the webhooks will be sent only to the subscriptions that are associated with the group. If there is no group associated with the event, then the webhook will be sent to all subscriptions that are not associated with any group. Webhook groups are only available for partners.
         */
        WebhookGroup: {
            /**
             * @description The ID of the webhook group.
             * @example wg_123
             */
            id: string;
            /**
             * @description The name for the webhook group.
             * @example Some Webhook Group
             */
            name: string;
        };
        /**
         * Webhook Group Member
         * @description A member of a webhook group.
         */
        WebhookGroupMember: {
            /**
             * @description The ID of the webhook group this member belongs to.
             * @example wg_123
             */
            group_id: string;
            /**
             * @description The ID of the webhook group member.
             * @example cuacc_123
             */
            member_id: string;
            member_type: components['schemas']['WebhookGroupMemberType'] & unknown;
        };
        WebhookGroupMemberInput: {
            /** @description The ID of the webhook group member. */
            member_id: string;
            member_type: components['schemas']['WebhookGroupMemberType'] & unknown;
        };
        /**
         * @description The type of a webhook group member.
         * @enum {string}
         */
        WebhookGroupMemberType: 'ACCOUNT';
        /**
         * Webhook Secret
         * @description A webhook secret, which can be used to validate that incoming webhook messages were sent by Brex.
         */
        WebhookSecret: {
            /**
             * @description The payload of the secret to be used for webhook validation.
             * @example whsec_123
             */
            secret: string;
            status: components['schemas']['WebhookSecretStatus'] & unknown;
        };
        /**
         * @description The status of a webhook secret.
         * @enum {string}
         */
        WebhookSecretStatus: 'ACTIVE' | 'PENDING_REVOKE' | 'REVOKED';
        /**
         * Webhook Subscription
         * @description A webhook subscription. When events of the specified event types occur, they will be sent to the given URL. If the subscription applies to a webhook group, then only events that apply to the members of that group will be sent. If it does not apply to any group, then only events that don't apply to any specific group will be sent. Webhook groups are only available for partners.
         */
        WebhookSubscription: {
            /**
             * @description List of event types that this webhook subscription listens to.
             * @example ["EXPENSE_PAYMENT_UPDATED"]
             */
            event_types: components['schemas']['WebhookEventType'][];
            /**
             * @description ID of the webhook group to which this subscription applies, if any.
             * @example wg_123
             */
            group_id?: string | null;
            /**
             * @description ID of the webhook subscription.
             * @example wsub_123
             */
            id: string;
            status: components['schemas']['WebhookSubscriptionStatus'] & unknown;
            /**
             * @description The URL to which webhook events will be sent. Must be a valid HTTPS URL.
             * @example https://example.com/webhook
             */
            url: string;
        };
        /**
         * @description The status of a webhook subscription.
         * @enum {string}
         */
        WebhookSubscriptionStatus: 'ACTIVE' | 'INACTIVE';
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listWebhookSubscriptions: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Page_WebhookSubscription_'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createWebhookSubscription: {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['CreateWebhookSubscriptionRequest'];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['WebhookSubscription'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getWebhookSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['WebhookSubscription'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateWebhookSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['UpdateWebhookSubscriptionRequest'];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['WebhookSubscription'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteWebhookSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listWebhookGroups: {
        parameters: {
            query?: {
                /** @description Cursor for pagination. */
                cursor?: string | null;
                /** @description Limit for pagination. If not provided, defaults to 100. Cannot be greater than 1000. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Page_WebhookGroup_'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createWebhookGroup: {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['CreateWebhookGroupRequest'];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['WebhookGroup'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getWebhookGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the webhook group to retrieve. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['WebhookGroup'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteWebhookGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the webhook group to delete. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addWebhookGroupMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the webhook group to add members to. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['AddWebhookGroupMembersRequest'];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listWebhookGroupMembers: {
        parameters: {
            query?: {
                /** @description Cursor for pagination. */
                cursor?: string | null;
                /** @description Limit for pagination. If not provided, defaults to 100. Cannot be greater than 1000. */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description The ID of the webhook group to retrieve members for. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Page_WebhookGroupMember_'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeWebhookGroupMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the webhook group to remove members from. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['RemoveWebhookGroupMembersRequest'];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listWebhookSecrets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['WebhookSecret'][];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
