// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import { BrexCore } from '../core/client';
import type { BrexOptions } from '../core/options';
import { BrexAccounting } from './client.gen';

export * from '../core';
export { AccountingIntegrations, AccountingRecords, BrexAccounting } from './client.gen';
export type * from './schemas.gen';
export type { components as AccountingComponents, paths as AccountingPaths } from './types.gen';

/** Standalone client for the Brex Accounting API. */
export function createAccountingClient(options: BrexOptions): BrexAccounting {
    return new BrexAccounting(new BrexCore(options));
}
