openapi: 3.0.1
info:
  title: Budgets API
  description: |

    The budgets API lets you manage your Brex Budgets and Spend Limits.
  contact:
    name: Admin
    url: https://brex.com
    email: developer-support@brex.com
  version: '1.0'
  x-logo:
    altText: Brex Logo
    url: https://www.brex.com/logo.png
servers:
  - url: https://api.brex.com
    description: Production
  - url: https://api-staging.brex.com
    description: >-
      Staging (Note: This is not a sandbox. It will not work with customer
      tokens.)
security:
  - OAuth2: []
tags:
  - name: Spend Limits (v1)
    description: >-
      Endpoints for Spend Limits data. Please note that /v1/budgets targets
      spend limits, and will soon be deprecated in favor of /v2/spend_limits.
  - name: Budget Programs
    description: Endpoints for Budget Programs data.
  - name: Budgets
    description: Endpoints for Budgets data.
  - name: Spend Limits (v2)
    description: Endpoints for spend limits data.
paths:
  /v1/budget_programs:
    get:
      tags:
        - Budget Programs
      summary: |

        List Budget Programs
      description: |

        Lists Budget Programs belonging to this account
      operationId: listBudgetPrograms
      security:
        - OAuth2:
            - budgets.readonly
            - budgets
  /v1/budget_programs/{id}:
    get:
      tags:
        - Budget Programs
      summary: |

        Get Budget Program
      description: |

        Retrieves a Budget Program by ID
      operationId: getBudgetProgramById
      security:
        - OAuth2:
            - budgets.readonly
            - budgets
  /v1/budgets:
    get:
      tags:
        - Spend Limits (v1)
      summary: |

        List Spend Limits
      description: |

        Lists Spend Limits belonging to this account
      operationId: listBudgets
      security:
        - OAuth2:
            - budgets.readonly
            - budgets
    post:
      tags:
        - Spend Limits (v1)
      summary: |

        Create Spend Limit
      description: |

        Creates a Spend Limit
      operationId: createBudget
      security:
        - OAuth2:
            - budgets
  /v1/budgets/{id}:
    get:
      tags:
        - Spend Limits (v1)
      summary: |

        Get Spend Limit
      description: |

        Retrieves a Spend Limit by ID
      operationId: getBudgetById
      security:
        - OAuth2:
            - budgets.readonly
            - budgets
    put:
      tags:
        - Spend Limits (v1)
      summary: |

        Update Spend Limit
      description: |

        Updates a Spend Limit
      operationId: updateBudget
      security:
        - OAuth2:
            - budgets
  /v1/budgets/{id}/archive:
    post:
      tags:
        - Spend Limits (v1)
      summary: |

        Archive a Spend Limit
      description: >

        Archives a Spend Limit, making it unusable for future expenses and
        removing it from the UI
      operationId: archiveBudget
      security:
        - OAuth2:
            - budgets
  /v2/budgets:
    get:
      tags:
        - Budgets
      summary: |

        List Budgets
      description: |

        Retrieves a list of Budgets
      operationId: listSpendBudgets
      security:
        - OAuth2:
            - budgets.readonly
            - budgets
    post:
      tags:
        - Budgets
      summary: |

        Create Budget
      description: |

        Creates a Budget
      operationId: createSpendBudget
      security:
        - OAuth2:
            - budgets
  /v2/budgets/{id}:
    get:
      tags:
        - Budgets
      summary: |

        Get Budget
      description: |

        Retrieves a Budget by ID
      operationId: getSpendBudgetById
      security:
        - OAuth2:
            - budgets.readonly
            - budgets
    put:
      tags:
        - Budgets
      summary: |

        Update Budget
      description: |

        Updates a Budget
      operationId: updateSpendBudget
      security:
        - OAuth2:
            - budgets
  /v2/budgets/{id}/archive:
    post:
      tags:
        - Budgets
      summary: |

        Archive a Budget
      description: >

        Archives a Budget, making any Spend Limits beneath it unusable for
        future expenses and removing it from the UI
      operationId: archiveSpendBudget
      security:
        - OAuth2:
            - budgets
  /v2/spend_limits:
    get:
      tags:
        - Spend Limits (v2)
      summary: |

        List Spend Limits
      description: |

        Retrieves a list of Spend Limits
      operationId: listSpendLimits
      security:
        - OAuth2:
            - budgets.readonly
            - budgets
    post:
      tags:
        - Spend Limits (v2)
      summary: |

        Create Spend Limit
      description: |

        Creates a Spend Limit
      operationId: createSpendLimit
      security:
        - OAuth2:
            - budgets
  /v2/spend_limits/{id}:
    get:
      tags:
        - Spend Limits (v2)
      summary: |

        Get Spend Limit
      description: |

        Retrieves a Spend Limit by ID
      operationId: getSpendLimitById
      security:
        - OAuth2:
            - budgets.readonly
            - budgets
    put:
      tags:
        - Spend Limits (v2)
      summary: |

        Update Spend Limit
      description: |

        Updates a Spend Limit
      operationId: updateSpendLimit
      security:
        - OAuth2:
            - budgets
  /v2/spend_limits/{id}/archive:
    post:
      tags:
        - Spend Limits (v2)
      summary: |

        Archive a Spend Limit
      description: >

        Archives a Spend Limit, making it unusable for future expenses and
        removing it from the UI
      operationId: archiveSpendLimit
      security:
        - OAuth2:
            - budgets
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: OAuth2 security scheme
      flows:
        authorizationCode:
          authorizationUrl: https://accounts-api.brex.com/oauth2/default/v1/authorize
          tokenUrl: https://accounts-api.brex.com/oauth2/default/v1/token
          scopes:
            openid: openid
            offline_access: offline access
            budgets: View and manage budgets data
            budgets.readonly: View budgets data
x-explorer-enabled: false
