openapi: 3.0.1
info:
  title: Team API
  description: |

    The team API lets you manage users, departments, locations, and cards.
  contact:
    name: Admin
    url: https://brex.com
    email: developer-support@brex.com
  version: '1.0'
  x-logo:
    altText: Brex Logo
    url: https://www.brex.com/logo.png
servers:
  - url: https://api.brex.com
    description: Production
  - url: https://api-staging.brex.com
    description: >-
      Staging (Note: This is not a sandbox. It will not work with customer
      tokens.)
security:
  - OAuth2: []
tags:
  - name: Users
    description: Endpoints for user management.
  - name: Locations
    description: Endpoints for location management.
  - name: Departments
    description: Endpoints for department management.
  - name: Titles
    description: Endpoints for title management.
  - name: Cards
    description: Endpoints for card management.
  - name: Legal Entities
    description: Endpoints for legal entities.
paths:
  /v2/cards:
    get:
      tags:
        - Cards
      summary: |

        List cards
      description: |

        Lists all cards by a `user_id`.
        Only cards with `limit_type = CARD` have `spend_controls`
      operationId: listCardsByUserId
      security:
        - OAuth2:
            - cards.readonly
            - cards
    post:
      tags:
        - Cards
      summary: |

        Create card
      description: >

        Creates a new card.

        The `spend_controls` field is required when `limit_type` = `CARD`.

        The `mailing_address` field is required for physical cards and is the
        shipping address used to send the card; it is not the same as the
        billing and mailing address used for online purchases.

        The first 2 lines of this address must be under 60 characters long. Each
        user can only have up to 10 active physical cards.

        For Empower accounts, this endpoint requires budget management. If your
        account does not have access to budget management features, a 403
        response status will be returned. 

        If this is the case and you want to gain access to this endpoint, please
        contact Brex support.
      operationId: createCard
      security:
        - OAuth2:
            - cards
  /v2/cards/{id}:
    get:
      tags:
        - Cards
      summary: |

        Get card
      description: >

        Retrieves a card by ID. Only cards with `limit_type = CARD` have
        `spend_controls`
      operationId: getCardById
      security:
        - OAuth2:
            - cards
            - cards.readonly
    put:
      tags:
        - Cards
      summary: |

        Update card
      description: |

        Update an existing vendor card
      operationId: updateCard
      security:
        - OAuth2:
            - cards
  /v2/cards/{id}/lock:
    post:
      tags:
        - Cards
      summary: |

        Lock card
      description: >

        Locks an existing, unlocked card. And the card owner will receive a
        notification about it.
      operationId: lockCard
      security:
        - OAuth2:
            - cards
  /v2/cards/{id}/pan:
    get:
      tags:
        - Cards
      summary: |

        Get card number
      description: |

        Retrieves card number, CVV, and expiration date of a card by ID.
      operationId: getCardNumber
      security:
        - OAuth2:
            - cards.pan
      servers:
        - url: https://api.brex.com
          description: Production
        - url: https://api-staging.brex.com
          description: >-
            Staging (Note: This is not a sandbox. It will not work with customer
            tokens.)
  /v2/cards/{id}/secure_email:
    post:
      tags:
        - Cards
      summary: |

        Create secure email to send card number 
      description: >

        Creates a secure email to send card number, CVV, and expiration date of
        a card by ID to the specified email.


        This endpoint is currently gated. If you would like to request access,
        please reach out to

        developer-support@brex.com
      operationId: emailCardNumber
      security:
        - OAuth2:
            - cards.pan
  /v2/cards/{id}/terminate:
    post:
      tags:
        - Cards
      summary: |

        Terminate card
      description: >

        Terminates an existing card. The card owner will receive a notification
        about it.
      operationId: terminateCard
      security:
        - OAuth2:
            - cards
  /v2/cards/{id}/unlock:
    post:
      tags:
        - Cards
      summary: |

        Unlock card
      description: |

        Unlocks an existing card.
      operationId: unlockCard
      security:
        - OAuth2:
            - cards
  /v2/company:
    get:
      tags:
        - Companies
      summary: |

        Get company
      description: >

        This endpoint returns the company associated with the OAuth2 access
        token.
      operationId: getCompany
      security:
        - OAuth2:
            - companies.readonly
  /v2/departments:
    get:
      tags:
        - Departments
      summary: |

        List departments
      description: |

        This endpoint lists all departments.
      operationId: listDepartments
      security:
        - OAuth2:
            - departments
            - departments.readonly
    post:
      tags:
        - Departments
      summary: |

        Create department
      description: |

        This endpoint creates a new department
      operationId: createDepartment
      security:
        - OAuth2:
            - departments
  /v2/departments/{id}:
    get:
      tags:
        - Departments
      summary: |

        Get department
      description: |

        This endpoint gets a department by ID.
      operationId: getDepartmentById
      security:
        - OAuth2:
            - departments
            - departments.readonly
  /v2/legal_entities:
    get:
      tags:
        - Legal Entities
      summary: |

        List legal entities
      description: |

        List legal entities for the account.
      operationId: listLegalEntities
      security:
        - OAuth2:
            - legal_entities
            - legal_entities.readonly
  /v2/legal_entities/{id}:
    get:
      tags:
        - Legal Entities
      summary: |

        Get legal entity
      description: |

        Get a legal entity by its ID.
      operationId: getLegalEntity
      security:
        - OAuth2:
            - legal_entities
            - legal_entities.readonly
  /v2/locations:
    get:
      tags:
        - Locations
      summary: |

        List locations
      description: |

        This endpoint lists all locations.
      operationId: listLocations
      security:
        - OAuth2:
            - locations
            - locations.readonly
    post:
      tags:
        - Locations
      summary: |

        Create location
      description: |

        This endpoint creates a new location.
      operationId: createLocation
      security:
        - OAuth2:
            - locations
  /v2/locations/{id}:
    get:
      tags:
        - Locations
      summary: |

        Get location
      description: |

        This endpoint gets a location by ID.
      operationId: getLocationById
      security:
        - OAuth2:
            - locations
            - locations.readonly
  /v2/titles:
    get:
      tags:
        - Titles
      summary: |

        List titles
      description: |

        This endpoint lists all titles.
      operationId: listTitles
      security:
        - OAuth2:
            - titles
            - titles.readonly
    post:
      tags:
        - Titles
      summary: |

        Create title
      description: |

        This endpoint creates a new title
      operationId: createTitle
      security:
        - OAuth2:
            - titles
  /v2/titles/{id}:
    get:
      tags:
        - Titles
      summary: |

        Get title
      description: |

        This endpoint gets a title by ID.
      operationId: getTitleById
      security:
        - OAuth2:
            - titles
            - titles.readonly
  /v2/users:
    get:
      tags:
        - Users
      summary: |

        List users
      description: >

        This endpoint lists all users. To find a user id by email, you can
        filter using the `email` query parameter.
      operationId: listUsers
      security:
        - OAuth2:
            - users
            - users.readonly
    post:
      tags:
        - Users
      summary: |

        Invite user
      description: >

        This endpoint invites a new user as an employee.

        To update user's role, check out [this
        article](https://support.brex.com/how-do-i-change-another-user-s-role/).
      operationId: createUser
      security:
        - OAuth2:
            - users
  /v2/users/me:
    get:
      tags:
        - Users
      summary: |

        Get current user
      description: |

        This endpoint returns the user associated with the OAuth2 access token.
      operationId: getMe
      security:
        - OAuth2:
            - users
            - users.readonly
  /v2/users/{id}:
    get:
      tags:
        - Users
      summary: |

        Get user
      description: |

        This endpoint gets a user by ID.
      operationId: getUserById
      security:
        - OAuth2:
            - users
            - users.readonly
    put:
      tags:
        - Users
      summary: |

        Update user
      description: >

        This endpoint updates a user. Any parameters not provided will be left
        unchanged.
      operationId: updateUser
      security:
        - OAuth2:
            - users
  /v2/users/{id}/limit:
    get:
      tags:
        - Users
      summary: |

        Get limit for the user
      description: >

        This endpoint gets the monthly limit for the user including the monthly
        available limit.
      operationId: getUserLimit
      security:
        - OAuth2:
            - users
            - users.readonly
    post:
      tags:
        - Users
      summary: |

        Set limit for the user
      description: >

        This endpoint sets the monthly limit for a user. 

        The limit amount must be non-negative. 

        To unset the monthly limit of the user, just set `monthly_limit` to
        null.
      operationId: setUserLimit
      security:
        - OAuth2:
            - users
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: OAuth2 security scheme
      flows:
        authorizationCode:
          authorizationUrl: https://accounts-api.brex.com/oauth2/default/v1/authorize
          tokenUrl: https://accounts-api.brex.com/oauth2/default/v1/token
          scopes:
            openid: openid
            offline_access: offline access
            users.readonly: View user data
            users: View and manage user data
            locations.readonly: View location data
            locations: View and manage location data
            departments.readonly: View department data
            departments: View and manage department data
            titles: View and manage title data
            titles.readonly: View title data
            cards: View and manage card data
            cards.readonly: View card data
            cards.pan: View and Send card number data
            legal_entities: View and manage legal entities
            legal_entities.readonly: View legal entities
x-explorer-enabled: false
