// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import { BrexCore } from "../core/client";
import type { BrexOptions } from "../core/options";
import { BrexTravel } from "./client.gen";

export * from "../core";
export { BrexTravel, Trips } from "./client.gen";
export type * from "./schemas.gen";
export type { components as TravelComponents, paths as TravelPaths } from "./types.gen";

/** Standalone client for the Brex Travel API. */
export function createTravelClient(options: BrexOptions): BrexTravel {
  return new BrexTravel(new BrexCore(options));
}
