// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import type { components } from "./types.gen";

export type Address = components["schemas"]["Address"];
export type Address_GeoCoordinates = components["schemas"]["Address.GeoCoordinates"];
export type AirBookingData = components["schemas"]["AirBookingData"];
export type AirBookingData_CabinClass = components["schemas"]["AirBookingData.CabinClass"];
export type AirBookingData_DocumentNumber = components["schemas"]["AirBookingData.DocumentNumber"];
export type AirBookingData_Flight = components["schemas"]["AirBookingData.Flight"];
export type AirBookingData_FlightEndpoint = components["schemas"]["AirBookingData.FlightEndpoint"];
export type AirBookingData_FlightNumber = components["schemas"]["AirBookingData.FlightNumber"];
export type AirBookingData_FlightSeat = components["schemas"]["AirBookingData.FlightSeat"];
export type AirBookingData_FlightSeatStatus =
  components["schemas"]["AirBookingData.FlightSeatStatus"];
export type AirBookingData_FlightTicket = components["schemas"]["AirBookingData.FlightTicket"];
export type AirBookingData_Journey = components["schemas"]["AirBookingData.Journey"];
export type Booking = components["schemas"]["Booking"];
export type Booking_Data = components["schemas"]["Booking.Data"];
export type Booking_Source = components["schemas"]["Booking.Source"];
export type Booking_Time = components["schemas"]["Booking.Time"];
export type Booking_Type = components["schemas"]["Booking.Type"];
export type BookingStatus = components["schemas"]["BookingStatus"];
export type CarRentalBookingData = components["schemas"]["CarRentalBookingData"];
export type CarRentalBookingData_CarClass = components["schemas"]["CarRentalBookingData.CarClass"];
export type CarRentalBookingData_CarDetails =
  components["schemas"]["CarRentalBookingData.CarDetails"];
export type CarRentalBookingData_RentalEndpoint =
  components["schemas"]["CarRentalBookingData.RentalEndpoint"];
export type CarRentalBookingData_ReservationDetails =
  components["schemas"]["CarRentalBookingData.ReservationDetails"];
export type LodgingBookingData = components["schemas"]["LodgingBookingData"];
export type LodgingBookingData_ContactInfo =
  components["schemas"]["LodgingBookingData.ContactInfo"];
export type LodgingBookingData_LodgingDetails =
  components["schemas"]["LodgingBookingData.LodgingDetails"];
export type LodgingBookingData_ReservationDetails =
  components["schemas"]["LodgingBookingData.ReservationDetails"];
export type LodgingBookingData_Room = components["schemas"]["LodgingBookingData.Room"];
export type Page_Booking_ = components["schemas"]["Page_Booking_"];
export type Page_Trip_ = components["schemas"]["Page_Trip_"];
export type RailBookingData = components["schemas"]["RailBookingData"];
export type RailBookingData_RailClass = components["schemas"]["RailBookingData.RailClass"];
export type RailBookingData_RailJourney = components["schemas"]["RailBookingData.RailJourney"];
export type RailBookingData_RailLeg = components["schemas"]["RailBookingData.RailLeg"];
export type RailBookingData_RailSeat = components["schemas"]["RailBookingData.RailSeat"];
export type RailBookingData_RailStation = components["schemas"]["RailBookingData.RailStation"];
export type RailBookingData_RailStationType =
  components["schemas"]["RailBookingData.RailStationType"];
export type RailBookingData_Vehicle = components["schemas"]["RailBookingData.Vehicle"];
export type RailBookingData_VehicleType = components["schemas"]["RailBookingData.VehicleType"];
export type Traveler = components["schemas"]["Traveler"];
export type Traveler_Name = components["schemas"]["Traveler.Name"];
export type Traveler_Type = components["schemas"]["Traveler.Type"];
export type Trip = components["schemas"]["Trip"];
export type Trip_Status = components["schemas"]["Trip.Status"];
