// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import { AccountingIntegrations, AccountingRecords } from './accounting/client.gen';
import { BudgetPrograms, Budgets, BudgetsV1, SpendLimits } from './budgets/client.gen';
import { BrexCore } from './core/client';
import type { BrexOptions } from './core/options';
import { CardExpenses, Expenses, Receipts } from './expenses/client.gen';
import { Fields, FieldValues } from './fields/client.gen';
import { Referrals } from './onboarding/client.gen';
import { LinkedAccounts, Transfers, Vendors } from './payments/client.gen';
import {
    Cards,
    Companies,
    Departments,
    LegalEntities,
    Locations,
    Titles,
    Users,
} from './team/client.gen';
import { Accounts, Transactions } from './transactions/client.gen';
import { Trips } from './travel/client.gen';
import { WebhookGroups, Webhooks } from './webhooks/client.gen';

export * from './core';

/**
 * Unified client covering every Brex API.
 *
 * Importing `Brex` pulls in all ten API surfaces; if bundle size matters,
 * import a single API from its subpath instead (e.g. `brex/payments`).
 */
export class Brex {
    readonly accountingIntegrations: AccountingIntegrations;
    readonly accountingRecords: AccountingRecords;
    readonly accounts: Accounts;
    readonly budgetPrograms: BudgetPrograms;
    readonly budgets: Budgets;
    readonly budgetsV1: BudgetsV1;
    readonly cardExpenses: CardExpenses;
    readonly cards: Cards;
    readonly companies: Companies;
    readonly departments: Departments;
    readonly expenses: Expenses;
    readonly fields: Fields;
    readonly fieldValues: FieldValues;
    readonly legalEntities: LegalEntities;
    readonly linkedAccounts: LinkedAccounts;
    readonly locations: Locations;
    readonly receipts: Receipts;
    readonly referrals: Referrals;
    readonly spendLimits: SpendLimits;
    readonly titles: Titles;
    readonly transactions: Transactions;
    readonly transfers: Transfers;
    readonly trips: Trips;
    readonly users: Users;
    readonly vendors: Vendors;
    readonly webhookGroups: WebhookGroups;
    readonly webhooks: Webhooks;

    constructor(options: BrexOptions) {
        const core = new BrexCore(options);
        this.accountingIntegrations = new AccountingIntegrations(core);
        this.accountingRecords = new AccountingRecords(core);
        this.accounts = new Accounts(core);
        this.budgetPrograms = new BudgetPrograms(core);
        this.budgets = new Budgets(core);
        this.budgetsV1 = new BudgetsV1(core);
        this.cardExpenses = new CardExpenses(core);
        this.cards = new Cards(core);
        this.companies = new Companies(core);
        this.departments = new Departments(core);
        this.expenses = new Expenses(core);
        this.fields = new Fields(core);
        this.fieldValues = new FieldValues(core);
        this.legalEntities = new LegalEntities(core);
        this.linkedAccounts = new LinkedAccounts(core);
        this.locations = new Locations(core);
        this.receipts = new Receipts(core);
        this.referrals = new Referrals(core);
        this.spendLimits = new SpendLimits(core);
        this.titles = new Titles(core);
        this.transactions = new Transactions(core);
        this.transfers = new Transfers(core);
        this.trips = new Trips(core);
        this.users = new Users(core);
        this.vendors = new Vendors(core);
        this.webhookGroups = new WebhookGroups(core);
        this.webhooks = new Webhooks(core);
    }
}
