// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import type { BrexCore } from '../core/client';
import type { RequestOptions } from '../core/options';
import type { PagePromise } from '../core/pagination';
import type { paths } from './types.gen';

export class Accounts {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Get cash account by ID
     *
     * This endpoint returns the cash account associated with the provided ID with its status.
     *
     * `GET /v2/accounts/cash/{id}` — requires OAuth scope: `accounts.cash.readonly`
     */
    get(
        id: paths['/v2/accounts/cash/{id}']['get']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<
        paths['/v2/accounts/cash/{id}']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v2/accounts/cash/{id}']['get']['responses']['200']['content']['application/json']
        >('GET', `/v2/accounts/cash/${encodeURIComponent(id)}`, { options });
    }

    /**
     * Get primary cash account
     *
     * This endpoint returns the primary cash account with its status. There will always be only one primary account.
     *
     * `GET /v2/accounts/cash/primary` — requires OAuth scope: `accounts.cash.readonly`
     */
    getPrimary(
        options?: RequestOptions,
    ): Promise<
        paths['/v2/accounts/cash/primary']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v2/accounts/cash/primary']['get']['responses']['200']['content']['application/json']
        >('GET', '/v2/accounts/cash/primary', { options });
    }

    /**
     * List cash accounts
     *
     * This endpoint lists all the existing cash accounts with their status.
     *
     * `GET /v2/accounts/cash` — requires OAuth scope: `accounts.cash.readonly`
     */
    list(
        options?: RequestOptions,
    ): Promise<
        paths['/v2/accounts/cash']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v2/accounts/cash']['get']['responses']['200']['content']['application/json']
        >('GET', '/v2/accounts/cash', { options });
    }

    /**
     * List card accounts
     *
     * This endpoint lists all accounts of card type.
     *
     * `GET /v2/accounts/card` — requires OAuth scope: `accounts.card.readonly`
     */
    listCard(
        options?: RequestOptions,
    ): Promise<
        paths['/v2/accounts/card']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v2/accounts/card']['get']['responses']['200']['content']['application/json']
        >('GET', '/v2/accounts/card', { options });
    }

    /**
     * List cash account statements.
     *
     * This endpoint lists all finalized statements for the cash account by ID.
     *
     * `GET /v2/accounts/cash/{id}/statements` — requires OAuth scope: `statements.cash.readonly`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    listCashStatements(
        id: paths['/v2/accounts/cash/{id}/statements']['get']['parameters']['path']['id'],
        query?: paths['/v2/accounts/cash/{id}/statements']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<
        paths['/v2/accounts/cash/{id}/statements']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.list<
            paths['/v2/accounts/cash/{id}/statements']['get']['responses']['200']['content']['application/json']
        >(`/v2/accounts/cash/${encodeURIComponent(id)}/statements`, { query, options });
    }

    /**
     * List primary card account statements.
     *
     * This endpoint lists all finalized statements for the primary card account.
     *
     * `GET /v2/accounts/card/primary/statements` — requires OAuth scope: `statements.card.readonly`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    listPrimaryCardStatements(
        query?: paths['/v2/accounts/card/primary/statements']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<
        paths['/v2/accounts/card/primary/statements']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.list<
            paths['/v2/accounts/card/primary/statements']['get']['responses']['200']['content']['application/json']
        >('/v2/accounts/card/primary/statements', { query, options });
    }
}

export class Transactions {
    constructor(private readonly _core: BrexCore) {}

    /**
     * List transactions for the selected cash account.
     *
     * This endpoint lists all transactions for the cash account with the selected ID.
     *
     * `GET /v2/transactions/cash/{id}` — requires OAuth scope: `transactions.cash.readonly`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    listCash(
        id: paths['/v2/transactions/cash/{id}']['get']['parameters']['path']['id'],
        query?: paths['/v2/transactions/cash/{id}']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<
        paths['/v2/transactions/cash/{id}']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.list<
            paths['/v2/transactions/cash/{id}']['get']['responses']['200']['content']['application/json']
        >(`/v2/transactions/cash/${encodeURIComponent(id)}`, { query, options });
    }

    /**
     * List transactions for all card accounts.
     *
     * This endpoint lists all settled transactions for all card accounts.
     * Regular users may only fetch their own "PURCHASE","REFUND" and "CHARGEBACK" settled transactions.
     *
     * `GET /v2/transactions/card/primary` — requires OAuth scope: `transactions.card.readonly`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    listPrimaryCard(
        query?: paths['/v2/transactions/card/primary']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<
        paths['/v2/transactions/card/primary']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.list<
            paths['/v2/transactions/card/primary']['get']['responses']['200']['content']['application/json']
        >('/v2/transactions/card/primary', { query, options });
    }
}

export class BrexTransactions {
    readonly accounts: Accounts;
    readonly transactions: Transactions;
    constructor(core: BrexCore) {
        this.accounts = new Accounts(core);
        this.transactions = new Transactions(core);
    }
}
