// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import { BrexCore } from '../core/client';
import type { BrexOptions } from '../core/options';
import { BrexTransactions } from './client.gen';

export * from '../core';
export { Accounts, BrexTransactions, Transactions } from './client.gen';
export type * from './schemas.gen';
export type { components as TransactionsComponents, paths as TransactionsPaths } from './types.gen';

/** Standalone client for the Brex Transactions API. */
export function createTransactionsClient(options: BrexOptions): BrexTransactions {
    return new BrexTransactions(new BrexCore(options));
}
