// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import type { components } from './types.gen';

export type CardAccount = components['schemas']['CardAccount'];
export type CardTransaction = components['schemas']['CardTransaction'];
export type CardTransactionType = components['schemas']['CardTransactionType'];
export type CashAccount = components['schemas']['CashAccount'];
export type CashTransaction = components['schemas']['CashTransaction'];
export type CashTransactionType = components['schemas']['CashTransactionType'];
export type Merchant = components['schemas']['Merchant'];
export type Money = components['schemas']['Money'];
export type Page_CardTransaction_ = components['schemas']['Page_CardTransaction_'];
export type Page_CashAccount_ = components['schemas']['Page_CashAccount_'];
export type Page_CashTransaction_ = components['schemas']['Page_CashTransaction_'];
export type Page_Statement_ = components['schemas']['Page_Statement_'];
export type Statement = components['schemas']['Statement'];
export type StatementPeriod = components['schemas']['StatementPeriod'];
export type Status = components['schemas']['Status'];
