// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate
export interface paths {
    '/v2/accounts/card': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List card accounts
         * @description This endpoint lists all accounts of card type.
         */
        get: operations['listCardAccounts'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v2/accounts/card/primary/statements': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List primary card account statements.
         * @description This endpoint lists all finalized statements for the primary card account.
         */
        get: operations['listPrimaryCardStatements'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v2/accounts/cash': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List cash accounts
         * @description This endpoint lists all the existing cash accounts with their status.
         */
        get: operations['listAccounts'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v2/accounts/cash/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cash account by ID
         * @description This endpoint returns the cash account associated with the provided ID with its status.
         */
        get: operations['getAccount'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v2/accounts/cash/{id}/statements': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List cash account statements.
         * @description This endpoint lists all finalized statements for the cash account by ID.
         */
        get: operations['listCashStatements'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v2/accounts/cash/primary': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get primary cash account
         * @description This endpoint returns the primary cash account with its status. There will always be only one primary account.
         */
        get: operations['getPrimaryAccount'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v2/transactions/card/primary': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List transactions for all card accounts.
         * @description This endpoint lists all settled transactions for all card accounts.
         *     Regular users may only fetch their own "PURCHASE","REFUND" and "CHARGEBACK" settled transactions.
         */
        get: operations['listPrimaryCardTransactions'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v2/transactions/cash/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List transactions for the selected cash account.
         * @description This endpoint lists all transactions for the cash account with the selected ID.
         */
        get: operations['listCashTransactions'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CardAccount: {
            account_limit?: components['schemas']['Money'] | null;
            available_balance?: components['schemas']['Money'] | null;
            current_balance?: components['schemas']['Money'] | null;
            current_statement_period: components['schemas']['StatementPeriod'];
            /** @description ID of the card account */
            id: string;
            status?: components['schemas']['Status'] | null;
        };
        CardTransaction: {
            amount: components['schemas']['Money'];
            /** @description ID of the card used for the transaction. Null when type is REWARDS_CREDIT or COLLECTION. */
            card_id?: string | null;
            /**
             * @description Set of key value pairs associated with this object. Please do not store any personally identifiable or sensitive information here.
             *     Limitations: maximum of 50 keys, keys cannot exceed 40 characters, values cannot exceed 500 characters.
             */
            card_metadata?: {
                [key: string]: string;
            } | null;
            /** @description The card transaction operation reference ID. Null when type is REWARDS_CREDIT, COLLECTION, or BNPL_FEE. */
            card_transaction_operation_reference_id?: string | null;
            /** @description Description of the transaction */
            description: string;
            /** @description The expense ID related to the card transaction. */
            expense_id?: string | null;
            id: string;
            /**
             * Format: date
             * @description ISO 8601 date string
             */
            initiated_at_date: string;
            merchant?: components['schemas']['Merchant'] | null;
            /**
             * Format: date
             * @description ISO 8601 date string
             */
            posted_at_date: string;
            type?: components['schemas']['CardTransactionType'] | null;
        };
        /** @enum {string} */
        CardTransactionType:
            | 'PURCHASE'
            | 'REFUND'
            | 'CHARGEBACK'
            | 'REWARDS_CREDIT'
            | 'COLLECTION'
            | 'BNPL_FEE';
        CashAccount: {
            account_number: string;
            available_balance: components['schemas']['Money'];
            current_balance: components['schemas']['Money'];
            /** @description ID of the cash account */
            id: string;
            name: string;
            /** @description Whether or not this account is the primary account. There will always be only one primary account. */
            primary: boolean;
            routing_number: string;
            status?: components['schemas']['Status'] | null;
        };
        CashTransaction: {
            amount?: components['schemas']['Money'] | null;
            /** @description Description of the transaction */
            description: string;
            id: string;
            /**
             * Format: date
             * @description ISO 8601 date of when the payment is initiated
             */
            initiated_at_date: string;
            /**
             * Format: date
             * @description ISO 8601 date of when the payment is posted
             */
            posted_at_date: string;
            /** @description Transfer ID to fetch additional metadata about the transaction using `https://developer.brex.com/openapi/payments_api/#operation/getTransfersById` */
            transfer_id?: string | null;
            type?: components['schemas']['CashTransactionType'] | null;
        };
        /** @enum {string} */
        CashTransactionType:
            | 'PAYMENT'
            | 'DIVIDEND'
            | 'FEE'
            | 'ADJUSTMENT'
            | 'INTEREST'
            | 'CARD_COLLECTION'
            | 'REWARDS_REDEMPTION'
            | 'RECEIVABLES_OFFERS_ADVANCE'
            | 'FBO_TRANSFER'
            | 'RECEIVABLES_OFFERS_REPAYMENT'
            | 'RECEIVABLES_OFFERS_COLLECTION'
            | 'BREX_OPERATIONAL_TRANSFER'
            | 'INTRA_CUSTOMER_ACCOUNT_BOOK_TRANSFER'
            | 'BOOK_TRANSFER'
            | 'CRYPTO_BRIDGE'
            | 'STABLECOIN'
            | 'TRANSACTION_FEES_COLLECTION'
            | 'PAYBACK';
        Merchant: {
            /** @description Merchant's country, in ISO 3166-1 alpha-3 format. */
            country: string;
            /** @description A four-digit number listed in ISO 18245 for retail financial services, e.g. 4121 for Taxicabs and Rideshares. Please refer to https://en.wikipedia.org/wiki/Merchant_category_code for more details. */
            mcc: string;
            /** @description Merchant descriptor, it can be the merchant name. */
            raw_descriptor: string;
        };
        /**
         * @description Money fields can be signed or unsigned. Fields are signed (an unsigned value will be interpreted as positive). The amount of money will be represented in the smallest denomination
         *     of the currency indicated. For example, USD 7.00 will be represented in cents with an amount of 700.
         */
        Money: {
            /**
             * Format: int64
             * @description The amount of money, in the smallest denomination of the currency indicated by currency. For example, when currency is USD, amount is in cents.
             * @example 700
             */
            amount: number;
            /**
             * @description The type of currency, in ISO 4217 format.
             * @default USD
             * @example USD
             */
            currency: string | null;
        };
        Page_CardTransaction_: {
            items: components['schemas']['CardTransaction'][];
            next_cursor?: string | null;
        };
        Page_CashAccount_: {
            items: components['schemas']['CashAccount'][];
            next_cursor?: string | null;
        };
        Page_CashTransaction_: {
            items: components['schemas']['CashTransaction'][];
            next_cursor?: string | null;
        };
        Page_Statement_: {
            items: components['schemas']['Statement'][];
            next_cursor?: string | null;
        };
        Statement: {
            end_balance?: components['schemas']['Money'] | null;
            id: string;
            period: components['schemas']['StatementPeriod'];
            start_balance?: components['schemas']['Money'] | null;
        };
        StatementPeriod: {
            /**
             * Format: date
             * @description End date of the statement period at UTC 00:00:00 (exclusive)
             */
            end_date: string;
            /**
             * Format: date
             * @description Start date of the statement period at UTC 00:00:00 (inclusive)
             */
            start_date: string;
        };
        /** @enum {string} */
        Status: 'ACTIVE';
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCardAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns a list of card accounts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['CardAccount'][];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPrimaryCardStatements: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns a list of primary card account statements. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Page_Statement_'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns a list of cash accounts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Page_CashAccount_'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the cash account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['CashAccount'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCashStatements: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns a list of cash account statements. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Page_Statement_'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPrimaryAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the primary cash account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['CashAccount'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPrimaryCardTransactions: {
        parameters: {
            query?: {
                cursor?: string | null;
                'expand[]'?: string[] | null;
                limit?: number | null;
                /**
                 * @description Shows only transactions with a `posted_at_date` on or after this date-time. This parameter is the date-time notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6)
                 * @example 2022-12-12T23:59:59.999
                 */
                posted_at_start?: string | null;
                user_ids?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns a list of card transactions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Page_CardTransaction_'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCashTransactions: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number | null;
                /**
                 * @description Shows only transactions with a `posted_at_date` on or after this date-time. This parameter is the date-time notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6)
                 * @example 2022-12-12T23:59:59.999
                 */
                posted_at_start?: string | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns a list of cash transactions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Page_CashTransaction_'];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
