// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import type { BrexCore } from '../core/client';
import type { RequestOptions } from '../core/options';
import type { PagePromise } from '../core/pagination';
import type { paths } from './types.gen';

export class LinkedAccounts {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Lists linked accounts
     *
     * This endpoint lists all bank connections that are eligible to make ACH transfers to Brex business account
     *
     * `GET /v1/linked_accounts` — requires OAuth scope: `linked_accounts.readonly`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    list(
        query?: paths['/v1/linked_accounts']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<
        paths['/v1/linked_accounts']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.list<
            paths['/v1/linked_accounts']['get']['responses']['200']['content']['application/json']
        >('/v1/linked_accounts', { query, options });
    }
}

export class Transfers {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Create transfer
     *
     * This endpoint creates a new transfer.
     *
     * Currently, the API can only create transfers for the following payment rails:
     * - ACH
     * - DOMESTIC_WIRE
     * - CHEQUE
     * - INTERNATIONAL_WIRES
     *
     * **Transaction Descriptions**
     * * For outgoing check payments, a successful transfer will return a response containing a description value with a format of `Check #<check number> to <recipient_name> - <external_memo>`.
     * * For book transfers (from one Brex Business account to another), the recipient value will have a format of `<customer_account.dba_name> - <external_memo>` and the sender will have a format of `<target customer account's dba name> - <external_memo>`.
     * * For other payment rails, the format will be `<counterparty_name> - <external_memo>`, where Counterparty name is `payment_instrument.beneficiary_name` or `contact.name`
     * For vendors created from the Payments API, the `counterparty_name` will be the `company_name` [field](/openapi/payments_api/#operation/createVendor!path=company_name&t=request).
     *
     * **Reminder**: You may not use the Brex API for any activity that requires a license or registration from any
     * governmental authority without Brex's prior review and approval. This includes but is not limited to any money services
     * business or money transmission activity.
     *
     * Please review the <a href="https://www.brex.com/legal/developer-portal/">Brex Access Agreement</a> and contact us if
     * you have any questions.
     *
     * `POST /v1/transfers` — requires OAuth scope: `transfers`
     * Sends an `Idempotency-Key` header: `options.idempotencyKey`, or an auto-generated UUID.
     */
    create(
        body: NonNullable<
            paths['/v1/transfers']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<paths['/v1/transfers']['post']['responses']['200']['content']['application/json']> {
        return this._core.request<
            paths['/v1/transfers']['post']['responses']['200']['content']['application/json']
        >('POST', '/v1/transfers', { body, idempotency: 'required', options });
    }

    /**
     * Create incoming transfer
     *
     * This endpoint creates a new incoming transfer. You may use use any eligible bank account connection to fund (ACH Debit)
     * any active Brex business account.
     *
     * **Reminder**: You may not use the Brex API for any activity that requires a license or registration from any
     * governmental authority without Brex's prior review and approval. This includes but is not limited to any money services
     * business or money transmission activity.
     *
     * Please review the <a href="https://www.brex.com/legal/developer-portal/">Brex Access Agreement</a> and contact us if
     * you have any questions.
     *
     * `POST /v1/incoming_transfers` — requires OAuth scope: `incoming_transfers`
     * Sends an `Idempotency-Key` header: `options.idempotencyKey`, or an auto-generated UUID.
     */
    createIncoming(
        body: NonNullable<
            paths['/v1/incoming_transfers']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<
        paths['/v1/incoming_transfers']['post']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v1/incoming_transfers']['post']['responses']['200']['content']['application/json']
        >('POST', '/v1/incoming_transfers', { body, idempotency: 'required', options });
    }

    /**
     * Get transfer
     *
     * This endpoint gets a transfer by ID.
     *
     * Currently, the API can only return transfers for the following payment rails:
     * - ACH
     * - DOMESTIC_WIRE
     * - CHEQUE
     * - INTERNATIONAL_WIRE
     *
     * `GET /v1/transfers/{id}` — requires OAuth scope: `transfers.readonly`, `incoming_transfers`
     */
    get(
        id: paths['/v1/transfers/{id}']['get']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<
        paths['/v1/transfers/{id}']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v1/transfers/{id}']['get']['responses']['200']['content']['application/json']
        >('GET', `/v1/transfers/${encodeURIComponent(id)}`, { options });
    }

    /**
     * Lists transfers
     *
     * This endpoint lists existing transfers for an account.
     *
     * Currently, the API can only return transfers for the following payment rails:
     * - ACH
     * - DOMESTIC_WIRE
     * - CHEQUE
     * - INTERNATIONAL_WIRE
     *
     * `GET /v1/transfers` — requires OAuth scope: `transfers.readonly`, `incoming_transfers`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    list(
        query?: paths['/v1/transfers']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<
        paths['/v1/transfers']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.list<
            paths['/v1/transfers']['get']['responses']['200']['content']['application/json']
        >('/v1/transfers', { query, options });
    }
}

export class Vendors {
    constructor(private readonly _core: BrexCore) {}

    /**
     * Create vendor
     *
     * This endpoint creates a new vendor.
     *
     * `POST /v1/vendors` — requires OAuth scope: `vendors`
     * Sends an `Idempotency-Key` header: `options.idempotencyKey`, or an auto-generated UUID.
     */
    create(
        body: NonNullable<
            paths['/v1/vendors']['post']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<paths['/v1/vendors']['post']['responses']['200']['content']['application/json']> {
        return this._core.request<
            paths['/v1/vendors']['post']['responses']['200']['content']['application/json']
        >('POST', '/v1/vendors', { body, idempotency: 'required', options });
    }

    /**
     * Delete vendor.
     *
     * This endpoint deletes a vendor by ID.
     *
     * `DELETE /v1/vendors/{id}` — requires OAuth scope: `vendors`
     */
    delete(
        id: paths['/v1/vendors/{id}']['delete']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<void> {
        return this._core.request<void>('DELETE', `/v1/vendors/${encodeURIComponent(id)}`, {
            options,
        });
    }

    /**
     * Get vendor
     *
     * This endpoint gets a vendor by ID.
     *
     * `GET /v1/vendors/{id}` — requires OAuth scope: `vendors.readonly`
     */
    get(
        id: paths['/v1/vendors/{id}']['get']['parameters']['path']['id'],
        options?: RequestOptions,
    ): Promise<
        paths['/v1/vendors/{id}']['get']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v1/vendors/{id}']['get']['responses']['200']['content']['application/json']
        >('GET', `/v1/vendors/${encodeURIComponent(id)}`, { options });
    }

    /**
     * Lists vendors
     *
     * This endpoint lists all existing vendors for an account.
     * Takes an optional parameter to match by vendor name.
     *
     * `GET /v1/vendors` — requires OAuth scope: `vendors.readonly`
     * Await for a single page, or `for await` to iterate items across all pages.
     */
    list(
        query?: paths['/v1/vendors']['get']['parameters']['query'],
        options?: RequestOptions,
    ): PagePromise<paths['/v1/vendors']['get']['responses']['200']['content']['application/json']> {
        return this._core.list<
            paths['/v1/vendors']['get']['responses']['200']['content']['application/json']
        >('/v1/vendors', { query, options });
    }

    /**
     * Update vendor
     *
     * Updates an existing vendor by ID.
     *
     * `PUT /v1/vendors/{id}` — requires OAuth scope: `vendors`
     * Supports an optional `Idempotency-Key` via `options.idempotencyKey`.
     */
    update(
        id: paths['/v1/vendors/{id}']['put']['parameters']['path']['id'],
        body: NonNullable<
            paths['/v1/vendors/{id}']['put']['requestBody']
        >['content']['application/json'],
        options?: RequestOptions,
    ): Promise<
        paths['/v1/vendors/{id}']['put']['responses']['200']['content']['application/json']
    > {
        return this._core.request<
            paths['/v1/vendors/{id}']['put']['responses']['200']['content']['application/json']
        >('PUT', `/v1/vendors/${encodeURIComponent(id)}`, {
            body,
            idempotency: 'optional',
            options,
        });
    }
}

export class BrexPayments {
    readonly linkedAccounts: LinkedAccounts;
    readonly transfers: Transfers;
    readonly vendors: Vendors;
    constructor(core: BrexCore) {
        this.linkedAccounts = new LinkedAccounts(core);
        this.transfers = new Transfers(core);
        this.vendors = new Vendors(core);
    }
}
