// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import { BrexCore } from '../core/client';
import type { BrexOptions } from '../core/options';
import { BrexPayments } from './client.gen';

export * from '../core';
export { BrexPayments, LinkedAccounts, Transfers, Vendors } from './client.gen';
export type * from './schemas.gen';
export type { components as PaymentsComponents, paths as PaymentsPaths } from './types.gen';

/** Standalone client for the Brex Payments API. */
export function createPaymentsClient(options: BrexOptions): BrexPayments {
    return new BrexPayments(new BrexCore(options));
}
