// GENERATED by scripts/generate.ts — do not edit. Run: bun run generate

import type { components } from './types.gen';

export type ACHDetailsRequest = components['schemas']['ACHDetailsRequest'];
export type ACHDetailsResponse = components['schemas']['ACHDetailsResponse'];
export type AccountClass = components['schemas']['AccountClass'];
export type AccountType = components['schemas']['AccountType'];
export type Address = components['schemas']['Address'];
export type ApprovalType = components['schemas']['ApprovalType'];
export type Balance = components['schemas']['Balance'];
export type BankAccountDetailsResponse = components['schemas']['BankAccountDetailsResponse'];
export type BankConnection = components['schemas']['BankConnection'];
export type BankDetails = components['schemas']['BankDetails'];
export type BankType = components['schemas']['BankType'];
export type BeneficiaryBank = components['schemas']['BeneficiaryBank'];
export type BookTransferDetails = components['schemas']['BookTransferDetails'];
export type BookTransferDetailsResponse = components['schemas']['BookTransferDetailsResponse'];
export type BrexCashAccountDetails = components['schemas']['BrexCashAccountDetails'];
export type BrexCashAccountDetailsResponse =
    components['schemas']['BrexCashAccountDetailsResponse'];
export type BrexCashDetails = components['schemas']['BrexCashDetails'];
export type ChequeDetailsRequest = components['schemas']['ChequeDetailsRequest'];
export type ChequeDetailsResponse = components['schemas']['ChequeDetailsResponse'];
export type CounterParty = components['schemas']['CounterParty'];
export type CounterPartyBankDetails = components['schemas']['CounterPartyBankDetails'];
export type CounterPartyIncomingTransfer = components['schemas']['CounterPartyIncomingTransfer'];
export type CounterPartyIncomingTransferType =
    components['schemas']['CounterPartyIncomingTransferType'];
export type CounterPartyResponse = components['schemas']['CounterPartyResponse'];
export type CounterPartyResponseType = components['schemas']['CounterPartyResponseType'];
export type CounterPartyType = components['schemas']['CounterPartyType'];
export type CreateIncomingTransferRequest = components['schemas']['CreateIncomingTransferRequest'];
export type CreateTransferRequest = components['schemas']['CreateTransferRequest'];
export type CreateVendorRequest = components['schemas']['CreateVendorRequest'];
export type DomesticWireDetailsRequest = components['schemas']['DomesticWireDetailsRequest'];
export type DomesticWireDetailsResponse = components['schemas']['DomesticWireDetailsResponse'];
export type InternationalWireDetailsResponse =
    components['schemas']['InternationalWireDetailsResponse'];
export type Money = components['schemas']['Money'];
export type OriginatingAccount = components['schemas']['OriginatingAccount'];
export type OriginatingAccountResponse = components['schemas']['OriginatingAccountResponse'];
export type OriginatingAccountResponseType =
    components['schemas']['OriginatingAccountResponseType'];
export type OriginatingAccountType = components['schemas']['OriginatingAccountType'];
export type Page_BankConnection_ = components['schemas']['Page_BankConnection_'];
export type Page_Transfer_ = components['schemas']['Page_Transfer_'];
export type Page_VendorResponse_ = components['schemas']['Page_VendorResponse_'];
export type PaymentAccountDetails = components['schemas']['PaymentAccountDetails'];
export type PaymentAccountDetailsResponse = components['schemas']['PaymentAccountDetailsResponse'];
export type PaymentAccountRequest = components['schemas']['PaymentAccountRequest'];
export type PaymentAccountResponse = components['schemas']['PaymentAccountResponse'];
export type PaymentDetailsTypeRequest = components['schemas']['PaymentDetailsTypeRequest'];
export type PaymentDetailsTypeResponse = components['schemas']['PaymentDetailsTypeResponse'];
export type PaymentType = components['schemas']['PaymentType'];
export type ReceivingAccount = components['schemas']['ReceivingAccount'];
export type ReceivingAccountType = components['schemas']['ReceivingAccountType'];
export type Recipient = components['schemas']['Recipient'];
export type RecipientType = components['schemas']['RecipientType'];
export type Transfer = components['schemas']['Transfer'];
export type TransferCancellationReason = components['schemas']['TransferCancellationReason'];
export type TransferStatus = components['schemas']['TransferStatus'];
export type UpdateVendorRequest = components['schemas']['UpdateVendorRequest'];
export type VendorDetails = components['schemas']['VendorDetails'];
export type VendorDetailsResponse = components['schemas']['VendorDetailsResponse'];
export type VendorResponse = components['schemas']['VendorResponse'];
